### ISSUE TITLE
Assignment 2: Designing an interactive map experience

### ISSUE THREAD

**Issue by planemad** [mapschool/cartography#11]
**Brief** Design and develop a interactive web application on either of the following topics:
- Railway atlas of India
- Tourism map of a popular Indian destination
- Themed street map of an Indian city

**Evaluation**
- Relevance of the map narrative to the topic
- Visual experience of the cartographic style
- Complexity of datasets and data preprocessing

**Duration** 1 Week (Friday January 15)

cc @mapschool/infdpg14

**Comment by planemad** [comment]
@mapschool/infdpg14 By now everyone should be well underway with their topics. Don't forget to open an issue ticket here with a link to your repository. Its great that nobody faced any issues so far, looking forward to the outputs. 

![](https://cloud.githubusercontent.com/assets/12744420/12014746/2241ef42-ad58-11e5-843b-d44bed1decbb.gif)

In the meantime:
- http://visualoop.com/blog/90498/100-outstanding-interactive-maps-of-2015-part-1
- Portfolio of an [information designer](http://www.slaughterstudio.com/) who is at Mapbox for 1 week sprint

**Comment by kunchapu** [comment]
Hi Arun,

We are facing issue in adding data to the mapbox data set.  The type of data that we have is which connects cities / streets .  Is it possible for you to share any video related to it , ll b helpful.

**Comment by planemad** [comment]
Cannot help without understanding the problem completely. Can you share sample of the data, what was the error faced?

**Comment by planemad** [comment]
@kunchapu can you help me to understand the problem completely. Can you share sample of the data, or the error that was faced?

**Comment by planemad** [comment]
@mapschool/infdpg14 just a reminder, i will be posting a final progress chart for the class with the status of all their submissions for explorations and assignments that have been shared on Github so far.

**Comment by SuchismitaNaik** [comment]
Hi Arun,

This is the error we are getting while adding the data sets.

![error_faced](https://cloud.githubusercontent.com/assets/16536382/13028317/7220ea14-d291-11e5-9c2d-cf8aa82704e1.jpg)

**Comment by planemad** [comment]
@SuchismitaNaik it seems like the data is not in a valid format. You can paste the contents of the json here to check for issues: http://geojsonlint.com

**Comment by SuchismitaNaik** [comment]
Hi Arun,

It worked. I tried with csv file.

**Comment by nikhilshivpuja** [comment]
Hey Arun , trying to make my map/ style  toggle layers . So i followed this tutorial : https://www.mapbox.com/mapbox.js/example/v1.0.0/layers/ 

I changed the map call function to load my style .

Now for toggling the layers , i don't know what name to add in the addLayer command to call the layers i want , is there a way for me to see the layer name in mapbox studio   that i can use the addLayer call ? 

All my attempts are leading to 404 errors 

Also if i want to calculate the area of styled regions , is there any other function other than leaflet.geodesy ?

**Comment by planemad** [comment]
@nikhilshivpuja you need to be looking at mapbox-gl.js which is used for the new GL based maps that you see in Studio with smooth zooming. What you want is to follow this example https://www.mapbox.com/mapbox-gl-js/example/setstyle/

If you have a geojson object you can calculate this easily using turf.js http://turfjs.org/static/docs/module-turf_area.html

**Comment by nikhilshivpuja** [comment]
@planemad  while this answers the question partially, I still have no idea how to filter layers that exist in the style we have used.(How do I know the layer name ?, the example given pulls layer from other sources or changes the style being used). Also when i mentioned area calculation, i was wondering if we can calculate the area of selected data, in a specific layer (after using the filters ) .

**Comment by nikhilshivpuja** [comment]
my  git repository right now : https://github.com/nikhilshivpuja/mapbox-cartography-assignment-2

**Comment by SuchismitaNaik** [comment]
Initial exploration of Goa tourist maps ( only showing the restaurants/shacks/cafe): 
[Goa Map Trial 1](https://a.tiles.mapbox.com/v4/suchismitanaik.p5d0l6np/page.html?access_token=pk.eyJ1Ijoic3VjaGlzbWl0YW5haWsiLCJhIjoiY2lqMmZ5N2N5MDAwZnVna25hcjE2b2Q1eCJ9.IYx8Zoc0yNPcp7Snd7yW2A#14/15.3726/73.8015)
To be added:
Filters based on Budget, Cuisine type, Collection based

**Comment by jamboks** [comment]
A map of tourist spots in Delhi (Have taken 20 most famous spots for now, will be adding more)-
Repository (with filters) - https://github.com/jamboks/delhi
Mapbox link (without filters) - https://a.tiles.mapbox.com/v4/manupriya.p55eaopl/page.html?access_token=pk.eyJ1IjoibWFudXByaXlhIiwiYSI6ImNpaWZ4YWhpOTAyMWR1M2tyYnVrNmtlZHIifQ.8EMsCq5seNFvkumaadMn0g#15/28.6185/77.2190

**Comment by planemad** [comment]
@nikhilshivpuja the layer names is the same as what you see in the layer panel when you open the style in Studio or the id you are using if adding it via js.

The dynamic area calculation is a little complex. You can only do it for the filtered features visible in the map view or features that you click on.

Make use of https://www.mapbox.com/mapbox-gl-js/api/#Map.featuresAt or featuresIn method to retrieve the geometries of the feature from your map. Once you have a list of features you can iterate through them and see if they match the condition you are looking for. And if they do use, turf.area to calculate the area cumulatively.

**Comment by arshedhakeem** [comment]
Hi Arun,
PFA the folder structure of webpage which has the 'TRIVANDRUM TOURIST MAP' (index.html)
Features in the map:( Exploration 1)
- Geocoder Search Bar
- Toggle between different map views( street,outdoor and satellite)
- button for panning back to trivandrum, with zoom level of 11
- tourist location filters
- transportation filters

[Trivandrum_tourist_map_webpage.zip](https://github.com/mapschool/course/files/131841/Trivandrum_tourist_map_webpage.zip)

**Comment by prajography** [comment]
[sindhudurga tourist map.zip](https://github.com/mapschool/course/files/131877/sindhudurga.tourist.map.zip)

**Comment by planemad** [comment]
**Some maps**
- Railway map of the world http://shvrm.github.io/railway/

**Studio tilesets**
- Railway stations of the world https://www.mapbox.com/studio/tilesets/ramas.4r5v31i6
- Railway tracks https://www.mapbox.com/studio/tilesets/arunasank.railwayTracks

**Comment by planemad** [comment]
Rescoped and tracking on #12
