### ISSUE TITLE
Assignment 2: Streetmap design

### ISSUE THREAD

**Issue by planemad** [mapschool/cartography#12]
**Objective** Custom design a map style in Studio for a selected theme. End output will be a Studio style. Optionally create a custom html+js wrapper for your map to add interactivity.

Add your project ideas like this example, add any other resources where you are taking inspiration from :

> **Thiruvananthapuram Heritage Map**
> Map of the city showing a walking trail across heritage zones of the city.
> Data needed: Location and names of heritage buildings
### Data
- Query data from [Overpass Turbo](http://overpass-turbo.eu) https://www.mapbox.com/help/overpass-turbo/
- Add missing data into [OpenStreetMap](http://osm.org) https://www.mapbox.com/blog/get-on-the-map/
- Query object properties on OSM by using the query tool (? on the right) https://www.openstreetmap.org/way/27618340 ; Use the properties to search on overpass
- Create custom shapes with properties http://geojson.io
### Interactivity
- Add search and directions https://www.mapbox.com/mapbox-gl-js/plugins/
- Find user location through HTML geolocations http://html5demos.com/geo
-  Center map on a clicked marker https://www.mapbox.com/mapbox-gl-js/example/center-on-symbol/
- Show popup on hover https://www.mapbox.com/mapbox-gl-js/example/popup-on-hover/
- Restrict map pan area https://www.mapbox.com/mapbox-gl-js/example/restrict-bounds/
### Design
- Mapbox Gallery https://www.mapbox.com/gallery/

**Comment by nikhilshivpuja** [comment]
The various aspects of Bangalore : 

> Bangalore has many names 
> Garden City
> City of Lakes
> Silicon valley of India
> City of pubs
> etc
> Data for each of these categories

**Comment by yashodha8** [comment]
To design a tourist Map for Chennai.
Historical Places
Spiritual Places
Beaches
Experiential Places
-Filters
-Text on Hover

Data & icons for each categories

**Comment by kunchapu** [comment]
Places to visit in Delhi
-Map of Delhi showing, top places to visit in & around Delhi.  -
-Data Needed: Location of places, nearest transport etc.

**Comment by tinozza** [comment]
The Great Outdoors Map
Map showing all the trekking spots near Bangalore.

Data: Location and Description

Filter by: Difficulty level, Distance from Bangalore, trek length, Best season to visit

Additional data: Trekking Rentals nearby, Other nearby tourist spots

**Comment by aswathyali** [comment]
Places to visit in Wayanad
-top tourist places in wayanad according to their historical, cultural and scenic values

**Comment by arshedhakeem** [comment]
### Medical Tourism in Thiruvananthapuram:
- map showing ayurveda,siddha and yoga centers
- Recuperation centers at five star beach resorts and hill stations 
- major modern medicine hospitals attracting medical tourists 

> Data : Location & details of centers

**Comment by SuchismitaNaik** [comment]
**Restaurants of Goa**

Overview: Map showing all restaurants of goa.
On click: Paths of all the tourist places (churches, beaches etc.) from each restaurant.

Filter by: Hidden Gems, Breakfast Places, Celebrity Spotting Places, Party Places, Romantic Dining, Budget Friendly, Shacks, Authentic Goan Places

Data Needed: Location, names of the restaurants and details of each restaurants

**Comment by tantadang** [comment]
**Fort Cochin Heritage Map**

Data Needed : Location & details of
> Colonial Structures Eg: Cabaral Boatyard
> Religious Centres Eg: Santa Cruz Basilica, Jew Synagogue
> Cultural Centres & Art Cafes

**Comment by tantadang** [comment]
**Fort Cochin Tourist Map**
Data Needed : Location & details of

> Colonial Structures 
> Religious & Cultural Centres 
> Restaurents & Art Cafes

**Comment by prajography** [comment]
**Sindhudurga Tourist Map**

Recreational Spots
- Beaches
- Religious places
- Forts
- Waterfalls
- View Points
- Others

Transportation
- Bus Depots
- Railway Stations

Accommodation
- Hotels
- Resorts
- Farmhouses/House Stays

**Comment by manaskumar7707** [comment]
**Incredible Odisha**
Showing most visited tourist places in Odisha, supported by customised icons.
The map gives a link to trip advisor for hotel search and also shows how to go that particular place from three epicentres( Cuttack, Bhubaneswar, Berhampur )

**Comment by jamboks** [comment]
**Tourism in Delhi**
Looking at tourist spots in Delhi
Segregation of spots based on:
- first time visitor
- returning visitor
- an off-beat traveller
  OR
- religious spots
- historical monuments
- arts and culture
- foodie joints
- old haunts of the city
- contemporary hangouts

Along with info on routes from point A to point B, and modes of transport available for the same.

**Comment by nehaarsid1** [comment]
Overview: Map showing all Must visit places of Hyderabad

Filter by: Hidden pearls, Food,Shopping Streets, Tourist Places, Resorts, Adventure&Fun zones

Data Needed: Locations, names of tourist places,shopping streets and famous food places and their details
