### ISSUE TITLE
Assignment 2 Update: Day 0

### ISSUE THREAD

**Issue by planemad** [mapschool/cartography#13]
For #12 

Post a screenshot and a few lines about what you tried and where you are blocked at the end of each day. This would be an amazing archive of progress :rocket: 

@mapschool/infdpg14

**Comment by tantadang** [comment]
![fort-kochi-tourism-map-v1 0](https://cloud.githubusercontent.com/assets/16536337/13086078/895edea2-d507-11e5-9860-9e32f53727dc.jpg)

### Fort Cochin Tourist Map V1.0

Base Map Chosen : Streets

CHANGELOG
Customized colors of land, water & roads
Added the following data layers using overpass turbo
- Restaurants  Data 
- Cafes Data 
- Ferry Routes Data

**Comment by planemad** [comment]
Nice @tantadang ! Are those the Chinese fishing nets north of Fort Kochi? I remember adding all those ferry routes in OSM many years ago, you should check if they are correct ;)

**Comment by tantadang** [comment]
yes @planemad they are chinese fishing nets..  

Not sure if its the exact path they take but all the routes still exist with govt boat service. :)

**Comment by nikhilshivpuja** [comment]
<img width="950" alt="capture" src="https://cloud.githubusercontent.com/assets/1097779/13105281/7868c24e-d588-11e5-9c16-ecbebcea06d3.PNG">

Basic layers are working , colour need to be changed

**Comment by planemad** [comment]
Thanks @mapschool/infdpg14, lets track todays updates on #14 

You can still post anything from yesterday here as part of your rolling documentation.
