### ISSUE TITLE
NID: Final feedback

### ISSUE THREAD

**Issue by planemad** [mapschool/cartography#17]
@mapschool/infdpg14 awesome work with all the maps: 
- A1. Basic map visualization https://github.com/mapschool/course/issues/6
- E2. Bengaluru Airport connectivity diagram https://github.com/mapschool/course/issues/2 
- A2.Streetmap Design https://github.com/mapschool/course/issues/16 

It would be great to compile a list of your final submissions here for review. Everyone can post a comment with screenshots/Mapbox links to your outputs. I will be posting my feedback on the work here. Grades will be based on the best two of the three outputs.

**Submit by** Friday 5PM, 17th March

![](https://cloud.githubusercontent.com/assets/12103383/12879309/38ba06d6-ce57-11e5-84e8-4bbd377e3b8d.gif)

**Comment by tantadang** [comment]
![1-bial-bus-routes](https://cloud.githubusercontent.com/assets/16536337/13879063/62d0a6a2-ed3b-11e5-91ed-109273923d9a.jpg)
BIAL Airport Shuttle Service Schematic Map

![3-fort-cochin-map](https://cloud.githubusercontent.com/assets/16536337/13879076/769dac7a-ed3b-11e5-928b-ac4c955adbf1.jpg)
[Fort Cochin Tourist Map](https://api.mapbox.com/styles/v1/anishkrishnan/cikp2eb7c00mfcilue03p08gm.html?title=true&access_token=pk.eyJ1IjoiYW5pc2hrcmlzaG5hbiIsImEiOiJjaWhjYncyeDcwMWRydGNsejRubXB5MzRlIn0.A3kdrdduu50RctPTe2-Qow#14.82/9.9629/76.2501)

![2-netas-crore-club](https://cloud.githubusercontent.com/assets/16536337/13879079/7afa22f8-ed3b-11e5-8f88-2555bb999127.jpg)
[Netas in 10&100 crore clubs](https://api.mapbox.com/styles/v1/anishkrishnan/cij3s6hiz000qapkl0qeg6inm.html?title=true&access_token=pk.eyJ1IjoiYW5pc2hrcmlzaG5hbiIsImEiOiJjaWhjYncyeDcwMWRydGNsejRubXB5MzRlIn0.A3kdrdduu50RctPTe2-Qow#4.04/22.191/79.371)

**Comment by kunchapu** [comment]
1.Delhi Tourism, 
2. Airport route Buses
3..Neta's: 
No Crime record on MP's having total assets Less than 10,00,000.
Few Mp's have Assets more than 100 crores and edu less than 10th pass with crime records.
More Post Graduates and less crimes in UP & KL.
More Crimes in MH & Bihar and have more MP's whose Education qual is less than 10th Pass .

This viz compares Mp's having
Education qual : Less than 10th fail , Crime: >0 (Red Circles)
Assets : <10,00,000 (Light Green) and >100,00,00,000 (Dark Green)

[Submission.zip](https://github.com/mapschool/course/files/179743/Submission.zip)

**Comment by prajography** [comment]
1. Vayuvajra Bus Shuttle Service Map
2. Parties ke Crorepati
3. Sindhudurga Tourist Map

[Maps.zip](https://github.com/mapschool/course/files/179949/Maps.zip)

**Comment by arshedhakeem** [comment]
[Criminal Crorepati MPs - major parties](https://api.mapbox.com/styles/v1/arshedhakeem/cij31ja19003hbdm4zthjntwd.html?title=true&access_token=pk.eyJ1IjoiYXJzaGVkaGFrZWVtIiwiYSI6ImNpajB0dDdubTAwN3R1NG00ZnM0czY5dzQifQ.lIw8WcejfKVYW18MZORJ0A#3.86/20.83/85.57)

```
MPs with criminal records and assets more than Rs. 1 Cr
Parties covered in visualization are

Bharatiya Janata Party
Indian National Congress
Shivsena
Telugu Desam Party
Telangana Rashtra Samithi
All India Majlis-E-Ittehadul Muslimeen
YSR Congress Party
Assam United Democratic Front
Janata Dal (United)
Rashtriya Janata Dal
Jammu & Kashmir People's Democratic Party
Jharkhand Mukti Morcha
Communist Party of India (Marxist)
National People's Party
Biju Janata Dal
Shiromani Akali Dal
Pattali Makkal Katchi
All India Anna Dravida Munnetra Kazhagam
Samajwadi Party
All India Trinamool Congress
Nationalist Congress Party
All India N.R. Congress
```

![criminal crorepati mps](https://cloud.githubusercontent.com/assets/16536380/13883153/30d99ba0-ed4e-11e5-9533-fbe489c66720.png)

PFA BMTC Airport bus service & Trivandrum Medical tourism website folder below -
[Arshed Hakeeem_Submission.zip](https://github.com/mapschool/course/files/179952/Arshed.Hakeeem_Submission.zip)

**Comment by planemad** [comment]
@mapschool/infdpg14 Thank you everyone, it was my first such course that relied on online documentation and the results are promising. There was much I learned using such a process, the biggest of which is that documentation allows one to understand progress and a student's understanding very well.

A key area for improvement is to ensure the every course issue ticket is scoped well and gets participation from everyone. Seamless and timely communication and feedback online is essential for the success of this format. Because this is a new approach, not all students seemed very comfortable sharing their in progress work in the public in this way. Also cross student participation on the issues themselves was low, which could have been leveraged upon to troubleshoot issues much quicker.

### Evaluation notes

The grading was done today on the following criteria and submitted to the institute:
- Exploration  &  Improvisation
- Conceptual clarity & comprehension
- Problem Solving & Lateral Thinking
- Originality & Visualization
- Teamwork, Participation and Time Management

Since the grading needed to be done by student, I found a convenient way to view all of a student's course activity is using the [public activity feed](https://github.com/tantadang?tab=activity). Looking at the final outputs of a student its easy to give an overall grade based on the above. A closer look at the details of the interactions and outputs reveal areas that were stood out and that which could be improved upon and the grades for this are adjusted accordingly.

Since the none of the assignments were group based, only those who could help each other out using GitHub were given A+ in group activity. I also went in the order of which student made the earliest comment to give higher grades to more proactive and communicative students.

Reminder for self: make sure everyone adds their name to their profile and check team access during the course. Had to do some web sherlocking to identify @jamboks and @tinozza.

Evaluation is always tricky, but given how everyone's work is available here for each other to see, I believe the grades I have given would serve justice to your efforts. Looking forward to see how everyone takes their learning forward and is able to integrate it in the much larger scope of design. Fantastic work!

![](http://i.giphy.com/fHiz7HAUlSaIg.gif)
