### ISSUE TITLE
Sensory Mapping [NID-2017]

### ISSUE THREAD

**Issue by poornibadrinath** [mapschool/cartography#19]
- **Objective** Explore the fundamentals of mapping abstract information and data visualization
- **Time** 5 hours (1 hour field + 1 hour workshop + 30 min presentation + 2 hours workshop + 30 min presentation)
- **Resources needed** 
  - A route safe to walk around the classroom for field observations
  - 2xA3 sheet for each student
  - 2xA0 chart paper for final output
  - Art supplies: markers, PostIts, scissors and glue

### What is Sensory Mapping? 

<img width="667" alt="screenshot 2017-01-05 16 38 26" src="https://cloud.githubusercontent.com/assets/126868/21678575/6fda9f5e-d365-11e6-9dea-3bc339c75fc5.png"><br>_source: [sensoryjourneys](http://www.sensoryjourneys.net)_
   
Sensory mapping, (a part of [Dèrive](https://en.wikipedia.org/wiki/D%C3%A9rive)), is an interesting concept of [Psychogeography](https://en.wikipedia.org/wiki/Psychogeography) where in an individual tries to understand and map the surroundings purely based on his perception or senses. Different people have different ways of perceiving something, it might be visual, audio, taste, feel, smell etc and sensory mapping helps in how a same thing can be viewed in a completely different way when a series of components come together. 
   
### What you need to do in a Sensory Mapping? 

_How this exercise was carried out_ 

- Take a route of your surroundings
- See what are the things that catch your attention or are particularly standing out. (In a sense, view the surroundings in your own way and try to understand the way you are visualising it)
- Relate where you are to what you see
- Map it
- Complete the route
- See how different the results are when compared to the conventional mapping. 
- Share the results with others and see what they have come up with.

Ref: #18 

cc: @planemad @rasagy

**Comment by planemad** [comment]
### Step 1: Identify a route to map
- List main points of human activity within a 20 minute walk distance of the classroom
- Choose an optimal route that can be covered with a 15 minute walk

![unnamed](https://cloud.githubusercontent.com/assets/126868/21681846/20abf506-d377-11e6-94ba-cebccd95f8f9.jpg)

### Step 2: Assign senses to map
- Assign every student one of the 5 senses to map on the walk. There will be more than one student for each sense
- Students should walk independently and not cover the walk in groups

### Step 3: Share observations for each sense
- After the field observations, 5 groups are formed, one for each sense
- Each group presents a visual narrative of their sensory experience on paper

### Step 4:  Design a visual grammar for each sensory plane
- Each group iterates on the representation with a suitable visual grammar using colors, shapes, iconography and any other visualization techniques
- The route does not have to be geographically accurate

### Step 5: Combine the sensory map into the spatial plane
- All students create a combined map of the 5 senses on a geographically accurate representation

**Comment by planemad** [comment]
@mapschool/infdpg15 lets get all the outputs documented here.

For each group, please include a photo of:
- Raw notes of observation
- 1st iteration of sensory map
- 2nd iteration of sensory map
- Usernames of the group members

**Comment by ananth22by7** [comment]
# Smell
## Ananth Pai, Jerry Joseph Payyapilly, Deepti Garima

### Final
![img_20170106_141719870](https://cloud.githubusercontent.com/assets/9886093/21712575/9210120a-d41b-11e6-99c0-f786500bceb2.jpg)

### Process
![img_20170106_141732947](https://cloud.githubusercontent.com/assets/9886093/21712624/dd35b096-d41b-11e6-8174-d97fdc6e75d4.jpg)
![img_20170106_141739601](https://cloud.githubusercontent.com/assets/9886093/21712725/4c097340-d41c-11e6-8e05-a5fff376ad24.jpg)

**Comment by aritrosaha** [comment]
# Taste
## Aritro Saha, Amrutheshwari V

![img_20170105_212947553](https://cloud.githubusercontent.com/assets/24912249/21712650/facf5346-d41b-11e6-86d3-0a8e8102c7d9.jpg)

![img_20170105_194523052 2](https://cloud.githubusercontent.com/assets/24912249/21712773/91941348-d41c-11e6-9461-fb79f057109e.jpg)

**Comment by abhi191** [comment]
# Sense - Sound
## Group Members - Abhinav, Artika, Priyanka

![3](https://cloud.githubusercontent.com/assets/766175/21712602/b52dfbb2-d41b-11e6-8677-219cbddb77bb.jpg)
![1](https://cloud.githubusercontent.com/assets/766175/21712601/b52d9a50-d41b-11e6-89e1-4b4585e994b3.jpg)
![2](https://cloud.githubusercontent.com/assets/766175/21712600/b52ca794-d41b-11e6-88be-68d6ed8205b3.jpg)

**Comment by krishnakuruva** [comment]
# Eye- See 
## # **Group members** ## - Vipasha Gupta, Divya Haridas, Krishna Prasad K

![spatial view](https://cloud.githubusercontent.com/assets/19968802/21712763/83e56ea4-d41c-11e6-9fb1-2cdb0c5d00c6.jpg)

![img_20170106_141048601](https://cloud.githubusercontent.com/assets/19968802/21712768/8c3a6f64-d41c-11e6-997d-b2190d513e82.jpg)

**Comment by nagavyas** [comment]
Touch- Sensory

**Comment by pratyaksha01** [comment]
# **#**SENSE- TOUCH****

## Pratyaksha, Nagavyas Kanugovi

![img_0130](https://cloud.githubusercontent.com/assets/24951788/21712920/3d52a960-d41d-11e6-8f73-5d3f2cce49db.JPG)
![img_0129](https://cloud.githubusercontent.com/assets/24951788/21712937/4dfc2822-d41d-11e6-8bc3-79add077cbc1.JPG)
![a](https://cloud.githubusercontent.com/assets/24951788/21712961/7a4c89b2-d41d-11e6-9126-02da3b64f6a4.JPG)
