### ISSUE TITLE
Exploration 2: Bengaluru Airport Connectivity Diagram

### ISSUE THREAD

**Issue by planemad** [mapschool/cartography#2]
**Brief:** Create an information graphic to help a foreign traveller decide a convenient route and mode of transport to reach the Airport from the city.

**Evaluation**
- Utility
- Legibility
- Data density

**Data sources**
- [BMTC - Latest routes, schedules and fare for Vayu Vajra services](http://www.mybmtc.com/airportservices)
- Post other resources as you find them

cc @mapschool/infdpg14

**Comment by kunchapu** [comment]
![](http://farm4.static.flickr.com/3275/2511364212_d615d2fa68_o.png)

**Comment by nikhilshivpuja** [comment]
Existing map on the bmtc site
![service map](https://cloud.githubusercontent.com/assets/1097779/12086942/762eb710-b2f4-11e5-9547-a8692fa29993.png)

**Comment by tantadang** [comment]
Map given in the BMTC Brochure. ![bmtc-kial-buses](https://cloud.githubusercontent.com/assets/16536337/12088273/b93bf4a4-b2ff-11e5-9c40-51fde1602d99.jpg)

**Comment by planemad** [comment]
Location of bus stops, bus stations and railway stations: http://overpass-turbo.eu/s/dxl

![screenshot 2016-01-04 16 47 57](https://cloud.githubusercontent.com/assets/126868/12088628/f3c34c14-b302-11e5-9f4c-43dbb53976cc.png)

**Comment by planemad** [comment]
Some of my past schematic maps:
- http://irfca.org/faq/map/Mumbai_suburban_rail_map_large.png
- http://irfca.org/faq/map/Chennai_suburban_rail_map_large.png
- http://www.irfca.org/faq/map/IR_network_schematic_map_large.png
- https://upload.wikimedia.org/wikipedia/commons/9/9b/Chennai_suburban_rail_and_bus_interconnectivity_map.png
- https://upload.wikimedia.org/wikipedia/commons/d/d9/Chennai_schematic_bus_map.png
- https://bitterscotch.files.wordpress.com/2007/08/chennai-schematic.png
- https://upload.wikimedia.org/wikipedia/commons/5/5a/Chennai_Metropolitan_Area_Transit_-_Night_Bus_Routes_Map.png
- https://upload.wikimedia.org/wikipedia/commons/d/d2/Renumbered_National_Highways_map_of_India_%28Schematic%29.jpg

**Comment by prajography** [comment]
First Exploration

![vayu vajra bus shuttle_map redesign r1](https://cloud.githubusercontent.com/assets/16536383/12146532/11f37020-b4ba-11e5-8cd6-cee0edf6dbc7.jpg)

**Comment by arshedhakeem** [comment]
1st Exploration 
![bmtc bus service_arshed](https://cloud.githubusercontent.com/assets/16536380/12146627/a455ca94-b4ba-11e5-88bb-e876c82a436e.jpg)

**Comment by arshedhakeem** [comment]
1st exploration 

![bmtc bus service_arshed-01](https://cloud.githubusercontent.com/assets/16536380/12146732/45bd5032-b4bb-11e5-81d5-230db2035e4b.jpg)

**Comment by tantadang** [comment]
BIAL Buses to Airport V1.0 ![bial-bus-routes](https://cloud.githubusercontent.com/assets/16536337/12146849/037b011e-b4bc-11e5-8fd1-47eacf760096.jpg)

**Comment by planemad** [comment]
Found online
![](https://pbs.twimg.com/media/CYFvNpfUEAAtPyH.png)
https://twitter.com/svaradarajan/status/684950900465471489

**Comment by prajography** [comment]
Hello Arun
Made some modifications to the map. I need some help figuring out the railway and metro routes.

![vayu vajra bus shuttle_map redesign r2_2](https://cloud.githubusercontent.com/assets/16536383/12172071/97960b1a-b574-11e5-8734-fe83bba78cf2.jpg)

**Comment by planemad** [comment]
@prajography the bus routes are starting to look really nice, especially the colors. You should add markers at the stops that you feel are important and also where the subway/railway connects with the bus route. You can then start distorting the rail lines that do not intersect with the bus routes freely.

Also you can choose where to diverge routes, create turns in a way so as to maintain symmetry and order with other elements. Use guides to help align elements neatly and they will look much better to the eye. @tantadang has done this very well https://github.com/mapschool/course/issues/2#issuecomment-169367465
![97960b1a-b574-11e5-8734-fe83bba78cf2_jpg_1_575x1_382_pixels](https://cloud.githubusercontent.com/assets/126868/12177476/5ffe9de8-b592-11e5-98ad-e8cf5686cc72.gif)

**Comment by nehaarsid1** [comment]
Exploration 1 : I tried to show all the bus stops with most frequent routes having thicker lines and first common bus stop of different bus routes being highlighted.
![exploration-1](https://cloud.githubusercontent.com/assets/16579291/12216559/1dc80a56-b70c-11e5-9d7e-39eb32b86172.jpg)

**Comment by planemad** [comment]
Grading done.

**Comment by planemad** [comment]
## Bengaluru Airport announces map contest

> Bengaluru International Airport Ltd (BIAL) has invited artists and architects to participate in a map design contest.
The three best-designed maps, with artist credit, will be printed and made available as takeaways for passengers.
The map must fit to scale, follow city boundaries and highlight key landmarks/locations. The design must be unique, original, and must not be in circulation, exhibited or created for other purposes.
Applicants can submit their design in soft copy with a concept note about the inspiration behind the illustration. The date for submission is October 15.
The top three winners will not just win prizes but also get a chance to showcase their talent to millions of people each day. Interested participants can send in their entry to artprogramme@bialairport.com
https://www.thehindubusinessline.com/news/national/bengaluru-airport-announces-map-contest/article29399183.ece

cc @mapschool/infdpg16 @mapschool/infdpg15 @mapschool/infdpg14
