### ISSUE TITLE
Digital mapping [NID 2017]

### ISSUE THREAD

**Issue by planemad** [mapschool/cartography#20]
- **Objective** Explore the fundamentals of digital mapping and web cartography
- **Time** 5 hours (4.5 hour workshop + 30 min presentation )
- **Resources needed** 
  - Individual laptops and Wifi
  - Signup on [Mapbox](http://www.mapbox.com)

### Brief
Design and publish an interactive sensory map of the walk from #19 

cc @mapschool/infdpg15

**Comment by planemad** [comment]
### Step 1: Understand the fundamentals of web maps
- Map data 
- Map tiles
- Slippy map

Reading: http://mapschool.io

### Step 2: Creating and styling map data
- Overview of the [Mapbox stack](https://www.mapbox.com/developers/) and [Mapbox Studio](https://www.mapbox.com/help/getting-started-mapbox-studio-1/) with [examples](https://textb.org/t/mapbox/)
- [Create a dataset](https://www.mapbox.com/help/getting-started-studio-datasets/) of sensory observations
- Export the data as a tileset
- Add the tileset to [a new basic style](https://www.mapbox.com/help/getting-started-mapbox-studio-2/)
- [Publish your first map](https://www.mapbox.com/help/getting-started-mapbox-studio-3/)

### Step 4: Design a cartographic style
- Create layers for lines, fills, circles and symbols
- Filter data layers by geometries and attributes
- Style visual properties based on attributes and zoom level
- Show text labels for data points
- Change the color, size and icons of  data points by attribute

### Step 5: Create an interactive web map
- Setup a simple [development environment](https://gist.github.com/planemad/716fd648564ca083921a)
- Create a [basic example map](https://www.mapbox.com/mapbox-gl-js/examples/) by copying the html code and creating a .html file using a text editor. Customize the style url and starting position for your map.
- Display a [popup on hovering over the data point](https://www.mapbox.com/mapbox-gl-js/example/popup-on-hover/).

**Comment by rasagy** [comment]
## Creating datasets:

Each group will work on their own sense data with the following fields:

**common**
- source: animals, machines, people, vehicles, daily chores, material
- location: tapri, NID, Platinum gate

**sound**
- intensity: high/medium/low

**taste**
- intensity: high/medium/low
- type: tangy, sweet etc.

**vision**
- color:

**touch**
- safety: safe, unsafe
- feeling: pleasant, unpleasant
- texture: smooth, rough, even
- material: tar, cement, soil
- strain: low, medium, high

**smell**
- feeling: pleasant, unpleasant, neutral
- intensity: 1-5

Once you’re done, share the tileset url on this ticket, like https://www.mapbox.com/studio/tilesets/rasagy.cixlesg5y002a32lpxwjjf82h-3bml2/

**Comment by abhi191** [comment]
**Sounds**

https://www.mapbox.com/studio/tilesets/abhi191.cixlog1qd00442qn0nvzk8r3p-9bkyx/

**Comment by Amruthavijaykabadi** [comment]
**Taste**

https://www.mapbox.com/studio/tilesets/amruthavkabadi.cixlp5lnb001c2qlpqb5dy81e-59t7p/

**Comment by jerryjoseph208** [comment]
**Smell Tileset**

https://www.mapbox.com/studio/tilesets/jerryjoseph208.cixln73x0003y2wpylyzyhf5o-5a71v/

![image](https://cloud.githubusercontent.com/assets/1117531/21718020/87da8b48-d43a-11e6-9266-871261218906.png)

https://api.mapbox.com/styles/v1/jerryjoseph208/cixlo9vlw00132ro0m4jghni5.html?title=true&access_token=pk.eyJ1IjoiamVycnlqb3NlcGgyMDgiLCJhIjoiY2l4bGUwZmdxMDA5eDMzbW9hc3R4Z29qOCJ9.iw9f-lfTh3YcALjzjvX5Ww#18.3/13.034790/77.534232/0

**Comment by divyasreejai** [comment]
**Vision Tileset**
https://www.mapbox.com/studio/tilesets/divyasreejai.cixlr9a0i002x2yrs4mf35g7q-9gkfa/

**Comment by jibs23labs** [comment]
Touch Tileset
https://www.mapbox.com/studio/tilesets/jibs23labs.cixlrcdcq005b2xn1ipuvrpje-41skl/
