### ISSUE TITLE
Assignment 2: Sensory Digital Map

### ISSUE THREAD

**Issue by rasagy** [mapschool/cartography#21]
This ticket is for all discussions, doubts and inspiration for this assignment started in #20.

Feel free to ask questions, share screenshots & links of your progress here.

**Comment by ananth22by7** [comment]
**Smell**
Link to check in on progress any time
https://api.mapbox.com/styles/v1/jerryjoseph208/cixlo9vlw00132ro0m4jghni5.html?title=true&access_token=pk.eyJ1IjoiamVycnlqb3NlcGgyMDgiLCJhIjoiY2l4bGUwZmdxMDA5eDMzbW9hc3R4Z29qOCJ9.iw9f-lfTh3YcALjzjvX5Ww#18.3/13.034790/77.534232/0

**Comment by Vvipasha** [comment]
# Vision

the following was made using the mapbox online editor. However, I wasn't able to get the same result using mapbox studio (since online editor projects will become read only as of 31st Jan). 

Is there a **quick** way to migrate to studio (keeping markers and image files in pop up as it is ) using geojson or kml files.?? 

[<img width="1280" alt="1" src="https://cloud.githubusercontent.com/assets/24951724/21753095/0e542fb8-d60b-11e6-8be0-240481d65f1f.png">](url)

**Comment by planemad** [comment]
@Vvipasha the online editor is no longer maintained and should not be used. Unfortunately there is no way to migrate from this to Studio as they are incompatible technologies.

**Comment by abhi191** [comment]
> Playing with the color schemes and point plots.

![p1](https://cloud.githubusercontent.com/assets/766175/21761790/608a25e2-d67b-11e6-990d-4bdba2cda2ea.png)

![p2](https://cloud.githubusercontent.com/assets/766175/21762115/f601af36-d67c-11e6-9c6c-5069407afd45.png)

**Comment by aritrosaha** [comment]
@planemad Is there a color gradient tool to apply on an area or a line in the mapbox studio?

**Comment by planemad** [comment]
@aritrosaha gradient colors are not yet supported in Studio

**Comment by planemad** [comment]
@mapschool/infdpg15 please share the progress and blockers you are facing so @rasagy and I can help out. We're looking forward to some great walkthroughs.

**Comment by Amruthavijaykabadi** [comment]
## Taste
Aritro Saha, Amrutha
Working on the dimensions: type, source, intensity

![screen shot 2017-01-09 at 8 30 16 pm](https://cloud.githubusercontent.com/assets/24955244/21770820/f24a6f1c-d6aa-11e6-9d37-be80d0fef0de.png)


![screen shot 2017-01-09 at 8 36 00 pm](https://cloud.githubusercontent.com/assets/24955244/21770908/4e3445e6-d6ab-11e6-8bbf-fecdfa5d831d.png)

**Comment by pratyaksha01** [comment]
**I TOUCH TO CONNECT**

Lines representing dimensions- material, surface, sunlight, comfort
WIP- experience, safety

![screenshot 1](https://cloud.githubusercontent.com/assets/24951788/21771006/b92c622a-d6ab-11e6-8c59-c875efb2a8f9.png)

https://api.mapbox.com/styles/v1/pratyaksha/cixq4a0xq00712rphumle7ryu.html?fresh=true&title=true&access_token=pk.eyJ1IjoicHJhdHlha3NoYSIsImEiOiJjaW0wNmhsY3kwOGx1dTlrcjR0ZHJldWduIn0.LeINIf9Dh-dozopC65rcNQ#16.16/13.03659/77.53356

**Comment by planemad** [comment]
@Amruthavijaykabadi looking very interesting. It helpful to write a text legend when planning the style to help you think in terms of how to communicate the visual grammar.

@pratyaksha01 Do share a text legend of what the line styles and color represent

**Comment by jerryjoseph208** [comment]
## Smell

Jerry,Ananth, Deepti

[Github Pages Link](https://jerryjoseph208.github.io/smells-of-peenya/)
<img width="1433" alt="screen shot 2017-01-10 at 4 48 07 pm" src="https://cloud.githubusercontent.com/assets/24951700/21804406/d6b607f2-d754-11e6-9aa7-d604ff3c35bf.png">

**Comment by planemad** [comment]
@jerryjoseph208 @ananth22by7 @diptigarima this is looking great! Think about how you can guide the journey for a user, how does one know where to start?

You can also see how you can bring the positive and negative attributes of the surroundings using subtle colors on the basemap.

**Comment by jerryjoseph208** [comment]
@planemad We are looking into how the user can be navigated through the journey. 

We had already tried to bring the positive and negative attributes of the surroundings through the dotted lines on the path. Do let us know if the same is not working.

Updated the earlier version with legend and intensity details on hover. 

[https://jerryjoseph208.github.io/smells-of-peenya/](https://jerryjoseph208.github.io/smells-of-peenya/)

<img width="1440" alt="screen shot 2017-01-10 at 6 47 04 pm" src="https://cloud.githubusercontent.com/assets/24951700/21807816/8a9afe1a-d766-11e6-86d0-90cc3e07a2ba.png">

**Comment by Vvipasha** [comment]
# Vision

###  Q :  I am unable to upload an image into the popup message. Tried adding the link as a key value pair while styling and then fetching the value via html file and supplying the url in sethtml() as below ->

`  var altT = feature.properties.location;
   var url1 = feature.properties.url;
        popup.setLngLat(feature.geometry.coordinates) 
        .setHTML(feature.properties.source + " <br> <b> <center> <h2>" + feature.properties.location + "<img src = url1>") 
        .addTo(map);`
**ps : while debugging, the console shows fetching the correct url under the variable url1**

[<img width="1280" alt="vision basic 2_png" src="https://cloud.githubusercontent.com/assets/24951724/21813912/b27c404e-d77d-11e6-8941-511b89e53c46.png">](url)

**Comment by Vvipasha** [comment]
# VISION

### Tried experimenting with icons having actual images along with description in the popup. 
[<img width="1280" alt="icon_map style 1_png" src="https://cloud.githubusercontent.com/assets/24951724/21814354/111d0bf0-d77f-11e6-93a5-9d6124b46ad2.png">](url)

**Comment by ananth22by7** [comment]
@planemad - (For the [smell assignment](https://jerryjoseph208.github.io/smells-of-peenya/)) There's an issue when you zoom in/out - the areas with grey dots show only in a certain range of zoom - at least for us. Is it the same for you guys too?

<img width="1440" alt="1" src="https://cloud.githubusercontent.com/assets/9886093/21816745/351e1be0-d787-11e6-9105-af8c2db3e432.png">

----------------------------------------
Also the grey dotted polygon for an area (the area in front of Platinum City Club House) isn't showing up at all, which is strange because all the areas were showing fine before publishing.

<img width="1440" alt="2" src="https://cloud.githubusercontent.com/assets/9886093/21816746/356f5d48-d787-11e6-9442-18605e2237f3.png">

**Comment by aritrosaha** [comment]
# Taste
## Aritro, Amrutheshwari
Hi @planemad  @rasagy ,
We are currently working on the text legend. Meanwhile we introduced icons for different types of TASTES. Along with colors(shades & tints) for the intensity of that type of taste.

https://api.mapbox.com/styles/v1/amruthavkabadi/cixq5c86r007d2rphsc2xeesq.html?fresh=true&title=true&access_token=pk.eyJ1IjoiYW1ydXRoYXZrYWJhZGkiLCJhIjoiY2l1ZXRoZDU3MDBmOTJ0bXplbWkwd2hoayJ9.ufR0k9N9m6oRPNltjubxCg#18.3/13.03566/77.53412/-68.4/60

![1-16](https://cloud.githubusercontent.com/assets/24912249/21818276/2f574140-d78d-11e6-9bc1-c10eccaf95f1.png)

**Comment by planemad** [comment]
@Vvipasha can you share the value for a sample `url1`? The html is correct, its likely that the location to the image is incorrect.

**Comment by planemad** [comment]
@ananth22by7 not seeing any issues with the grey dot patterns, it shows up fine on all zoom levels. 

![new3](https://cloud.githubusercontent.com/assets/126868/21839652/efa9c618-d7fe-11e6-9268-faca2942698f.gif)

Not sure of the missing piece. Everything else shows up fine, what was done differently for that polygon?

**Comment by planemad** [comment]
@aritrosaha @Amruthavijaykabadi looking good.

<img width="171" alt="screenshot 2017-01-11 14 29 42" src="https://cloud.githubusercontent.com/assets/126868/21841926/6a304e74-d80a-11e6-9c62-e18b10b6264d.png">
This type of line styling makes it look like you took three different routes. You can see if different line attributes like widths and blurs can improve the visualization.

**Comment by rasagy** [comment]
Loving the explorations!

Want to share a quick tip: You’ll notice that even though places like NID & Platinum city are mapped in OSM, they don’t show up as labels in your map. That’s because the `poi_label` layer in this map style only filters a small set of points to show. 

You can change this by going to the `poi_label` layer in the style, opening `Select Data` tab, and removing the filters:

![nid-poi-show-all](https://cloud.githubusercontent.com/assets/1117531/21842072/25576930-d80b-11e6-8e4d-6ea19aced71c.gif)

You can always add new layers instead of editing the `poi_label` layer, and design the specific labels for apartments & rest of the PoI to get something like below:

<img width="1031" alt="screenshot 2017-01-11 14 37 49" src="https://cloud.githubusercontent.com/assets/1117531/21842201/afc4b1e0-d80b-11e6-837c-081346ef198e.png">

I’m using the following filters for the two layers:

<img width="1105" alt="screenshot 2017-01-11 14 32 29" src="https://cloud.githubusercontent.com/assets/1117531/21842211/ba0763f0-d80b-11e6-9b43-da1403f88267.png">
<img width="1099" alt="screenshot 2017-01-11 14 32 21" src="https://cloud.githubusercontent.com/assets/1117531/21842210/ba0513de-d80b-11e6-88d5-e27c44f8f5b7.png">

**Comment by rasagy** [comment]
> Also the grey dotted polygon for an area (the area in front of Platinum City Club House) isn't showing up at all, which is strange because all the areas were showing fine before publishing.

@ananth22by7 You might have missed the properties for this part of the road, or might have missed adding this part of the road. Can you cross check in the Dataset Editor once?

@Vvipasha Try catching up with @jerryjoseph208 & @ananth22by7 and get them to host your project on Github pages like they have done. Then we can help out with the error if you’re still getting it, although from the code you pasted, it seems to be because the space (` `) in the code shouldn’t be there:

> popup.setLngLat(feature.geometry.coordinates)` `.setHTML(feature.properties.source +…

**Comment by ananth22by7** [comment]
@planemad @rasagy Yep, the zoom issue is gone for us too. Polygon still missing though. I don't recall doing anything different for that polygon but I'll check once again.

**Comment by planemad** [comment]
@mapschool/infdpg15 please start posting your `final` submissions today. Meanwhile @rasagy and I will outline next actions for the group assignment #22

**Comment by planemad** [comment]
@mapschool/infdpg15 

**Assignment check-in**
- Date: 12 January 
- Time: 2-2:30pm
- **[Google Hangout](https://hangouts.google.com/hangouts/_/mapbox.com/nidthematiccartographycheck-in)**

The check-in is to help groups with feedback and help with any blockers for the final submission today. Please share the code online prior to the hangout to help troubleshoot problems.

**Comment by jibs23labs** [comment]
**Touch - Sensory Experience Mapping**
__________________________________________
Exploration

<img width="1440" alt="screen shot 2017-01-12 at 2 02 48 pm" src="https://cloud.githubusercontent.com/assets/20012246/21882299/db9657a0-d8cf-11e6-937d-7f36caee3413.png">

Version_1a
https://rawgit.com/jibs23labs/Mapbox/56f5c4aab681e29679aa9ca0a40d2f50eb931d55/test.html

Updates - WIP
1. Visuals on hover.
2. Revising material visual pattern.
3. Combining V1 and V1a.
4. Legends on Page.
5. Redefining visual grammer.

**Comment by jerryjoseph208** [comment]
# Smell
## Ananth, Deepti, Jerry

Github Pages Map:
[Smells Of Peenya](https://jerryjoseph208.github.io/smells-of-peenya/)

Code Link:
[https://github.com/jerryjoseph208/smells-of-peenya/blob/master/index.html](https://github.com/jerryjoseph208/smells-of-peenya/blob/master/index.html)

[Style URL](https://api.mapbox.com/styles/v1/jerryjoseph208/cixlo9vlw00132ro0m4jghni5.html?title=true&access_token=pk.eyJ1IjoiamVycnlqb3NlcGgyMDgiLCJhIjoiY2l4bGUwZmdxMDA5eDMzbW9hc3R4Z29qOCJ9.iw9f-lfTh3YcALjzjvX5Ww#17.0/13.034718/77.534528/-12)

![gif-15s](https://cloud.githubusercontent.com/assets/24951700/21882339/01520958-d8d0-11e6-9380-92fd1a9439a0.gif)

**Comment by jibs23labs** [comment]
https://rawgit.com/jibs23labs/Mapbox/56f5c4aab681e29679aa9ca0a40d2f50eb931d55/test.html

**Comment by rasagy** [comment]
@ananth22by7 @jerryjoseph208 Have a look at this example of flying to different locations with scrolling: https://www.mapbox.com/mapbox-gl-js/example/scroll-fly-to/

**Comment by rasagy** [comment]
@Vvipasha Have a look at [this example](https://www.mapbox.com/mapbox-gl-js/example/custom-marker-icons/) if you haven’t already for implementing this idea you shared earlier:

![image](https://cloud.githubusercontent.com/assets/24951724/21814354/111d0bf0-d77f-11e6-93a5-9d6124b46ad2.png)

Try working with your batchmates to debug issues or share your code so we can help out. :)

**Comment by rasagy** [comment]
Here’s an example for creating hover on your elements, however it’s slightly javascript heavy: https://www.mapbox.com/mapbox-gl-js/example/hover-styles/

Also have a look at other examples in the **User Interaction** section, like this example to [restrict panning to an area](https://www.mapbox.com/mapbox-gl-js/example/restrict-bounds/), [filter symbols by toggling buttons](https://www.mapbox.com/mapbox-gl-js/example/filter-markers/) etc.

**Comment by rasagy** [comment]
Here’s how you can get the arrow along a continuous line added in Dataset Editor:

<img width="846" alt="nid-sounds-arrows" src="https://cloud.githubusercontent.com/assets/1117531/21885556/3b28bd08-d8de-11e6-9cdb-36bf2645d725.png">

Or footsteps!

<img width="464" alt="screenshot 2017-01-12 15 53 30" src="https://cloud.githubusercontent.com/assets/1117531/21885806/505f2d5a-d8df-11e6-92cc-06b72193f26d.png">

**Comment by ananth22by7** [comment]
@rasagy Hmm, we had tried that approach with one of the default icons but icons weren't always aligned with the direction of the line, so we didn't proceed. We'll try it again now.

Footsteps is a good idea!

**Comment by rasagy** [comment]
@Amruthavijaykabadi @aritrosaha Here’s one more thing you can play with when you’re making the parallel lines: Change the dashes to go from long to short. See if this approach helps!

<img width="643" alt="screenshot 2017-01-12 16 22 43" src="https://cloud.githubusercontent.com/assets/1117531/21886949/dc18c9ce-d8e3-11e6-8429-0e77d0ce0fa1.png">

**Comment by rasagy** [comment]
Taking the discussion of the Group project to #22.

**Comment by Vvipasha** [comment]
@rasagy 
Hey can you share the code snippet to read a geojson file into a variable in order to access the coordinates for each point on map. TIA

**Comment by rasagy** [comment]
@Vvipasha The [example I shared](https://www.mapbox.com/mapbox-gl-js/example/custom-marker-icons/) does exactly that. Are you getting stuck somewhere? Can you upload your code on github and share some screenshots/errors so we get a better idea?

<details><summary>Here’s roughly what that code does:</summary>

---

Takes the geojson file and saves it in the variable `geojson`:
```
var geojson = {
    "type": "FeatureCollection",
    "features": [
        {
```
Then loops through each of the feature (point-based markers, in this case):
```
// add markers to map
geojson.features.forEach(function(marker) {
```

Then does something (creates a `<div>`) with the properties of each feature:
```
    // create a DOM element for the marker
    var el = document.createElement('div');
    el.className = 'marker';
    el.style.backgroundImage = 'url(https://placekitten.com/g/' + marker.properties.iconSize.join('/') + '/)';
```

Then adds that `<div>` as a marker on the map with the latlong property of the geojson for the marker:
```
    // add marker to map
    new mapboxgl.Marker(el, {offset: [-marker.properties.iconSize[0] / 2, -marker.properties.iconSize[1] / 2]})
        .setLngLat(**marker.geometry.coordinates**)
        .addTo(map);
```
</details>

**Comment by Vvipasha** [comment]
@rasagy i see in the code , the geojson is written in the same html file. Instead, I am trying to access the features.json file stored in the same folder location and then store the value into the variable. So if you could let me know how do i access the feature.json file into my index.html file and storing in the similar way as mentioned above

**Comment by rasagy** [comment]
@Vvipasha Understood. An easier hack would be to open the geojson file and copy paste the json in your own code, like the example does, if the geojson won’t change/doesn’t _need_ to be in a separate file.

If not, then this page explains [different ways to access a geojson file](http://stackoverflow.com/questions/19706046/how-to-read-an-external-local-json-file-in-javascript): By running a local server, or by converting it into a .js file by making a small edit. Hope this works if you want to refer to the file.

**Comment by planemad** [comment]
@Vvipasha like @rasagy mentions you cannot access external JS files without using a server. Its as simple as running the command `python -m SimpleHTTPServer` in your terminal at the folder location, and opening the server address in the browser.

A simple tutorial to get you started with a simple web development environment and share your code on Github: https://gist.github.com/planemad/716fd648564ca083921a

**Comment by Vvipasha** [comment]
@rasagy @planemad  .. Thanks for the suggestion and links.

For the update , made few changes as follows -
1. Made the land use features like parks and buildings a little prominent.
2. Added icons for the objects.
3. Displaying color to highlight the sense of sight as background for the icons
4. Provided the journey route.
5. Displaying pop ups on hover with :
       a object name
       b. location
       c. source
       d. image 

**Next Item actions :**
1. working on having custom marker icons.
2. Looking to incorporate shapes
3. Also looking to incorporate crowd density for different points
         a. large gatherings
         b. small gatherings
         c. very less or no gathering

https://api.mapbox.com/styles/v1/vipasha/cixuqov2r007m2so6jxaq4nji.html?fresh=true&title=true&access_token=pk.eyJ1IjoidmlwYXNoYSIsImEiOiJjaW1memNyNWgwMXVzdmNtNmQyemNqa3o1In0.J2DseJ4fjLUYStQrrV0fKQ#19.12/13.03468/77.53447/-70

[
<img width="1280" alt="vision submission 1_png" src="https://cloud.githubusercontent.com/assets/24951724/21912389/95b1b3a2-d94b-11e6-8d3b-d06877167abf.png">
](url)

Ps : would commit the code today before lunch time.

**Comment by rasagy** [comment]
@Vvipasha Awesome, looking forward to seeing what you finally come up with!

**Comment by planemad** [comment]
@Vvipasha this is great. The route labels are nice, wonder if it could be made more expressive, rather than route numbers which does not tell much about the route.

**Comment by Amruthavijaykabadi** [comment]
## Our Journey Through Taste 
## Aritro, Amrutheshwari


### Our visualisation:
https://amruthavijaykabadi.github.io/taste-journey/

![screen shot 2017-01-14 at 8 25 17 pm](https://cloud.githubusercontent.com/assets/24955244/21955804/359ca60e-da98-11e6-947b-f2ec8001d94b.png)

Code:
https://github.com/Amruthavijaykabadi/taste-journey/blob/master/index.html

### Exploration:
https://api.mapbox.com/styles/v1/amruthavkabadi/cixu61r3v00572so6w7g05xib.html?fresh=true&title=true&access_token=pk.eyJ1IjoiYW1ydXRoYXZrYWJhZGkiLCJhIjoiY2l1ZXRoZDU3MDBmOTJ0bXplbWkwd2hoayJ9.ufR0k9N9m6oRPNltjubxCg#16.2/13.03686/77.53257/-1

![screen shot 2017-01-14 at 8 25 33 pm](https://cloud.githubusercontent.com/assets/24955244/21955838/e7deb762-da98-11e6-8b42-7491899a1535.png)

![screen shot 2017-01-14 at 8 27 41 pm](https://cloud.githubusercontent.com/assets/24955244/21955808/4b509e92-da98-11e6-81de-4f69c8244de7.png)

**Comment by abhi191** [comment]
**Output** - https://abhi191.github.io/NID-Sounds/
**Code** - https://github.com/abhi191/NID-Sounds/blob/master/index.html

**Comment by Vvipasha** [comment]
Output - https://vvipasha.github.io/VisionNID/
Code - https://github.com/Vvipasha/VisionNID/blob/master/index.html
