### ISSUE TITLE
Assignment 3: Map data story

### ISSUE THREAD

**Issue by rasagy** [mapschool/cartography#22]
**Assignment Brief** Design an interactive map based narrative that highlights a widely discussed issue of the city of Bengaluru using primary data collected from the field.

**Deadline**: 20th Jan

Topic | Interested members
----- | ----------------
Politicians vs Amenities | 6
Road utilization & congestion | 9
Women safety + Liquor | 8
School & Amenities (Public vs Private) | 7

**Comment by rasagy** [comment]
@mapschool/infdpg15 

**Group Project discussion**
- Date: 12 January 
- Time: 5-5:30 PM
- **[Google Hangout](https://hangouts.google.com/hangouts/_/mapbox.com/nidthematiccartographycheck-in)**

**Comment by planemad** [comment]
@mapschool/infdpg15 per discussion:
- Form 3 groups for the narrative cartography assignment of 4-6 members each
- Pick one of the suggested story topic or your own
- Each group post a project plan for their story that includes:
  - Story title and abstract with hypothesis
  - Data required for the story
  - Field data collection strategy
  - Group members

Submit the project outlines by 1pm Jan 12th for feedback.

**Comment by jibs23labs** [comment]
Hello @planemad @rasagy 
Was thinking on mapping the road signs of particular scoped area and finding out **how effective are our Road signs** for user, without digital intervention of navigational apps.

Analysis on:
1. Cluttering of road signs.
2. Effectiveness of road signs.
3. Correctness/contradiction if any.

Any suggestion you would like to share if it could be taken up/revised/roadblock/validity etc?


e.g of road signs in scope etc.
___________________________________________________________________________________________________
![mandatorysign](https://cloud.githubusercontent.com/assets/20012246/21890039/caa4e156-d8f1-11e6-955f-77d754399883.gif)

**Comment by abhi191** [comment]
**Road utilization & congestion** - Jerry, Ananth, Abhinav, Naga, Pratyaksha
**Women safety + Liquor** - KP, Aritro, Vipasha, Artika, Priyanka
**School & Amenities (Public vs Private)** - Divya, Deepti, Amrutha
**Undecided** - Jibin

**Comment by planemad** [comment]
@jibs23labs road signs are rather rare on the city, so the data collection itself would be quite sparse to do any reasonable analysis. One possible angle could be recording data of traffic violations at certain busy stretches to monitor the effectiveness of traffic regulation. The data collection would have to be done at different times of the days and in areas with/without a policeman to bring out an interesting analysis. Or you could tie this as an additional data layer for the road congestion theme.

**Comment by jibs23labs** [comment]
@planemad Thanks Arun, understood. Will look into it with Road Congestion team plans.

**Comment by rasagy** [comment]
@mapschool/infdpg15 Can the three groups post the outlines for their projects here?

**Comment by divyasreejai** [comment]
**Environmental Safety around the schools ( Government Vs Private)** - Dipti, Amrutha, Divya

**Dimensions of data collection -** 
Ground, 
Signboards,
Greenery around the schools,
**Type of Locality –** 
Residential,
Industrial
**Commute –**
School Buses,
Public Transport,
Road Crossing

**Comment by rasagy** [comment]
@mapschool/infdpg15 Can the other two groups also share their project plan? Try and include the following as @planemad mentioned:

> Each group post a project plan for their story that includes:
>  - Story title and abstract with hypothesis
>  - Data required for the story
>  - Field data collection strategy
>  - Group members

As discussed last week, use today (Monday) for finding more information about the topic, data to be collected and a run a trial field survey to see how your data collection will pan out. Keep updating your progress (interesting papers & secondary research, reflections from the data collection etc.) here on Github.

Let’s catch up tomorrow afternoon (**Tue, 17 Jan, 2PM**) for discussing where you are.
- Date: 17 January 
- Time: 2-2:30 PM
- **[Google Hangout](https://hangouts.google.com/hangouts/_/mapbox.com/nidthematiccartographycheck-in)**

**Comment by ananth22by7** [comment]
# Traffic Congestion in Bangalore

## Data required for the story
- **Signal duration** _(duration of red and green signals)_
- **Time taken by traffic to clear during green signal** _(if traffic is significantly cleared and green signal is still on, or if traffic is overflowing to next signal)_
- **Road condition, maintenance work** _(scale of 0 to 5 for road quality, and also qualitative observations such as dug up road, broken roads, large potholes, etc.)_
- **Accumulation of buses or heavy vehicles** _(identify and investigate possibility of outstation bus stop, truck stop, or any other reason for accumulation)_
- **Road encroachments** _(mark encroachments on map)_
- **Pedestrian activity** - people walking on roads, people crossing roads, number of people, general direction of crowd _(mark large crowds on map)_
- **Nature of traffic** - buses, trucks, small cars, large cars, autos, 2 wheelers, etc
- **On-street parking** _(mark excessive on-street parking on map)_
- **Bus-stop location and pedestrian density around stop** _(mark locations on map)_
- **Speak to people around junction to identify origin of traffic, personal inputs, anecdotes, or reactions**
- **Lane discipline**
- **2-wheeler behaviour** - footpath riding, cutting lanes, not waiting for signal, not stopping when signal changes
- **Stormwater drains for water logging** _(mark locations on map)_
- **Footpath presence, quality, and width** - also whether pedestrians are using them _(mark irregularities in footpaths)_
- **Traffic police presence and effectiveness** - officers, vehicles, station _(mark locations on map)_
- **Vehicle breakdown or accident** _(mark locations on map)_

## Field Data Collection strategy
- We plan to visit each chokepoint multiple times in a day _(three times - once early in the morning, before the traffic starts, and other two during rush hour)_
- We will note down the time of recording along with our observations
- We are considering the use of Mapillary, Google My Maps, Map Marker,  to mark our photos with location on map. @planemad @rasagy any other suggestions for apps or techniques would be appreciated.

## Group members
- The group consists of Ananth, Jerry, Jibin, Nagavyas, Pratyaksha, and Abhinav
- **Silk Board Junction** - Jerry, Ananth
- **Marathalli Bridge** - Pratyaksha, Jibin
- **KR Puram, Tin Factory** - Nagavyas, Abhinav

**Comment by krishnakuruva** [comment]
**Title - LIQUOR SHOPS- WOMEN AND OVERALL FRIENDLINESS**

**Data for the story-**

- **Category of Liquor Stores**- Bar/ Malls/Mini Liqour outlets 
- **Locality or surrounding areas** 
- **Availability of Public transport**
- **Police Patrolling** 
- **People's Behaviour** (Checking and observing the people's behaviour at the outlets)
- **Security Guards** (Avalability, activeness, alertness)
- **Proper Lightings around the surroundings**
- **Untidy and stinky smell and cleanliness factors**
- **Men groups or drunkards groups surrounding the outlet**
- **Dark and Shady places around the outlets**
- **Salesmen Behaviour**
- **No survellience**
- **CC Cameras**
- **Quarrels and fights around the stores**
- **Ambiance inside the outlets**
- **Eve teasings and molestations**
- **Spaces and cultural changes** 
- **Cultural and social behavior of this class of people**

**Data collection Strategy -** 

- We plan to visit Residential areas, Highways, Party hubs, Market places.
- We will note down the time of recording along with our observations and questionnaire.
- Casual interviews with the Outlet owners and workers/ Women
- We are considering the use of Google My Maps, Map Marker, to mark our photos with location on map.

**Team members-** 

Vipasha
Aritro
Artika 
Priyanka
Krishna Prasad

**Comment by rasagy** [comment]
Here’s the link to http://fieldpapers.org/ that we talked about today.

**Comment by planemad** [comment]
@mapschool/infdpg15 Deliverables today: Post a project plan backed by the data from your trial surveys. Having the data in a format like a spreadsheet with map locations is ideal, but feel free to be creative with how you want to communicate your findings.

**Comment by divyasreejai** [comment]
## Environmental Safety around the schools (Government vs. Public) - Dipti, Amrutha, Divya

**Hypothesis -** Prime localities suitable for schooling are compromised for other amenities thereby disrupting the safety around the schools.

**The excel shows the data of the visited schools and observations -** 
[school_data.xlsx](https://github.com/mapschool/course/files/719400/school_data.xlsx)

**Work in progress** – Plotted the schools visited around Malleshwaram, Jalahalli and Dasarhalli.
schools in residential areas - plotted in blue
schools in commercial areas - plotted in pink

https://api.mapbox.com/styles/v1/dgarima/ciy5oed02004a2sof448h6mb6.html?fresh=true&title=true&access_token=pk.eyJ1IjoiZGdhcmltYSIsImEiOiJjaW1leXc0eXIwMTN3djJtNjExemY1c28yIn0.t18VMgaCwKULETq7W6twOg#13.73/13.0338/-282.4788


**Implementation Plan -** 
Zoom out:
    1.	  Schools with good surrounding
    2.	  Schools  with bad surrounding 
(Good and bad are defined by score derived from the observations.)
    3.   Both these schools will be plotted under the categories ‘commercial and residential’. 
Zoom in:
    1.   Areas highlighting other amenities within the surrounding of the schools like Malls, Industries, etc.
    2.	  On Demand, detailed information of the observations done for each school.

**Comment by jibs23labs** [comment]
# Traffic Congestion in Bangalore Group

Area: **Marathalli Bridge Traffic Congestion:**
_Jibin and Pratyaksha_

https://api.mapbox.com/styles/v1/jibs23labs/cj0iw57ws00gk2rn4ueixxqjk.html?title=true&access_token=pk.eyJ1IjoiamliczIzbGFicyIsImEiOiJjaXN2OGpwNW8wMDF2MnBxcHJtODVrNHkyIn0.b9NzuPtFN3sfPwHArEMozA#0.0/0.000000/0.000000/0

<img width="1116" alt="screen shot 2017-03-21 at 7 24 44 am" src="https://cloud.githubusercontent.com/assets/20012246/24129463/e068c722-0e08-11e7-9842-96844161acba.png">

Work In Progress
<img width="1440" alt="screen shot 2017-03-21 at 7 36 36 am" src="https://cloud.githubusercontent.com/assets/20012246/24129516/2637e24c-0e09-11e7-9653-bb19338d4e3f.png">
