### ISSUE TITLE
Introduction: Self Cartography – I

### ISSUE THREAD

**Issue by rasagy** [mapschool/cartography#24]
Let’s kickstart this Digital Cartography module with a short exploration on how we visually encode data. We’ll use this beautiful project by Giorgia Lupi: [Drawing your own selfie](https://ideas.ted.com/how-to-draw-your-own-selfie-using-your-personal-data/)

Let’s create our own data-selfie and post here in comments. Let’s make this digitally on a 800x800px canvas. Feel free to use an image-editing tool of your choice (Photoshop, Illustrator, Sketch etc.).

**Comment by rasagy** [comment]
Here’s mine:

![data selfie - rasagy](https://user-images.githubusercontent.com/1117531/34372210-32a80a7a-eaf9-11e7-99b4-d1612a8095b0.png)

(Rasagy Sharma)

**Comment by holy-devil** [comment]
Rajshree:
<img width="800" alt="selfieartboard 1 2x" src="https://user-images.githubusercontent.com/4013612/34372177-02a043d8-eaf9-11e7-95d9-b01eb916db29.png">

**Comment by vinodxyz** [comment]
![vinod s selfie 2](https://user-images.githubusercontent.com/15855154/34372404-64bbf30e-eafa-11e7-91c4-ac7d7e7003fb.png)


(Vinod Kumar)

**Comment by aromalram** [comment]
![aromal_data selfie](https://user-images.githubusercontent.com/22998147/34372289-adacf712-eaf9-11e7-885a-6a6023794a91.png)

**Comment by DyoNDyyo** [comment]
![selfie](https://user-images.githubusercontent.com/34878262/34372214-399e9b82-eaf9-11e7-9cf1-34041800c962.jpg)

**Comment by DyoNDyyo** [comment]
![selfie](https://user-images.githubusercontent.com/34878262/34372262-7748b2e2-eaf9-11e7-9e74-8a10fdfec752.png)



Jayant

**Comment by BarshaP14** [comment]
![barsha](https://user-images.githubusercontent.com/25925845/34372295-b571bc8a-eaf9-11e7-8368-1580def263c0.png)
-Barsha

**Comment by niranjan41** [comment]
![selfie-01](https://user-images.githubusercontent.com/11681600/34372415-7d521902-eafa-11e7-9a6d-e8ccda240f76.png)

**Comment by rasagy** [comment]
Awesome work everyone! Let’s close this for now. If other classmates who’re on leave want to share their data-selfies, they can comment here — we can eventually make a poster for the whole class. 🎉

**Comment by DarthElevator** [comment]
![data-selfie-nikhil](https://user-images.githubusercontent.com/34890610/34384629-5e8fe6ea-eb43-11e7-9dbd-2191b9841be1.jpg)

Hey, I am Nikhil and i am from the Info D 2017 batch. This is my data selfie. This was a fun exercise :)
