### ISSUE TITLE
Self Cartography – II: Designing our own visual encoding framework

### ISSUE THREAD

**Issue by rasagy** [mapschool/cartography#25]
With #24 done, let’s try and take a stab at designing our own framework!

We will —
1. Narrow down on questions that we want to ask
2. Think of possible answers for each question
3. Break into two groups and come up with two frameworks
4. Pair up and make the selfie for each other using the two frameworks

For reference, feel free to look at possible visual encoding options from [Noah Illinsky’s post](http://complexdiagrams.com/properties):

![image](https://user-images.githubusercontent.com/1117531/34373002-9ab70dbe-eafe-11e7-83fc-001ca317b0b5.png)

**Comment by rasagy** [comment]
### Here are our questions:

1. **What kind of furniture do you prefer?** Wood / Metal
2. **Which part of India were you born in?** North/South/West/East/Central
3. **How many tourism spots would you recommend to visit in your hometown?** (Count)
4. **What kind of vacation do you prefer?** Calm/Happening
5. **How far do you like to travel?** Nearby/In the city/In the country/Abroad/Intergalactic
6. **What do you like to drink the most?** Tea / Coffee / Milk / Juice / Alcohol / Soda
7. **How many cities have you been to?** (Count)
8. **How are you doing?** Happy/Sad/Relaxed/Angry/Meh
9. **What music genre to do you listen to the most?** Rock & Metal / Pop / EDM / Jazz / Hip Hop & Rap / I prefer silence
10. **What runs your laptop?** Mac/Windows/Linux

**Comment by niranjan41** [comment]
## Group 1
Order of questions : 

1. How are you doing? Happy/Sad/Relaxed/Angry/Meh
2. From where do you belong? (City/Region) — Which part of India were you born in? North/South/West/East/Central
3. How many tourism spots would you recommend to visit in your hometown? (Count)
4. How many cities have you been to?
5. What music genre to do you listen to the most? Rock & Metal / Pop / EDM / Jazz / Hip Hop & Rap / I prefer silence
6. What runs your laptop? Mac/Windows/Linux
7. What do you like to drink the most? Tea / Coffee / Milk / Juice / Alcohol / Soda
8. What kind of furniture do you prefer? Wood / Metal
9. What kind of vacation do you prefer? Calm/Happening
10. How far do you like to travel? Nearby/In the city/In the country/Abroad/Intergalactic

**Comment by DyoNDyyo** [comment]
## Group 2

1. How are you doing? Happy/Sad/Relaxed/Angry/Meh
2. From where do you belong? (City/Region) — Which part of India were you born in? North/South/West/East/Central
3. How many tourism spots would you recommend to visit in your hometown? (Count)
4. What kind of furniture do you prefer? Wood / Metal
5. What runs your laptop? Mac/Windows/Linux
6. What do you like to drink the most? Tea / Coffee / Milk / Juice / Alcohol / Soda
7. What music genre to do you listen to the most? Rock & Metal / Pop / EDM / Jazz / Hip Hop & Rap / I prefer silence
8. How many cities have you been to?
9. What kind of vacation do you prefer? Calm/Happening
10. How far do you like to travel? Nearby/In the city/In the country/Abroad/Intergalactic

**Comment by rasagy** [comment]
Some of the projects that we looked at today:

- [Onformative’s Facebook Tree](http://onformative.com/work/4010-facebook-tree)
- [Stefanie Posavec’s Writing without words](http://www.stefanieposavec.com/writing-without-words/)
- [Generative Identity of Leeds College of Music](https://www.designweek.co.uk/issues/july-2013/leeds-college-of-musics-soundwave-identity-can-be-personalised/)
- [Generative Identity of Nordkyn](http://www.neue.no/nordkyn/)
- [Meshu — Jewelry from location data](https://meshu.io/)
- [MIT Media Lab’s old, generative identity](https://www.underconsideration.com/brandnew/archives/mit_media_lab_full_of_squares.php)
- [A typeface out of satellite imagery](http://benedikt-gross.de/log/2016/03/the-aerial-bold-project/)

(More project references are in my talk slides on [Using Data for Art](https://speakerdeck.com/rasagy/using-data-for-art))

**Comment by aromalram** [comment]
### Spirit Animal

These are the encodings for the answers of the various questions. These representations form the representation of your spirit animal.

![custom data selfie_1](https://user-images.githubusercontent.com/22998147/34377316-7f399288-eb16-11e7-8cd2-97478da1f1f4.jpg)

**Comment by vinodxyz** [comment]
## **My Planet**
Encodings followed by Group-1.
The idea is to represent our answers using a planet/celestial body.

![guide](https://user-images.githubusercontent.com/15855154/34379647-59d05642-eb22-11e7-831d-bcefddc2564e.png)

**Comment by vinodxyz** [comment]
Vinod's Data-selfie (Planet encoding framework)

![selife](https://user-images.githubusercontent.com/15855154/34383372-c9ecf774-eb3a-11e7-825c-ddfffcde49b3.png)

**Comment by vinodxyz** [comment]
Aromal's Data-selfie (Planet encoding framework)

![aromal s selfie](https://user-images.githubusercontent.com/15855154/34383860-620c9db8-eb3e-11e7-833b-f388ab087cf1.png)

**Comment by aromalram** [comment]
Vinod's Data Selfie (Spirit Animal)

![aromal_custom data selfie_vinod_custom selfie](https://user-images.githubusercontent.com/22998147/34384446-3ea15c0c-eb42-11e7-9f6c-f8642c6ece24.png)

**Comment by holy-devil** [comment]
Rajshree's Data selfie:

<img width="801" alt="selfieartboard 2 2x" src="https://user-images.githubusercontent.com/4013612/34384502-7ee883c6-eb42-11e7-8118-e52b0e565561.png">

**Comment by holy-devil** [comment]
Jayant's Data selfie:

<img width="801" alt="selfieartboard 2 copy 2x" src="https://user-images.githubusercontent.com/4013612/34384519-97d9b17a-eb42-11e7-8354-1497b06d7c43.png">

**Comment by aromalram** [comment]
Aromal's Data Selfie (Spirit Animal)

![aromal_custom data selfie_aromal_custom selfie](https://user-images.githubusercontent.com/22998147/34384521-a1114370-eb42-11e7-8344-b723058140b8.png)

**Comment by vinodxyz** [comment]
Jasleen's Data-selfie (My planet)

![jasleen s selfie](https://user-images.githubusercontent.com/15855154/34400165-a4d35b8e-ebb4-11e7-9ac3-9aa171613ece.png)

**Comment by BarshaP14** [comment]
Barsha's Data Selfie (Spirit Animal)

<img width="800" alt="barsha1" src="https://user-images.githubusercontent.com/25925845/34400494-f4cb7c40-ebb7-11e7-9430-f5e04ea4058f.png">

**Comment by BarshaP14** [comment]
Niranjan's Data Selfie (Spirit Animal)
<img width="800" alt="niranjan 1" src="https://user-images.githubusercontent.com/25925845/34400497-fa1623a8-ebb7-11e7-965c-74810d0c858d.png">

**Comment by rasagy** [comment]
Great, thanks for posting the explorations! Let’s close this once we have everyone’s work shared here.

**Comment by rasagy** [comment]
Going ahead and closing this — it was great to see two different styles emerge out from our discussions. If anyone who missed out wants to share their exploration, feel free to continue adding on as a comment.
