### ISSUE TITLE
Map abstraction - I

### ISSUE THREAD

**Issue by planemad** [mapschool/cartography#26]
Lets abstract the physical world by representing our surroundings in a visually interesting form.

Total time: 1.5hrs

**Data collection** 20 mins

- Sketch out the most detailed floor plan of the building on paper from memory. 
- Explore the floor on foot and add more details. Use a different color. 

**Data selection** 20 mins

- Highlight the 5 most interesting features from the observations.
- Discuss 🗣  What is the common features in everyones observations? Is there a shared understanding of the space? 

**Abstraction** 50 mins

- Create a abstract representation of the data, employ visual metaphors for the overall shape, and use appropriate visual encoding https://github.com/mapschool/course/issues/25 to represent repeated elements.

### Reading

- https://2012books.lardbucket.org/books/geographic-information-system-basics/s06-03-map-abstraction.html

cc @mapschool/infdpg16 @rasagy

**Comment by vinodxyz** [comment]
**Data collection and selection**
Things that I wanted to highlight on the floor-plan:
Lift, stairs, water source, student activities & doors

![floor-plan](https://user-images.githubusercontent.com/15855154/34406313-3ffd7e0e-ebde-11e7-94a4-a2ca51c3ae9e.png)

**Abstraction**

![top-floor---nid](https://user-images.githubusercontent.com/15855154/34406753-aa768774-ebe0-11e7-9d2f-e11a0d64bd2d.png)

**Comment by BarshaP14** [comment]
Map Sketch
![barsha_exp1](https://user-images.githubusercontent.com/25925845/34406596-edac1c76-ebdf-11e7-85e9-8bf8f7457415.jpg)

Digital Abstraction
<img width="866" alt="nid_map_barsha1" src="https://user-images.githubusercontent.com/25925845/34406608-08b955a6-ebe0-11e7-8181-2697a309eee7.png">

**Comment by aromalram** [comment]
**Initial Sketch**

![map_1](https://user-images.githubusercontent.com/22998147/34406666-546a90fa-ebe0-11e7-9f28-c74e36c45337.jpg)

**Abstracted Version of the Sketch**

![map_2](https://user-images.githubusercontent.com/22998147/34406700-7dd29e1a-ebe0-11e7-9f37-b4beb5cf989d.jpg)


**Digital Iteration**

![aromal_nid_abstracted map-03](https://user-images.githubusercontent.com/22998147/34406723-8cf68afa-ebe0-11e7-9e76-4df9bc35507c.jpg)

**Comment by DyoNDyyo** [comment]
![2](https://user-images.githubusercontent.com/34878262/34406761-addd9c86-ebe0-11e7-84bf-5e33bd4cbb40.jpg)
![1](https://user-images.githubusercontent.com/34878262/34406758-ad9df6e4-ebe0-11e7-8a54-5bb703f12cd8.jpg)
![nid 3rd floor](https://user-images.githubusercontent.com/34878262/34406762-ae1bd898-ebe0-11e7-8005-7d8ac73d0690.jpg)

A treasure hunt map

**Comment by pkd2512** [comment]
## First Draft
The idea was to roughly sketch the top floor plan from memory. Well, it served me quite right as I could get the basic spaces appropriately mapped on paper. Upon taking a tour of the space, some more details were added as deemed fit.

![new doc 2017-12-28 2 _1](https://user-images.githubusercontent.com/7580745/34406824-01e42a5c-ebe1-11e7-855f-7ed33572b527.jpg)


## Abstracting the key elements and spaces

![new doc 2017-12-28 2 _2](https://user-images.githubusercontent.com/7580745/34406829-07a6805c-ebe1-11e7-8b58-7107cffc5e6c.jpg)


## Digital map of the floor, showing the spaces, entry and exit points and some key elements

![infod-floormap-01](https://user-images.githubusercontent.com/7580745/34406777-c6993fa0-ebe0-11e7-823f-c3039a25831c.png)

**Comment by Tumb13weed** [comment]
**It all begins with a pencil**
The first draft on pen and paper tried to capture the space with some detail.
![img_20171228_150523](https://user-images.githubusercontent.com/30653549/34407184-0a1317e0-ebe3-11e7-9756-4236a1eeca8a.jpg)

**Abstraction**
Reductions were made from the detail map till only the essentials remained. The outer shape was morphed and simplified as well. 
![img_20171228_150537](https://user-images.githubusercontent.com/30653549/34407226-45086170-ebe3-11e7-9e43-5572a7037952.jpg)


**Going digital**
Moving to Illustrator, further abstractions were made in terms of shape, simplifying several curved and using colours for details. Muted colours denoted areas, while bright icons denoted areas or objects of importance such as lifts and fire extinguishers. The typeface of choice is Segoe UI, with increased tracking, using weights as heirarchy.


![ex 1 - 3rd floor plan - abstract draft i](https://user-images.githubusercontent.com/30653549/34407263-79d1dd1e-ebe3-11e7-9461-c468924d971b.png)

**Comment by jasleen20** [comment]
**Initial Sketch**
![new doc 2017-12-28_1](https://user-images.githubusercontent.com/30645312/34410496-d0ab79ac-ebf6-11e7-9bb1-34e914dc5f97.jpg)

**Abstracted** 
![new doc 2017-12-28_2](https://user-images.githubusercontent.com/30645312/34410454-7b04e132-ebf6-11e7-97df-3a1b95598481.jpg)

**Digital Draft**
![floor plan i1-01](https://user-images.githubusercontent.com/30645312/34410529-08d7b70a-ebf7-11e7-8b29-72312aa5c180.jpg)

**Draft 2**
Map showing the Emergecy exits, Fire extinguishers and Toilets
![floor plan-02](https://user-images.githubusercontent.com/30645312/34411038-2e030036-ebfa-11e7-85c5-4b48edda383a.jpg)

**Comment by planemad** [comment]
Excellent work @mapschool/infdpg16 

For reference, this is what the campus looked like in 2010 ⏳ 
![campus map](https://user-images.githubusercontent.com/126868/34412810-74e8c494-ec05-11e7-9878-1afcbf8ba4f3.png)

**Comment by rasagy** [comment]
Going ahead and closing this, you can follow the next schematic map design exploration on #27.

**Comment by niranjan41** [comment]
![map abstraction 2-03](https://user-images.githubusercontent.com/11681600/39473050-8c2dc4d0-4d6a-11e8-94ab-e1f06ff8bca3.png)
