### ISSUE TITLE
Map abstraction - II

### ISSUE THREAD

**Issue by planemad** [mapschool/cartography#27]
Lets apply the techniques of map abstraction https://github.com/mapschool/course/issues/26 to a more larger geographical area.

**Theme**: A tourist map of your favorite place
 Time: 24 hours

Focus on:
- Main transportation centres
- Points of tourist interest or landmarks
- Interesting or popular neighborhoods
- Popular routes for navigation
- Emergency information

## Examples
- [Schematic tourist maps](https://nidblore.wordpress.com/2013/08/12/geovisualization-workshop-2013/)

cc @mapschool/infdpg16

**Comment by vinodxyz** [comment]
A W.I.P version of Mangalore - Tourist map

![mangalore-schematic-map-v1](https://user-images.githubusercontent.com/15855154/34430975-850a80de-ec90-11e7-9fa2-28d16a31fc0c.png)

**Comment by aromalram** [comment]
Tourist map of Kannur (Kerala) (after incorporating the comments)

Changes Added

- Added concentric circles to indicate the approximate time taken to reach the destination by car.
- Added a few illustrative icons for the major attractions for it to stand out. Tried giving illustrative icons for everything, but seemed like it was getting congested.

Also I had uploaded the previous version on wikipedia. But they deleted for potential copyright violations. I have told them but awaiting its stance to be changed.


<img width="1168" alt="kannur tourist map_after correction" src="https://user-images.githubusercontent.com/22998147/35164957-7f59e9b6-fd72-11e7-93b4-0dcdcd51121a.png">




### Previous Versions

<img width="1168" alt="kannur tourist map-03" src="https://user-images.githubusercontent.com/22998147/34642355-87aa1cac-f337-11e7-9fea-21eb5eae5d67.png">

<img width="1179" alt="kannur tourist map pre 2" src="https://user-images.githubusercontent.com/22998147/34648794-258523b0-f3c7-11e7-8ab8-b627bb92dd04.png">

**Comment by holy-devil** [comment]
W.I.P version of Nagpur - Tourist map
<img width="759" alt="schematic_mapartboard 3 2x" src="https://user-images.githubusercontent.com/4013612/34431349-698c0824-ec94-11e7-84ab-08d14ce604e9.png">

**Comment by BarshaP14** [comment]
Hi Planemad,
While abstracting map, found bird like structure and this is the outcome, please give your feedback.

![bbsr_updated](https://user-images.githubusercontent.com/25925845/34851723-59045ba6-f751-11e7-8d43-7193caa0472a.png)

Earlier Versions
Exploration 2
<img width="1249" alt="simplified" src="https://user-images.githubusercontent.com/25925845/34469791-debc4320-ef4b-11e7-95fe-7c289cec6b0b.png">

Exploration 1
<img width="1249" alt="bbsr_map" src="https://user-images.githubusercontent.com/25925845/34467269-22058518-ef12-11e7-8b21-332b27ff884f.png">

**Comment by planemad** [comment]
@BarshaP14 
- The city area in grey is useful context, nice!
- All the geometries need heavy abstraction. Currently it is just vectorized from Gmaps
- For hospitals, just the main one which is centrally located should be enough
- It is unclear how to reach any of the places, do have all points attached to some part of the transport network
- Since your focus is on a city area, you could highlight a nice walking route that would take one to most places
- Include main transport points like airport, railway and bus station

**Comment by holy-devil** [comment]
Hi @planemad, Rajshree here. Following is my W.I.P schematic map for Nagpur city.
Few Points:
- Orange lines are National and Asian Highways, Yellow are state highways and white are major roads connecting city
- Dotted lines are to show roads in that direction leading to other tourist spots
- I have struggled with selecting how much data to put and how much to abstract. For Example, for getting exact circular ring road, i connected few joins into one single join ( this might confuse while actual navigation and lead to taking wrong turn ). Similar conflicts while abstracting inner city roads.
- Yet to add few labels, more connecting roads, and destination icons. Also thinking to add time for travel since distances are a bit skewed.

<img width="759" alt="schematic_mapartboard 3 copy 2 2x" src="https://user-images.githubusercontent.com/4013612/34442825-cb991d08-ecea-11e7-9517-36a6fe872a21.png">

**Comment by planemad** [comment]
• This is looking a lot more appealing and has a more uniform density of
information, nice!
• You can my minimise the use of color to show different road types by
using varying widths instead. This could be more intuitive to understand
also. Don’t forget to label the main roads to help in orientation.
• This map is for orientation and not for navigation. Feel free to merge
junctions that are close.
• Dotted lines for road give a feeling that they are broken. Try a
different method to indicate a break in scale.
• Add extra roads only if relevant for a tourist or to reach a destination.
• Make use of more icons to reduce dependence on text. E.g. airport symbol
would be self explanatory.

**Comment by vinodxyz** [comment]
Hi @planemad, all,

EDIT: I've updated the tourist-map of Mangalore, based on Arun's feedback. Thanks a lot.

![mangalore-tourist-map-v3](https://user-images.githubusercontent.com/15855154/34711293-de00828a-f544-11e7-9146-120285acb2a1.png)

I've also uploaded this version of the map to [Wikipedia](https://en.wikipedia.org/wiki/Mangalore#Geography_and_climate) =)
Please let me know, what you think. Thanks !

**Comment by planemad** [comment]
Beautiful results!

@aromalram has one of the best output here having a significantly high level of information density and managing to look very simple 💯 

Areas for improvement:
- The north arrow is over abstracted and the representation would not be obvious to a casual reader
- The railway station is not on the railway track!
- Many of the east-west roads have a very slight angle to the horizontal and looks like imprecise placement. Align such roads neatly to a perpendicular grid
- The red H marker for `Historical attraction` can be easily mistaken for a hospital icon
- Beaches look like parks with the green color, and the color contrast is too low to make out clearly
- The color of water for canals is significantly different from the sea, and might not be obvious since it is missing from the legend
- Some road corners are curved while others are not. The style should be consistent
- Label the major roads, waterways for better orientation
- Create a hierarchy in the place names. Currently Kannur city looks just as important as Payyanur village
- Create a sense of scale, its unclear how far apart all these places are to a new person
- Relook at the symbology of attraction points. Blue feels like something related to water and grey has both natural areas and colleges. Try out some more alternatives, one could also use more symbols for relatable places (eg. a palm tree for beaches) that would add more character to the map

**Comment by planemad** [comment]
@vinodxyz The map looks super neat, wonderful work! The elevation shading is a good attempt, but since there are no other areas like this, it stands out as some kind of visual artifact like a small smudge.  One approach could be to resuse such a shading for the whole map to show elevation, or otherwise a simpler solution might just be to use a symbol to indicate a peak like a triangle with the height.

**Comment by planemad** [comment]
![new1](https://user-images.githubusercontent.com/126868/34973924-47a3b192-fab0-11e7-8edb-508013ed877f.gif)

Some great animated examples of how real world geography was abstracted for many subway maps: [Twisted tracks: watch metro maps transform to real-life geography](https://www.theguardian.com/cities/2017/jun/27/twisted-tracks-metro-maps-real-life-geography-visualised)

**Comment by planemad** [comment]
@BarshaP14 amazing improvements to the color scheme and geometry https://github.com/mapschool/course/issues/27#issuecomment-354428945 Love the bird in the diamond shape, play a little more with this shape that will allow it to be spotted at first glance. For me the heavier lines going through the neck take more attention from this shape.

With a few more improvements this would look great:
- Many lines are almost but not parallel, this would make it much neater
- There's inconsistency in the rounding of corners, adopt a consistent visual grammar
- Have a consistent scheme for placing points of interest (POIs), sometimes its on the road and sometimes not connected to anything, try a grid?
- Labels on the important roads
<img width="763" alt="map_abstraction_-_ii_ _issue__27_ _mapschool_course" src="https://user-images.githubusercontent.com/126868/34977059-24f7522a-fabf-11e7-8dfe-31e4bf98707d.png">

**Comment by jasleen20** [comment]
Amritsar Tourist map
![amritsar-02](https://user-images.githubusercontent.com/30645312/35026644-4925a6c0-fb72-11e7-9974-472595d8fcb5.jpg)
![amritsar-04](https://user-images.githubusercontent.com/30645312/35026645-49725a74-fb72-11e7-83ba-aab96a1d0257.jpg)

**Comment by planemad** [comment]
@jasleen20 nice start, eager to see how it goes based on the inspiration from others.

**Comment by iamreetika** [comment]
Hello @planemad @rasagy 
This is my exploration for tourist map of Bhopal. I was unable to attend the map abstraction classes and could only work on this now. I am sorry this is really late, but please give your feedback. Thanks a lot!

![bhopal_tourist map-01](https://user-images.githubusercontent.com/22998482/37406938-74465052-27be-11e8-8f1c-397f1cef42ad.png)

**Comment by niranjan41** [comment]
Hi @planemad @rasagy @all, attaching my version of Belgaum city tourist map.
Would kindly like to know the feedback on this one.
(It has been really late, sorry for the inconvenience. )

![belgaum schematic map](https://user-images.githubusercontent.com/11681600/39573198-de0b3e00-4eef-11e8-8c96-a033ca8651a4.png)

**Comment by rasagy** [comment]
Thanks everyone for showing not just the final result, but the progress! Closing this. :)

**Comment by manasvhanmane** [comment]
![mapartboard 11](https://user-images.githubusercontent.com/32028594/44778346-5853cb80-ab9a-11e8-81a2-fa9e45bc4a99.jpg)
Two maps I found. The left one is from an old government report. The one on the right is the current Google Map.

![mapartboard 1 copy1](https://user-images.githubusercontent.com/32028594/44778512-ca2c1500-ab9a-11e8-9d65-bee748b45925.jpg)
I didn't want curvy roads. So I traced the Major Highways geometrically.

![mapartboard 1 copy 21](https://user-images.githubusercontent.com/32028594/44778559-f5166900-ab9a-11e8-85de-57543f6643e9.jpg)
Similarly, the streets. I only chose to highlight lanes which are 4 lanes or bigger.

![mapartboard 1 copy 41](https://user-images.githubusercontent.com/32028594/44778581-08293900-ab9b-11e8-94b7-a50bc1ac1d72.jpg)
There is a railway line passing through the city, but it isn't of much significance as only a few trains plying between Pune and Mumbai stop there.

![mapartboard 1 copy 51](https://user-images.githubusercontent.com/32028594/44778670-3870d780-ab9b-11e8-990d-fe60eef41d8e.jpg)
The multiple rivers lines around the land mass basically set the boundaries of the city. One Major river even passes through the heart of it.

![mapartboard 1 copy 71](https://user-images.githubusercontent.com/32028594/44778753-6c4bfd00-ab9b-11e8-93e1-0ed58031b47b.jpg)
I want to make the streets more geometric, so this is still a work in progress.
