### ISSUE TITLE
Custom maps in a day — Cartogram & Studio explorations

### ISSUE THREAD

**Issue by rasagy** [mapschool/cartography#28]
Hey @mapschool/infdpg16! Let’s kickstart the new year with some map styles inspired from contemporary art. We’ll be using a fun tool called [Cartogram by Mapbox](https://www.mapbox.com/cartogram/) to pick colors from an image and use automatically create a map style with those colors.

### 1. Picking colors with Cartogram

Let’s pick a contemporary painting and try and create two map styles:

1. **Bold**: Create a visually compelling map style with high contrast, different hues using the painting’s color palette.
2. **Minimal**: Create a subtle map style that has a subtle contrast, while keeping it legible.

Once you’re happy with your style, share a screenshot with how Bangalore looks in the two styles on this ticket.

![screenshot 2018-01-02 12 13 24](https://user-images.githubusercontent.com/1117531/34478051-a2ae2014-efc4-11e7-9a76-b0019e95fc53.png)

### 2. Updating fonts with Mapbox Studio

- Once you have your styles ready, `save` the bold style to open it in Mapbox Studio.
- Find a font family that you feel matches the painting or would work well on the map. You can pick free fonts from [Google Fonts](https://fonts.google.com/), [Font Squirrel](https://www.fontsquirrel.com/) or from [collections](http://freetypography.com/) & [blog posts](http://makerbook.net/best-free-decorative-fonts/).
- Filter for just the `symbol` layers, and select multiple layers and update the font accordingly.

![screenshot 2018-01-02 12 19 50](https://user-images.githubusercontent.com/1117531/34476752-8357c0ea-efb9-11e7-946a-ab3d98cbf048.png)
![screenshot 2018-01-02 12 24 08](https://user-images.githubusercontent.com/1117531/34476751-83197f92-efb9-11e7-8d74-566fb359b780.png)

----

Interested in learning more about Map Design principles? This guide by Amy Lee Walton is a great place to start: https://www.mapbox.com/map-design/

**Comment by pkd2512** [comment]
Color palette from image _The Persistence of Memory_

## Map Style 1 (**Bold**)

![image](https://user-images.githubusercontent.com/7580745/34475072-e943277a-efad-11e7-924f-baf5cb9402e8.png)

## Map Style 2 (**Bold**)
![image](https://user-images.githubusercontent.com/7580745/34475207-f2bc7a52-efaf-11e7-9304-f6abc348eb07.png)

![image](https://user-images.githubusercontent.com/7580745/34475228-1b793bf6-efb0-11e7-9498-b360d5360a1d.png)

![image](https://user-images.githubusercontent.com/7580745/34475112-84ed2ee6-efae-11e7-9a4b-e97b73332c2d.png)

![image](https://user-images.githubusercontent.com/7580745/34475121-ac82134a-efae-11e7-919a-815bcb1824d2.png)

![image](https://user-images.githubusercontent.com/7580745/34475133-dbc009a0-efae-11e7-9c82-5b3eacf47709.png)
 

Now the idea was to use the same painting to come up with a minimal palette with subtle contrast between the elements.

## Map Style 3 (**Minimal**)
![image](https://user-images.githubusercontent.com/7580745/34475486-965a859e-efb2-11e7-9296-7cde627b6877.png)
 
![image](https://user-images.githubusercontent.com/7580745/34475496-ae5e4982-efb2-11e7-9447-34c225471b95.png)

![image](https://user-images.githubusercontent.com/7580745/34475502-c4dd1c38-efb2-11e7-80cd-686d815032a1.png)

## Map Style 4 (**Minimal**)
![image](https://user-images.githubusercontent.com/7580745/34476443-c453e2fc-efb6-11e7-9109-dcd1ef31beaf.png)

![image](https://user-images.githubusercontent.com/7580745/34476449-d3f1484e-efb6-11e7-94c9-ac843bb3b5ca.png)


# Map font updated to Merriweather

![image](https://user-images.githubusercontent.com/7580745/34476773-ccf3639e-efb9-11e7-8c97-7a22c6ced387.png)


* Regular for Countries
* Bold for POIs
* Italics for Roads
* Light for the rest of the labels

![image](https://user-images.githubusercontent.com/7580745/34476717-3a154902-efb9-11e7-80ad-cc6b8d258041.png)

Now I tried to use a font called _Dali_ that resembles the artist's remarkable mustache.

![image](https://user-images.githubusercontent.com/7580745/34477007-eb207a6c-efbb-11e7-8f86-0789a88bb7cf.png)

![image](https://user-images.githubusercontent.com/7580745/34477033-41ca7a5c-efbc-11e7-8125-5b5983071c5b.png)

Feel free to check out the map style [https://api.mapbox.com/styles/v1/pkddapacific/cjbx8ejm1e3zi2rmf3i4hojef.html?fresh=true&title=true&access_token=pk.eyJ1IjoicGtkZGFwYWNpZmljIiwiYSI6ImNqMDNnZWExdjBhNWozM3AzZGJqbWVsbnAifQ.s6XTs8U9qu8Hwbuc4Fe3zA#14.3/12.975992/77.587075/0]()

**Comment by aromalram** [comment]
The painting chosen: Le Rêve (The Dream )by Pablo Picasso

## Bold Style

![op2](https://user-images.githubusercontent.com/22998147/34475136-e20b6a52-efae-11e7-8e72-d13b925c77c7.PNG)

![op2b](https://user-images.githubusercontent.com/22998147/34475151-f9fe069c-efae-11e7-8977-d4fd44783dd6.PNG)

![op2a](https://user-images.githubusercontent.com/22998147/34475152-fc7a9ea8-efae-11e7-9c26-2dcceba6294e.PNG)

## Minimal Style

![op3c](https://user-images.githubusercontent.com/22998147/34475499-b8434eb6-efb2-11e7-9616-0d9cd24ec4ae.PNG)

![op3b](https://user-images.githubusercontent.com/22998147/34475500-bbfc936e-efb2-11e7-960b-c012c52bd444.PNG)

![op3a](https://user-images.githubusercontent.com/22998147/34475501-c1ac720c-efb2-11e7-8583-68b98b9dd36d.PNG)

## Map Font Updated to Q Type Office Pro

![for font_q type](https://user-images.githubusercontent.com/22998147/34476796-fcbc34de-efb9-11e7-9bb3-84c453d7bc78.PNG)

**Comment by rasagy** [comment]
### **Bold** styles from _The Scream_:

![screenshot 2018-01-02 11 19 14](https://user-images.githubusercontent.com/1117531/34475138-e843f862-efae-11e7-93b4-81b346878ac7.png)
![screenshot 2018-01-02 11 22 23](https://user-images.githubusercontent.com/1117531/34475165-38e32464-efaf-11e7-8306-06cc0b7defa1.png)

### **Minimal** styles from _The Scream_:
![screenshot 2018-01-02 11 47 03](https://user-images.githubusercontent.com/1117531/34475495-ae3169a8-efb2-11e7-8664-70bf025df721.png)
![screenshot 2018-01-02 11 44 36](https://user-images.githubusercontent.com/1117531/34475497-ae72736c-efb2-11e7-93ab-4a11bf3a4681.png)


### Updating fonts in Mapbox Studio

Here is a bold style with **Merriweather**:

![screenshot 2018-01-02 12 31 16](https://user-images.githubusercontent.com/1117531/34476682-f6c3b40e-efb8-11e7-8066-96c459f6cdcd.png)
![screenshot 2018-01-02 12 24 08](https://user-images.githubusercontent.com/1117531/34476696-107f95d4-efb9-11e7-92de-17663ca462f6.png)
![screenshot 2018-01-02 12 33 29](https://user-images.githubusercontent.com/1117531/34476706-28909ce0-efb9-11e7-89fb-f48355c6856a.png)

Here is the same style with **Action Man**:

![screenshot 2018-01-02 14 31 31](https://user-images.githubusercontent.com/1117531/34478944-c8b10b96-efc9-11e7-9081-04b3f635373b.png)
![screenshot 2018-01-02 14 31 11](https://user-images.githubusercontent.com/1117531/34478945-c90e4afe-efc9-11e7-894f-338c946e8f55.png)

**Comment by iamreetika** [comment]
Cafe Terrace at Night | Vang Gogh | Bold style
<img width="1280" alt="screen shot 2018-01-02 at 11 17 57 am" src="https://user-images.githubusercontent.com/22998482/34475134-dd40c454-efae-11e7-8d62-2df62e9aa89e.png">
<img width="1276" alt="screen shot 2018-01-02 at 11 17 18 am" src="https://user-images.githubusercontent.com/22998482/34475135-dfb33d3e-efae-11e7-8a11-ff689b889928.png">
<img width="1280" alt="screen shot 2018-01-02 at 11 29 42 am" src="https://user-images.githubusercontent.com/22998482/34475261-54865884-efb0-11e7-839d-e6be416c2350.png">

Minimal style

<img width="1280" alt="screen shot 2018-01-02 at 11 58 19 am" src="https://user-images.githubusercontent.com/22998482/34476145-5b8d1164-efb4-11e7-92cd-3d83f94820d8.png">
<img width="1280" alt="screen shot 2018-01-02 at 11 58 09 am" src="https://user-images.githubusercontent.com/22998482/34476163-5e3ef8fa-efb4-11e7-8caf-3c064f44a7c4.png">
<img width="1280" alt="screen shot 2018-01-02 at 11 57 51 am" src="https://user-images.githubusercontent.com/22998482/34476164-5ff89f48-efb4-11e7-89ad-692351dd70a6.png">

**Comment by BarshaP14** [comment]
Map Style1(BOLD)
![screen shot 2018-01-02 at 11 23 15 am](https://user-images.githubusercontent.com/25925845/34475179-74b9e20c-efaf-11e7-8ac5-976afe5a7af6.png)

**Comment by vinodxyz** [comment]
Edvard Munch's [Two people: The Lonely ones
](https://www.google.com/culturalinstitute/beta/asset/two-people-the-lonely-ones/GwGd2TaGklgGmA)

**Map-style 1: Bold**
<img width="1440" alt="screen shot 2018-01-02 at 11 48 58 am" src="https://user-images.githubusercontent.com/15855154/34475532-fdff111a-efb2-11e7-9708-956ba33549f3.png">

<img width="1440" alt="screen shot 2018-01-02 at 11 49 18 am" src="https://user-images.githubusercontent.com/15855154/34475537-0133706a-efb3-11e7-9cf4-7f1a1532b482.png">

View style on [Mapbox-studio](https://api.mapbox.com/styles/v1/vinodxyz/cjbx9pihre51z2sqvrsv24xsd.html?fresh=true&title=true&access_token=pk.eyJ1Ijoidmlub2R4eXoiLCJhIjoiY2owczFscm1hMDAzbDM4bHIzeGZoZXg4cSJ9.OsBqNXFDc4SfyodyrGwHGw#11.13/12.9725/77.5973)

**Map-style 2: Minimal**
<img width="1440" alt="screen shot 2018-01-02 at 11 54 15 am" src="https://user-images.githubusercontent.com/15855154/34475937-d8e68704-efb3-11e7-80f5-fc3bc2b298aa.png">

<img width="1440" alt="screen shot 2018-01-02 at 12 09 01 pm" src="https://user-images.githubusercontent.com/15855154/34476324-c505d97c-efb5-11e7-8a35-d04590e01574.png">

**Comment by holy-devil** [comment]
Andy Warhol: Untitled (marilyn monroe).

**Bold Style 1** 
![bold - 1](https://user-images.githubusercontent.com/4013612/34475221-0f7bee34-efb0-11e7-906f-13bdeef4cdd7.PNG)

![bold - 1 2](https://user-images.githubusercontent.com/4013612/34475374-7880b724-efb1-11e7-9716-a3c7871e48c6.PNG)


**Bold Style 2**
![bold - 2](https://user-images.githubusercontent.com/4013612/34475230-1bee3cf8-efb0-11e7-9bcb-1e4f3f7858d2.PNG)

![bold - 2 2](https://user-images.githubusercontent.com/4013612/34475233-1f7dcf82-efb0-11e7-8601-c1cdb72af5de.PNG)


**Light Style 1**
![light - 1](https://user-images.githubusercontent.com/4013612/34476168-71139558-efb4-11e7-9a1d-5af398c83f26.PNG)

![light - 1 1](https://user-images.githubusercontent.com/4013612/34476167-6e6deb6e-efb4-11e7-83d4-80999b1d7841.PNG)

![light - 1 2](https://user-images.githubusercontent.com/4013612/34476171-75c352d2-efb4-11e7-86fa-b6d955d734dd.PNG)

**Font Update with Avant Garde & Tisa**
Avant Garde font for pop art theme, Tisa to bring little Vintage map feel
![font 1 1](https://user-images.githubusercontent.com/4013612/34478711-7d8221ce-efc8-11e7-868b-01fa85b24350.PNG)

![font 1 2](https://user-images.githubusercontent.com/4013612/34478728-88f751a0-efc8-11e7-9517-5bfddd05916c.PNG)

![font 1 3](https://user-images.githubusercontent.com/4013612/34478735-8fe83d1c-efc8-11e7-8244-ec2be45dbed6.PNG)

**Font Updated for Bold Style**
Used Avant Garde & Cafe Aroma
Cafe Aroma is font similar to the Campbell's Soup font in Andy Warhol's art, while Avant Garde is font from Bauhaus period

![font 2 1](https://user-images.githubusercontent.com/4013612/34550830-f9e2873c-f139-11e7-8d30-e548e1c902cb.png)

![font 2 2](https://user-images.githubusercontent.com/4013612/34550831-fd8bc7fe-f139-11e7-8087-956c43b8b1be.PNG)

**Comment by BarshaP14** [comment]
Starry Night | Vincent Van Gogh
Bold Style
![screen shot 2018-01-02 at 11 35 00 am](https://user-images.githubusercontent.com/25925845/34475344-41f74bdc-efb1-11e7-99dd-614e32605d10.png)

![screen shot 2018-01-02 at 11 37 34 am](https://user-images.githubusercontent.com/25925845/34475363-65dcb384-efb1-11e7-8f0e-90f47396940d.png)

Minimal Style
![screen shot 2018-01-02 at 11 49 36 am](https://user-images.githubusercontent.com/25925845/34475565-383cb058-efb3-11e7-8bff-5d6bba8b2426.png)
![screen shot 2018-01-02 at 11 48 25 am](https://user-images.githubusercontent.com/25925845/34475568-3c9d611a-efb3-11e7-9e22-678a7808c7f0.png)

Map font updated to Source Sans Pro
![screen shot 2018-01-02 at 2 27 33 pm](https://user-images.githubusercontent.com/25925845/34478868-5553f7d0-efc9-11e7-9428-63a654bde280.png)
![screen shot 2018-01-02 at 2 32 11 pm](https://user-images.githubusercontent.com/25925845/34478953-d9b50514-efc9-11e7-8b5f-d226410919ff.png)

**Comment by jasleen20** [comment]
Girl with a pearl Earring - Bold Style
![bold 2](https://user-images.githubusercontent.com/30645312/34482933-50f10850-efe1-11e7-8d27-e7c1d2a20efc.jpg)
![bold 4](https://user-images.githubusercontent.com/30645312/34482935-5130c6b6-efe1-11e7-9697-7c0a89290d3e.JPG)
Minimal Style
![light 1](https://user-images.githubusercontent.com/30645312/34482957-79303af2-efe1-11e7-8302-72a58516e91b.jpg)
![light 2](https://user-images.githubusercontent.com/30645312/34482958-79679196-efe1-11e7-8431-470c291345b3.jpg)

**Comment by jasleen20** [comment]
Country name- **Tartine Script Offc Pro Regular**
State name- **Crimson Roman**
City name- **Crimson Italic**
https://api.mapbox.com/styles/v1/jasleen20/cjbx9pjz0e5c12rqym48b1ay8.html?fresh=true&title=true&access_token=pk.eyJ1IjoiamFzbGVlbjIwIiwiYSI6ImNqYnFqeWVobzA0YXUycXIwc3h6MDFweTAifQ._Urezsu2VYTk2UUjzbyC2Q#4.0/25.298434/85.245574/0

![pearl 1](https://user-images.githubusercontent.com/30645312/34483379-19988510-efe4-11e7-99c5-1aa91ac3f2f6.png)

**Comment by faaizasaeed** [comment]
ferry rides in mumbai

![mumbai_ferry_map](https://user-images.githubusercontent.com/22995838/34559105-a4e107f4-f166-11e7-976a-e53e3f4b3f53.png)

**Comment by rasagy** [comment]
Great work everyone! 👏 

Closing this ticket — if anyone missed sharing their work, feel free to add a comment with some screenshots.

**Comment by niranjan41** [comment]
**Painting: The Great Wave off Kanagawa by Hokusai**

**Bold Style -** 
<img width="1280" alt="screen shot 2018-05-03 at 21 12 36" src="https://user-images.githubusercontent.com/11681600/39594781-4b52018e-4f2b-11e8-9cd7-2ff893617279.png">
<img width="1280" alt="screen shot 2018-05-03 at 21 11 05" src="https://user-images.githubusercontent.com/11681600/39594782-4b843032-4f2b-11e8-89df-636f66189057.png">
<img width="1280" alt="screen shot 2018-05-03 at 21 20 08" src="https://user-images.githubusercontent.com/11681600/39594783-4bb0b9d6-4f2b-11e8-9661-0d9b96e9062b.png">

**Minimal Style -** 
<img width="1280" alt="screen shot 2018-05-03 at 21 15 05" src="https://user-images.githubusercontent.com/11681600/39594809-61e177a4-4f2b-11e8-945a-3e2e1ba38b2e.png">
<img width="1280" alt="screen shot 2018-05-03 at 21 15 00" src="https://user-images.githubusercontent.com/11681600/39594810-620e8140-4f2b-11e8-8c6f-f2a57b3e5086.png">

**Font updated to 'Philosopher' -**
<img width="1280" alt="screen shot 2018-05-03 at 23 24 28" src="https://user-images.githubusercontent.com/11681600/39594880-85c11850-4f2b-11e8-9979-36c824b73719.png">
<img width="1280" alt="screen shot 2018-05-03 at 23 26 23" src="https://user-images.githubusercontent.com/11681600/39594882-85efa92c-4f2b-11e8-890d-e3e2d3d458d5.png">
