### ISSUE TITLE
MAPart: Designing maps with a part of the complete map data

### ISSUE THREAD

**Issue by rasagy** [mapschool/cartography#29]
Hey @mapschool/infdpg16! Now that we’ve played a bit with [Cartogram](https://www.mapbox.com/cartogram/) and started seeing how [Mapbox Studio works](https://www.mapbox.com/help/studio-manual/#sample-workflow), let’s take a deep dive into the data that powers Mapbox maps, and the amount of customizability that we can get in Mapbox Studio.

We’ll split the class so each person will work on one of the [layers in Mapbox Streets Source](https://www.mapbox.com/vector-tiles/mapbox-streets-v7/#layer-reference) and work on creating multiple styles with that tileset.

Here are some inspiring projects that focus on a part of a map:
- [Morphology by Geraldine Sarmiento (Mapzen)](https://www.atlasobscura.com/articles/morphology-abstracted-map-cartography)
- [Emoji map by Katy DeCorah (Mapbox)](https://blog.mapbox.com/emoji-map-markers-9d1452bc856a)
- [Interchange Choreography by Nicholas Rougeux](https://www.c82.net/work/?id=350) (Also his Subway projects on [tracks](https://www.c82.net/work/?id=360) & [colors](https://www.c82.net/work/?id=343))
- [Typographic maps on the Axis Maps store](http://store.axismaps.com/product/typographic-map-san-francisco)
- [Mumbai landuse map by Akshay Kore (IDC, IIT Bombay)](http://info-design-lab.github.io/Data-Visualization-for-Mumbai/)

**Comment by rasagy** [comment]
Let’s get started! Here’s what each student picked up to work on:

 1. *Landuse + Landcover* — Barsha
 1. *Waterway + water* — Vinod
 1. *Aeroway* — Aromal
 1. *Building* — Reetika
 1. *Road* — Faaiza
 1. *Country, State, Place* — Jasleen
 1. *PoI Labels* — Prasanta
 1. *Road Labels* — Rajshree

Get started by making a new map style using the `Basic` template. You can hide the other layers and only focus on the layer you’ve picked, and explore different ways to style the layer, breaking the layer into multiple layers using Filters, and using property functions to vary styles within a layer.

To know more about the layer, make sure you go through the [Layer Reference for Mapbox Streets Source](https://www.mapbox.com/vector-tiles/mapbox-streets-v7/#layer-reference), as well as other styles (like Streets, Light, Outdoors) to learn how these are usually broken/styled.

For icons, feel free to use [Maki Icons Editor](https://www.mapbox.com/maki-icons/editor/) for styling the icons, or use any free to use icon library like [Noun Project](https://thenounproject.com/) and customize them in Illustrators. 
For patterns, look for resources like [Hero Patterns](http://www.heropatterns.com/) that have `.svg` patterns for downloading (Unfortunately, `.png`/`.jpg` won’t work).

If you’re using any artwork under the CC license, don’t forget to credit the creator (in your comment+in any final poster you create!)
  
For more custom map design inspiration, do play with some of these [styles created by Designers at Mapbox](https://www.mapbox.com/designer-maps/)!

**Comment by rasagy** [comment]
Here are some of my explorations in case you’re looking for more ideas:

### Roads colored based on the class:
![screenshot 2018-01-04 13 09 51](https://user-images.githubusercontent.com/1117531/34554013-aac24a5e-f150-11e7-96a8-7d72c2ab97d2.png)
![screenshot 2018-01-04 13 09 00](https://user-images.githubusercontent.com/1117531/34554014-ab02c39a-f150-11e7-8869-da24466d0af9.png)

### 3D Buildings colored by height data:
![screenshot 2018-01-04 13 36 56](https://user-images.githubusercontent.com/1117531/34556340-e1bbebea-f15b-11e7-9740-eb4066878df5.png)
![screenshot 2018-01-04 14 38 09](https://user-images.githubusercontent.com/1117531/34556592-edd2e2ac-f15c-11e7-89be-54119624e789.png)

### Map with Road labels
![screenshot 2018-01-04 14 44 11](https://user-images.githubusercontent.com/1117531/34557496-74aedd14-f160-11e7-9d71-9bca80a4208b.png)
![screenshot 2018-01-04 14 56 59](https://user-images.githubusercontent.com/1117531/34557504-7c243d96-f160-11e7-95c0-ea6bf642a347.png)
![screenshot 2018-01-04 14 56 21](https://user-images.githubusercontent.com/1117531/34557506-7cffb4ca-f160-11e7-8a35-f866f198eb9c.png)

**Comment by vinodxyz** [comment]
#Waterway + water

**Rivers in India**
<img width="1292" alt="screen shot 2018-01-04 at 3 36 19 pm" src="https://user-images.githubusercontent.com/15855154/34558671-080c0b14-f165-11e7-9c8f-3a777ffa943e.png">

**Rivers resembling nerves (_unknown place_)** 
<img width="1280" alt="screen shot 2018-01-04 at 3 38 08 pm" src="https://user-images.githubusercontent.com/15855154/34558745-4abbc9f4-f165-11e7-9119-9a0e34cb5123.png">

**Comment by BarshaP14** [comment]
WIP version of Landcover + Landuse
![screen shot 2018-01-04 at 3 44 00 pm](https://user-images.githubusercontent.com/25925845/34559036-5f4da396-f166-11e7-8beb-f45ebf4cc14e.png)

 Hillside with Contours
![screen shot 2018-01-04 at 3 56 24 pm](https://user-images.githubusercontent.com/25925845/34559460-f894bff2-f167-11e7-9b0b-33c05bad98ac.png)

Green Landcover
![screen shot 2018-01-04 at 4 34 40 pm](https://user-images.githubusercontent.com/25925845/34560807-5d372ab2-f16d-11e7-8410-85e71559af0e.png)

**Comment by jasleen20** [comment]
**Countries, states and cities**
![o3](https://user-images.githubusercontent.com/30645312/34559077-8f59c89e-f166-11e7-8f48-ed6a1a3e2441.JPG)
![o4](https://user-images.githubusercontent.com/30645312/34559083-9122656e-f166-11e7-9bb5-3244b52a42c0.JPG)
![o5](https://user-images.githubusercontent.com/30645312/34559084-920023c2-f166-11e7-94a6-8987473ebb60.JPG)
**Style 2**
![s2 2](https://user-images.githubusercontent.com/30645312/34559127-b796f61a-f166-11e7-9a5c-93b5a58e077a.JPG)
![style2 1](https://user-images.githubusercontent.com/30645312/34559128-b7d902da-f166-11e7-8f8a-8a9b86b62acc.JPG)

**Comment by iamreetika** [comment]
Buildings in Paris

Lego city
<img width="1280" alt="screen shot 2018-01-04 at 3 26 26 pm" src="https://user-images.githubusercontent.com/22998482/34559021-5138dbb8-f166-11e7-861d-1bdad8f9687a.png">

Concrete jungle
<img width="1280" alt="screen shot 2018-01-04 at 3 34 27 pm" src="https://user-images.githubusercontent.com/22998482/34559027-533fed66-f166-11e7-938d-2b1538d5c25b.png">

~
<img width="1270" alt="screen shot 2018-01-04 at 3 43 58 pm" src="https://user-images.githubusercontent.com/22998482/34559030-55856a1a-f166-11e7-8acd-880b5e67d457.png">

New York | If buildings were trees
<img width="1280" alt="screen shot 2018-01-04 at 4 14 51 pm" src="https://user-images.githubusercontent.com/22998482/34560109-9c3f253c-f16a-11e7-9b2a-5288ad158a4f.png">

**Comment by 5xza** [comment]
ferry rides in mumbai

![mumbai_ferry_map](https://user-images.githubusercontent.com/22995838/34559181-e7b568ea-f166-11e7-9f61-23263e06bee8.png)

**Comment by holy-devil** [comment]
![road labels](https://user-images.githubusercontent.com/4013612/34559226-1654301e-f167-11e7-9c5e-a9ebcb438941.PNG)

![road labels 1 1](https://user-images.githubusercontent.com/4013612/34559306-5ba16d08-f167-11e7-9073-6f666a658c3c.PNG)

**Font Explorations** ( low legibility 😞  )
![road labels 1 2](https://user-images.githubusercontent.com/4013612/34559305-5b60e102-f167-11e7-967d-4ba9b8216c22.PNG)

**Font Explorations** ( better legibility  😄  )
![road labels 1 3](https://user-images.githubusercontent.com/4013612/34559915-d2ac35ac-f169-11e7-9097-7594af854bdc.PNG)

![road labels 1 4](https://user-images.githubusercontent.com/4013612/34559917-d4819732-f169-11e7-9520-c108016314ee.PNG)

![image](https://user-images.githubusercontent.com/4013612/34560023-3a4f7cdc-f16a-11e7-8471-c1390517e7df.png)

**Comment by aromalram** [comment]
## Aeroways

### Delhi Indira Gandhi International Airport

![aeroways2](https://user-images.githubusercontent.com/22998147/34559252-2eba91b6-f167-11e7-9a63-41aa6dedd38b.PNG)

![g - delhi 3d](https://user-images.githubusercontent.com/22998147/34649665-9fb6d9fa-f3d9-11e7-87d6-758658fc6ea7.PNG)


### Mumbai Chatrapati Shivaji International Airport

![aeroways3](https://user-images.githubusercontent.com/22998147/34559314-638002f0-f167-11e7-8db3-f8deb29aae5b.PNG)

![g - mumbai 3d](https://user-images.githubusercontent.com/22998147/34649649-64e5163e-f3d9-11e7-858a-67fd7469a23e.PNG)


### Compilations
 
<img width="2356" alt="artboard 3 2x" src="https://user-images.githubusercontent.com/22998147/34649138-075a5a42-f3cf-11e7-8d67-dee6c9cadcdb.png">

<img width="2730" alt="artboard 1 2x" src="https://user-images.githubusercontent.com/22998147/34649122-a3044328-f3ce-11e7-9029-25c38e8c02a7.png">

<img width="2356" alt="artboard 3 copy 2x" src="https://user-images.githubusercontent.com/22998147/34649880-3c8faa9c-f3dd-11e7-9491-350b5ba91630.png">

<img width="3453" alt="artboard 5 2x" src="https://user-images.githubusercontent.com/22998147/34649882-428c490a-f3dd-11e7-9122-bff2bc6d127a.png">

**Comment by pkd2512** [comment]
Working with POI (Restaurants, Pubs, Cafes, Desserts etc.) in the Indiranagar region of Bangalore.

## Created a minimal style, keeping only the required elements.

![image](https://user-images.githubusercontent.com/7580745/34560125-abdaeaa8-f16a-11e7-8816-b1ee1cb4bb13.png)


## Modified it to hold only the icons (modified)
Also, switched to a dark theme to keep the icons (POI) on the foreground.

![image](https://user-images.githubusercontent.com/7580745/34560179-dcfeb308-f16a-11e7-9d06-c6e231266f1e.png)

![image](https://user-images.githubusercontent.com/7580745/34562229-6de0384e-f173-11e7-887b-fadea0071ed0.png)


## Demonstration of the region and the density of the places.

![img](https://user-images.githubusercontent.com/7580745/34560406-965c5cec-f16b-11e7-9961-b7f96a3429e8.gif)

**Comment by 5xza** [comment]
road connectivity in india WIP
![roadways](https://user-images.githubusercontent.com/22995838/34560460-ce4efe5c-f16b-11e7-93aa-a40bebbcc9ee.png)

**Comment by rasagy** [comment]
Great work, and thanks for updating your comments with more examples & compilations (especially @aromalram!)

With this exploration, I’m hoping each student in the class will feel comfortable with the layer they work on — if someone else gets stuck when styling a particular layer, you know who to ask amongst your class for help! 😉 

Closing this, feel free to continue updating your comments with compilations or final posters etc. if you want.
