### ISSUE TITLE
Custom map styles FTW!

### ISSUE THREAD

**Issue by rasagy** [mapschool/cartography#32]
Hey everyone at Ashoka University! Feel free to drop a screenshot of your custom map style made using [Cartogram](https://www.mapbox.com/cartogram/) here.

**Comment by quagzlor** [comment]
![divij custom map](https://user-images.githubusercontent.com/26856169/36539429-cf301664-17fc-11e8-9b41-40afa46cf3c4.PNG)

**Comment by barun511** [comment]
![image](https://user-images.githubusercontent.com/12569516/36539431-cfe47618-17fc-11e8-937f-a78b63aaadc1.png)

**Comment by thenerdyouknow** [comment]
![image](https://user-images.githubusercontent.com/16417887/36539427-ceb0e7ea-17fc-11e8-9038-4194dffe08b6.png)

**Comment by vineetred** [comment]
**The last supper**
![screen shot 2018-02-22 at 18 19 19](https://user-images.githubusercontent.com/22273088/36539473-f66b4398-17fc-11e8-8604-cf7e3383c170.png)

**Comment by prakhar171** [comment]
<img width="1440" alt="screen shot 2018-02-22 at 18 19 05" src="https://user-images.githubusercontent.com/25053767/36539479-010858f4-17fd-11e8-8ca0-dbddfa324f30.png">

Tel Aviv as Tel Aviv

**Comment by shivangi-t** [comment]
![tokyomap](https://user-images.githubusercontent.com/17799209/36539475-fbf05b6e-17fc-11e8-8877-ee1d50ccdfcc.png)
The Great Wave off Kanagawa

**Comment by kanangupta** [comment]
![screenshot 178](https://user-images.githubusercontent.com/27192219/36539498-1416219c-17fd-11e8-94c1-a729451ae299.png)

**Comment by agdhruv** [comment]
<img width="1280" alt="screen shot 2018-02-22 at 18 19 36" src="https://user-images.githubusercontent.com/17107048/36539488-0be07216-17fd-11e8-908a-af1d03037c68.png">
Starry Night

**Comment by preetha2711** [comment]
<img width="1430" alt="screen shot 2018-02-22 at 6 19 48 pm" src="https://user-images.githubusercontent.com/25063027/36539521-25feb1e4-17fd-11e8-8533-b4cd1e37200a.png">

**Comment by sanchit-bansal** [comment]
![mapboxnew](https://user-images.githubusercontent.com/13086868/36539683-9f50a5e8-17fd-11e8-870d-3c3400db7f62.png)

**Comment by Chetana-Pai** [comment]
<img width="1440" alt="screen shot 2018-02-22 at 6 19 54 pm" src="https://user-images.githubusercontent.com/21356478/36539531-32821e1a-17fd-11e8-8d8d-42a52bed78a6.png">

**Comment by abhishekmishramm1997** [comment]
![abhishek](https://user-images.githubusercontent.com/26635837/36539568-4faba6d2-17fd-11e8-82fb-d2179edfa374.png)

**Comment by hoominchu** [comment]
<img width="1275" alt="screen shot 2018-02-22 at 6 21 38 pm" src="https://user-images.githubusercontent.com/8168506/36539555-4504977a-17fd-11e8-8444-df31ecabae94.png">

**Comment by rpranav22** [comment]
<img width="1278" alt="screen shot 2018-02-22 at 6 22 57 pm" src="https://user-images.githubusercontent.com/14824859/36539626-74e038e6-17fd-11e8-81dc-0c994515577e.png">

**Comment by koishore** [comment]
![screen shot 2018-02-22 at 6 22 33 pm](https://user-images.githubusercontent.com/12604720/36539660-898f08ee-17fd-11e8-83d8-da09f0ea834b.png)

**Comment by Apuroop** [comment]
![screen shot 2018-02-22 at 6 24 49 pm](https://user-images.githubusercontent.com/11079746/36539709-b9fe8702-17fd-11e8-98aa-c4791ac70382.png)

**Comment by manchesterf** [comment]
<img width="1228" alt="screen shot 2018-02-22 at 6 25 21 pm" src="https://user-images.githubusercontent.com/21331490/36539728-c78525b6-17fd-11e8-873f-01fee57ea343.png">

**Comment by jyotica** [comment]
![screen shot 2018-02-22 at 6 25 12 pm](https://user-images.githubusercontent.com/27670524/36539758-e0dd6c94-17fd-11e8-8c02-6b6f9bf4615c.png)

**Comment by anshulclock0** [comment]
![image](https://user-images.githubusercontent.com/27948370/36539799-064df9e4-17fe-11e8-8ad3-bc04aba07d74.png)

**Comment by pmathew96** [comment]
![screen shot 2018-02-22 at 6 20 46 pm](https://user-images.githubusercontent.com/17100390/36539801-0704cade-17fe-11e8-904f-71d59f308da8.png)

**Comment by dhruvsinha** [comment]
![a2](https://user-images.githubusercontent.com/27192087/36539856-3b04200a-17fe-11e8-80e6-4e73efb81e1d.jpg)

**Comment by Adi-1190** [comment]
<img width="1280" alt="screen shot 2018-02-22 at 18 23 05" src="https://user-images.githubusercontent.com/28273877/36539869-4221a4b6-17fe-11e8-8f59-57767b26c5d3.png">

**Comment by salonibhogale** [comment]
![screen shot 2018-02-22 at 6 21 33 pm](https://user-images.githubusercontent.com/30047062/36539886-528770ce-17fe-11e8-8cc0-5e156442b872.png)

**Comment by barun511** [comment]
![image](https://user-images.githubusercontent.com/12569516/36539914-62f22a1c-17fe-11e8-98c7-184d4812dcd6.png)

**Comment by samridhkudesia** [comment]
![samridh](https://user-images.githubusercontent.com/16561829/36539946-7fa34182-17fe-11e8-9e37-5cdfecc8d750.png)

**Comment by dibyendumishra18** [comment]
![screenshot from 2018-02-22 18-29-02](https://user-images.githubusercontent.com/21334587/36539942-782d69e6-17fe-11e8-9696-ef646b1225d0.png)

**Comment by quagzlor** [comment]
![capture](https://user-images.githubusercontent.com/26856169/36539965-95f34360-17fe-11e8-8df8-6255fcdd43bc.PNG)

**Comment by koishore** [comment]
![screen shot 2018-02-22 at 6 36 09 pm](https://user-images.githubusercontent.com/12604720/36540182-5f6a196c-17ff-11e8-82a4-98c451210a6f.png)

**Comment by selah18** [comment]
![screenshot-2018-2-22 cartogram](https://user-images.githubusercontent.com/23417065/36540957-50f26986-1802-11e8-8857-f381dca9cad8.png)

**Comment by selah18** [comment]
![screenshot-2018-2-22 cartogram 1](https://user-images.githubusercontent.com/23417065/36542379-aa736b3c-1806-11e8-86cc-48b8e247435b.png)
BY Sifan Tilahun
