### ISSUE TITLE
Your own Scrollytelling project

### ISSUE THREAD

**Issue by rasagy** [mapschool/cartography#35]
Hey everyone at Ashoka!

We spent the past two days getting started with our scrollytelling project. To summarize, you can fork my repo to get an example visualization like this.

Once you submit the work, also share the github link to the visualization, along with a screenshot/gif of the page on this issue.

(Deadline: 5th March)

**Comment by Apuroop** [comment]
![screen shot 2018-03-08 at 9 24 05 am](https://user-images.githubusercontent.com/11079746/37132179-826ed75a-22b2-11e8-9ad6-d75e817fe3d0.png)

Hi,
You can check out our Project at [https://apuroop.github.io/urban_slums/]((https://apuroop.github.io/urban_slums/))

**Comment by rasagy** [comment]
Most students ended up using the internal assignment submission tool for this, will share some examples of assignments done. Closing this!

**Comment by planemad** [comment]
Interactive article from Washington Post on riots in DC that won an award for [innovative storytelling](https://nationalpress.org/newsfeed/washington-post-team-honored-for-innovative-storytelling/)

Link: https://www.washingtonpost.com/graphics/2018/local/dc-riots-1968/?noredirect=on

![new1](https://user-images.githubusercontent.com/126868/49284219-e8ffb780-f4b9-11e8-9995-7758034e2452.gif)
