### ISSUE TITLE
Data Tools

### ISSUE THREAD

**Issue by maulicule** [mapschool/cartography#45]
Hello everyone,

Just thought we could contribute our bit to MapSchool by creating a (non-exhaustive, of course) pool of resources that could be used.

This issue is meant for DataViz tools and parallel resources we find along the way, especially pertaining to GeoViz. We've all been there, wishing there were a single place which could guide us to the right data tool, and this is a step in that direction. There could be better ways to do this, but here's for a start.

Just so we can all Cmd+F (or Ctrl+F, for all Windows users out there) better, it would be nice if we could maintain a common format (likely to improve through suggestions, so please go ahead and add in your views about this too):
 - Name of the tool
 - Link to the tool itself or to its source
 - Type of tool: for now, the categories are **Data-Scraping/Visualisation/Annotation/Stories/Map Styling/Other**
 > (if you're using 'Other', mention category so it can get added to the list here)
 - Coding requirement rating: This is, ofc, subjective, but let's generalise it to **None/Basic/Intermediate/Advanced** for the moment, as plausible keywords
 - What it lets us do: 1-4 lines on, doesn't have to be fancy or even exact. Could do with what we used it for
 - Input type (if applicable)
 - Output type (if applicable)
 - Keywords: anything you feel could help others access the tool quicker through a simple search, as long as it's specific and relevant to the tool

Just to remember, we're pooling tools and resources here, so we can all search for them when the time comes. Hope we can all spare a few moments to make lives a tiny bit easier for all of us.

Happy GeoVizzing!
-Maulashree 🤓

**Comment by maulicule** [comment]
## Mapbox Cartogram
Link: You can find Mapbox Cartogram [here](https://apps.mapbox.com/cartogram/#9.84/19.0933/72.8341)
Type: Map Styling
Coding Requirement: None
What it lets us do: Drag and drop images to create map styles using colours taken from the image
![Screenshot 2019-09-07 at 00 33 07](https://user-images.githubusercontent.com/19164674/64453841-1fccc300-d107-11e9-9e25-e9c3cd1771d0.png)
Input type: Image files - jpg, etc.
Output: Map style for use in [Mapbox Studio]()
Keywords: Map styling, aesthetics, style, colour

**Comment by planemad** [comment]
Wonderful @maulicule, this could be quite useful. 

## Map Scrollytelling Template
Link: https://www.mapbox.com/solutions/interactive-storytelling/
Type: Map Story
Coding Requirement: Minimal

Build a scrolling map based story with text annotation and map animations by just editing a text template. No coding knowledge is required. Read more on the [Mapbox blog](https://blog.mapbox.com/create-location-based-stories-with-minimal-code-fc8c5da60d96) 

![](https://assets.website-files.com/5d56eaf8976151b27baf7740/5dc071f85102da6d50a33dcc_glaciers.gif)

Input type: Text file with the story content, Mapbox Map style
Output: Interactive HTML
Keywords: Storytelling
