### ISSUE TITLE
Sensory Mapping

### ISSUE THREAD

**Issue by rasagy** [mapschool/cartography#49]
Hi everyone,

Let’s get started on mapping the campus for the following senses:

1. See: Aishwarya, Anurag, Nikhil
2. Touch: Roopam, Ipsha, Deshna
3. Smell: Kanchan, Shravani, Sanjay
4. Hear: Akshay, Preeti

One person from each group can post the first attempt at mapping the sense from each of the three group members here, and add more progress as we go along.

**Comment by AishwaryaAnandSingh** [comment]
**See:** Aishwarya, Anurag, Nikhil
Third Floor | National Institute of Design

**1. Nikhil:** Mapping the tables and type of flooring on the third floor 
![unnamed (1)](https://user-images.githubusercontent.com/52406831/71613433-784f3100-2bcc-11ea-9060-732df90d8600.jpg)

**2. Anurag:** Object density mapping
![New Doc 2019-12-31 12 43 32_1](https://user-images.githubusercontent.com/52406831/71613326-dcbdc080-2bcb-11ea-962f-ce011d8a57e5.jpg)

Final
![Sensory Map-11](https://user-images.githubusercontent.com/52406831/72148717-7dc82a80-33c7-11ea-9a3d-7e7da60e0574.jpg)

**3. Aishwarya:** Mapping the density of objects I see in terms of color- amount of green(trees), furniture and concrete

Day 1
![New Doc 2019-12-31 10 53 16_4](https://user-images.githubusercontent.com/52406831/71613435-81400280-2bcc-11ea-9703-52038f29d047.jpg)

Day 2
<img width="458" alt="Screenshot 2020-01-02 at 11 11 47 AM" src="https://user-images.githubusercontent.com/52406831/71653136-c5f4a680-2d50-11ea-998d-0d2eb3450d00.png">


<img width="510" alt="Screenshot 2020-01-02 at 10 54 09 AM" src="https://user-images.githubusercontent.com/52406831/71652826-87f68300-2d4e-11ea-9103-385d6a53fcc0.png">

Final
![Cartography Sense see-04](https://user-images.githubusercontent.com/52406831/71811870-c2885480-309b-11ea-9478-ae1a9a6d2648.jpg)

**Comment by okshyeah-nid** [comment]
# Hear
Akshay, Preeti

## Akshay
### Mapping data
* Data is presented as a word cloud: louder the sound, bigger the word. It is accompanied by a map of the 3rd floor
![IMG_1114](https://user-images.githubusercontent.com/44680006/71613354-08d94180-2bcc-11ea-96b1-af1d76b3b4aa.JPG)
---

## Preeti
* Two kinds of sounds: discrete (ripple) and continuous (wave)
* Single point of observation
* Sound sources are colour coded
![IMG_9035](https://user-images.githubusercontent.com/44680006/71613405-5190fa80-2bcc-11ea-968d-662708fa13ff.JPG)
---

## Data collection
[Sensory_map_data_collection.pdf](https://github.com/mapschool/course/files/4029506/Cartography_2020-01-07_13.42.24.pdf)
---

### WIP 

* Using gradients to convey the spread of sounds in sectors of the arc.
![senosry WIP 1](https://user-images.githubusercontent.com/44680006/71652338-b8d4b900-2d4a-11ea-9f07-d943eea3c11a.png)

* Removed gradients as they created too much of color variations by overlap
![senosry WIP 1](https://user-images.githubusercontent.com/44680006/71704916-f4cb5500-2e02-11ea-9f5c-c4b713c429f8.png)

* Simplified the sectors to arcs
![Artboard Copy 43](https://user-images.githubusercontent.com/44680006/71652885-1965f500-2d4f-11ea-9961-707964ab73a6.png)
---

# Final viz
![Sensory map final](https://user-images.githubusercontent.com/44680006/71879362-f1fa9800-3153-11ea-96d2-df4bdaa6b50d.png)

**Comment by shrav13** [comment]
### Smell
Kanchan, Shravani, Sanjay

Kanchan : 

![New Doc 2019-12-31 12 49 58_3](https://user-images.githubusercontent.com/33093334/71613521-02979500-2bcd-11ea-875f-ec04ca860ca9.jpg)
![kanchan](https://user-images.githubusercontent.com/33093334/71653684-d1959c80-2d53-11ea-912c-489bb3370ea6.jpg)



Shravani : 

![New Doc 2019-12-31 12 49 58_1](https://user-images.githubusercontent.com/33093334/71613523-0aefd000-2bcd-11ea-846b-fcd7191dc097.jpg)

![smell map1](https://user-images.githubusercontent.com/33093334/71659355-4e814000-2d6d-11ea-8a6a-726ef2eb609b.png)


Sanjay : 

![New Doc 2019-12-31 12 49 58_4](https://user-images.githubusercontent.com/33093334/71613527-117e4780-2bcd-11ea-9f1c-754593834df1.jpg)

**Comment by RoopamSonpethkar** [comment]
**Group :Touch** 

![IMG_20191231_125815](https://user-images.githubusercontent.com/47752434/71613633-a4b77d00-2bcd-11ea-8baa-668f589a530a.jpg)
![IMG_20191231_125819](https://user-images.githubusercontent.com/47752434/71613985-560ae280-2bcf-11ea-9e42-9cee6e041197.jpg)
![Uploading IMG_20191231_125819.jpg…]()


![IMG_20191231_125852](https://user-images.githubusercontent.com/47752434/71613635-a5e8aa00-2bcd-11ea-8b1e-aa2e5ecc42cd.jpg)
![IMG_20191231_125904](https://user-images.githubusercontent.com/47752434/71613638-a84b0400-2bcd-11ea-9ef6-abb5b7c45f47.jpg)
![Nagpur2](https://user-images.githubusercontent.com/47752434/71613962-2bb92500-2bcf-11ea-8038-7e3658b182e3.jpg)

**Comment by kanchanrpathak** [comment]
![Smell1 copy 8@300x-100](https://user-images.githubusercontent.com/13308318/71708499-df145a80-2e17-11ea-8435-050ac1f0510d.jpg)

**Comment by Tanaya01** [comment]
![Sensory Map](https://user-images.githubusercontent.com/47748863/71998760-37a78580-3266-11ea-80cb-06e9b9bfce91.jpg)
