### ISSUE TITLE
Excel choropleths

### ISSUE THREAD

**Issue by sanand0** [mapschool/cartography#50]
Here are the [slides for the session on Excel Maps](https://drive.google.com/file/d/1CHt_zdYTIJf-Cg7auJb9nSLtOBxcWMP5/view).

Your exercise is to create a map story using the Indian parliament choropleth and the 2009 election data.

1. Download the [India parliament choropleth and 2009 data](https://drive.google.com/file/d/1LutQhSp8GR1YE-tFs6wvH072MpyrtQ_2/view)
2. Pick any column in the dataset
3. Update the choropleth and draw insights
4. Write a story about your insights
5. Enhance the map to showcase your story
6. [Upload your story and map](https://github.com/mapschool/course/issues/50) as a comment against this issue

The quality of your story is a function of whether
- The insight is surprising and/or useful
- The map supports your insight through good use of color scales and annotations
- The story and the map are engaging

**Comment by rasagy** [comment]
## Datasets:
- Roopam: Contestants (I)
- Aishwarya: Pop Density (Z)
- Anurag: Poll % (L)
- Ipsha: Women count (M)
- Shravani: Women % (N)
- Kanchan: Win Gender (O)
- Deshna: % Margin (U)
- Akshay: Name Length (AA)
- Nikhil: % Lost Deposit (X)

**Comment by Ipsha13** [comment]
![image](https://user-images.githubusercontent.com/47627914/71663750-6a401280-2d7c-11ea-861e-a17ca58fdacd.png)

**Comment by anurag24395sachan** [comment]
<img width="1023" alt="Screenshot 2020-01-02 at 4 30 27 PM" src="https://user-images.githubusercontent.com/52406963/71663994-44ffd400-2d7d-11ea-87f1-f8b2c0364ad5.png">

**Comment by okshyeah-nid** [comment]
![Artboard 3](https://user-images.githubusercontent.com/44680006/71664168-f868c880-2d7d-11ea-9b52-7eaa5db021e3.png)

**Comment by AishwaryaAnandSingh** [comment]
<img width="716" alt="Screenshot 2020-01-02 at 4 32 20 PM" src="https://user-images.githubusercontent.com/52406831/71664099-b2ac0000-2d7d-11ea-8015-3c8ede3f2f6a.png">

**Comment by kanchanrpathak** [comment]
![Men Women Winner@300x-100](https://user-images.githubusercontent.com/13308318/71664143-d0796500-2d7d-11ea-89bd-7a98f1901872.jpg)

**Comment by kanchanrpathak** [comment]
![Men Women Winner@300x-100](https://user-images.githubusercontent.com/13308318/71664458-0bc86380-2d7f-11ea-9c0d-81d5652f41a7.jpg)

**Comment by DarthElevator** [comment]
![Moneydeposit 001](https://user-images.githubusercontent.com/34890610/71664298-7c22b500-2d7e-11ea-8efe-14d1eff42df4.jpeg)

**Comment by RoopamSonpethkar** [comment]
![Untitled-3](https://user-images.githubusercontent.com/47752434/71664526-4500d380-2d7f-11ea-9371-749e13e9437d.jpg)

**Comment by shrav13** [comment]
![11](https://user-images.githubusercontent.com/33093334/71664619-91e4aa00-2d7f-11ea-9378-81e8f20bf9e6.png)

**Comment by DeshnaSV** [comment]
![Web 1920 – 1@2x](https://user-images.githubusercontent.com/52406999/71664772-53032400-2d80-11ea-9889-e9248ab243d1.png)

**Comment by Tanaya01** [comment]
![Excel map-05](https://user-images.githubusercontent.com/47748863/71664798-6a421180-2d80-11ea-848f-4c5cfa2d778e.jpg)
