### ISSUE TITLE
Assignment 2: Maps in Apps

### ISSUE THREAD

**Issue by rasagy** [mapschool/cartography#59]
# Goal
Pick a type of store/amenity/activity, pick a city (or cities). Make a simple app prototype that uses a customized basemap and shows a few places on top of it.

# Steps
- Pick a topic, explore a color palette/moodboard
- Create a custom basemap in Mapbox: [Customize Monochrome](https://docs.mapbox.com/studio-manual/guides/map-styling/), Play with [Cartogram tool](https://apps.mapbox.com/cartogram/) or make something [completely custom](https://docs.mapbox.com/help/tutorials/create-a-custom-style/)
- Bring in a layer of data that you want to show on top of the map — either manually added through [Mapbox dataset editor](https://docs.mapbox.com/studio-manual/reference/datasets/) or extracted from OSM (using [Overpass Turbo](https://overpass-turbo.eu/) & [Geojson.io](http://geojson.io/)). You can also just add a point or two directly in your prototype
- Use this map with a UI for a phone/desktop, and design a simple store/amenity locator app prototype in your tool of choice ([Adobe Xd](https://xd.adobe.com/ideas/process/ui-design/designing-map-ui-tips-and-inspiration/)/[Sketch](https://sketchapphub.com/resource/sketch-maps-plugin/)/[Figma](https://blog.mapbox.com/mapsicle-plugin-for-figma-a6ec2513bcf8) etc.)

Share your map styles, screenshots & prototypes as a comment below.

# References:
- [Guide to Map Design on Mapbox](https://www.mapbox.com/designers), [Tutorials for Mapbox Studio](https://docs.mapbox.com/help/tutorials/?product=Mapbox+Studio), [Creating minimal basemap](https://blog.mapbox.com/data-needs-to-pop-7-steps-for-designing-an-ultra-minimum-style-in-studio-cb57bdcbadb5), [Creating custom maps](https://blog.mapbox.com/5-steps-for-creating-a-custom-map-78edec940e4f), [Creating Map Taxonomies](https://blog.mapbox.com/map-design-taxonomy-chart-ae17b23df019)
- Read through blog posts on the process of custom maps such as [Le Shine](https://blog.mapbox.com/rise-and-l%C3%A8-shine-c0eaf9a964d5), [Tillamook](https://blog.mapbox.com/the-tillamook-tillamap-story-abe36227cdcb), [Wheatpaste](https://blog.mapbox.com/concept-to-map-my-ideation-process-c5663c375e16), [Cali Terrain](https://blog.mapbox.com/mapbox-cali-terrain-style-bea8cd410523), [Picture Book](https://blog.mapbox.com/the-story-of-picture-book-e0de74c107fa), [Mineral](https://blog.mapbox.com/designing-the-mineral-map-style-cc47e5a980b6), [Carson](https://blog.mapbox.com/carson-a-map-style-inspired-by-scientific-journals-4b6b1e344ec0), [Pencil Map](https://blog.mapbox.com/designing-the-pencil-map-style-f8c57dae0e88), [Spider Map](https://blog.mapbox.com/navigate-the-festival-universe-with-woov-12dc08dc2ae4) [](https://www.mapbox.com/blog/the-amazing-spider-map)
- Find more [on Mapbox blog](https://www.mapbox.com/blog-tags/map-design) and [Medium](https://blog.mapbox.com/tagged/design)

**Comment by arunkumaryes** [comment]
Topic - **Cycle repair stop finder 🚴‍♀️**

An extended feature of an existing service - Strava

WIPP: https://www.figma.com/proto/G0osIvtPTG8Q3MfMBHTUNH/Strava-Ext?page-id=0%3A1&node-id=1%3A2&viewport=163%2C441%2C0.7139642834663391&scaling=scale-down

**Comment by projectpolymer** [comment]
Topic - Cafes with working spaces and wifi or co-working areas :coffee: :computer:

Need to finalize the city:-
1. Bengaluru
2. Hyderabad
3. Chandigarh

**Comment by Bhanvee** [comment]
Topic - Famous filter coffee spots (independent/darshini-s/coffee houses/tiffin rooms etc.) in Bengaluru (especially in the central Bengaluru areas like Indira Nagar, Jayanagar etc.)

And maybe add a layer of other coffee shops nearby (serving new-age 'brews'), for those who would want to explore them as well

**Comment by sashacherian** [comment]
**Topic**: Cuisine based restaurants in the city. (Extension of the topic for schematic maps onto a app)
<img width="871" alt="Screenshot 2021-08-03 at 12 55 57 PM" src="https://user-images.githubusercontent.com/72463543/127975035-b5d693d8-2055-4b34-ba09-16f4236242b0.png">

**Video Link:** https://youtu.be/2hTQRkBpv1U

**Comment by rajeeshNite** [comment]
![Web 1920 – 6](https://user-images.githubusercontent.com/72493235/115661570-3e72e280-a35b-11eb-8d37-50f21e0e9b3d.png)

**Comment by rasagy** [comment]
Closing this. If some of you did work on this for the jury, please do add on your final output/link to your portfolios!
