### ISSUE TITLE
Assignment 1: Map visualization

### ISSUE THREAD

**Issue by planemad** [mapschool/cartography#6]
**Brief** Visualize the affidavit data declared by the MPs in the Lok Sabha on one or more themes: education qualification, assets or criminal cases using Mapbox Studio

**Data**
Add these to your style project:
- [MP constituency shapes](https://www.mapbox.com/studio/data/planemad.6wpgu5qz/)
- [MP constituency points](https://www.mapbox.com/studio/data/planemad.7hf43eyu/)
- Lookup myneta.info for reference

**Evaluation**
- Visual aesthetics
- Legibility
- Clarity - choosing an appropriate color scale for data represented
- Level of detail relevant to the theme

@mapschool/infdpg14

**Comment by planemad** [comment]
**Essential Reading**
- [Information Visualization - Perception for Design by Colin Ware](https://books.google.co.in/books?hl=en&lr=&id=UpYCSS6snnAC&oi=fnd&pg=PP1&dq=information+visualization+colin&ots=32At1kUFlf&sig=eegD3ruXlIMND3mgnArgiv6i3Yo&redir_esc=y#v=onepage&q=information%20visualization%20colin&f=false)
- [False Color - Wikipedia](https://en.wikipedia.org/wiki/False_color)
- [Building effective color scales](http://blog.visual.ly/building-effective-color-scales/)
- [Color brewer](http://colorbrewer2.org)

**Comment by nehaarsid1** [comment]
mapbox://styles/nehaarsid1/cij2xg2ax0025aokq8jyx5gln

**Comment by nehaarsid1** [comment]
https://api.mapbox.com/styles/v1/nehaarsid1/cij2xg2ax0025aokq8jyx5gln.html?title=true&access_token=pk.eyJ1IjoibmVoYWFyc2lkMSIsImEiOiJjaWoyZnZza2kwMDBodHBrbjlqbDR6aGZlIn0.WxW2orybuhZ2Zoa2BgwO7g#5.142869178798359/27.11788048749004/79.91282449653727/0

**Comment by nehaarsid1** [comment]
**Good Neta**

This visualization deals with members of parliament who have 0 crimes, 0 liabilities and have education qualification of minimum graduate level.

<img width="879" alt="screenshot 2016-01-07 10 07 33" src="https://cloud.githubusercontent.com/assets/126868/12162331/89f09b90-b526-11e5-9128-8979ebde849c.png">

[View map](https://api.mapbox.com/styles/v1/nehaarsid1/cij2xg2ax0025aokq8jyx5gln.html?title=true&access_token=pk.eyJ1IjoibmVoYWFyc2lkMSIsImEiOiJjaWoyZnZza2kwMDBodHBrbjlqbDR6aGZlIn0.WxW2orybuhZ2Zoa2BgwO7g#5.14/29.223/81.385)

**Comment by arshedhakeem** [comment]
Good Neha

**Comment by kunchapu** [comment]
No Crime record on MP's having total assets Less than 10,00,000.
Few Mp's have Assets more than  100 crores and edu less than 10th pass with crime records.
More Post Graduates and less crimes in UP & KL.
More Crimes in MH & Bihar and have more MP's whose Education qual is less than 10th Pass .

This viz compares Mp's having
Education qual : Less than 10th fail , Crime:  >0 (Red Circles)
Assets :  <10,00,000 (Light Green)   and   >100,00,00,000 (Dark Green)
[Click here to view map ](https://api.mapbox.com/styles/v1/vardhan/cij323twy003yasm6ozlbuvi6.html?title=true&access_token=pk.eyJ1IjoidmFyZGhhbiIsImEiOiJjaWl6cTVuaG8wMDU3dG9sejFwNzdyNjExIn0.tZJeoFVL88Bxh7oGbuJsvA#4.406206601792284/22.24668465757803/76.42767200054249/0)

**Comment by manaskumar7707** [comment]
The map shows the hierarchy of total assets, different gradients showing corresponding asset value. 
The map also shows criminal cases against the MPs(the area of the circle being proportional to the cases registered).
[Map link](https://api.mapbox.com/styles/v1/manaskumar7707/cij3doues005pasm6ctlhst3a.html?title=true&access_token=pk.eyJ1IjoibWFuYXNrdW1hcjc3MDciLCJhIjoiY2lqMmZ3cDM1MDAwc3V4a25seWt6eHIwdyJ9.V3935z_oMa_MkOucfYbC7w#5.536093087821398/12.93331470395188/76.1439416018531/0)

**Comment by nikhilshivpuja** [comment]
This map shows the education and category of India's netas 
i have used Dark red for gen netas who've studied more than 12th standard
and red for scheduled netas who've studied more than 12th standard
dark blue for gen netas who haven't studied more than 12th standard
and blue for scheduled netas who haven't studied more than 12th standard

The map is here [neta education](https://api.mapbox.com/styles/v1/nikhilshivpuja/cij3jv1kt005hbdm414jrnjqj.html?title=true&access_token=pk.eyJ1IjoibmlraGlsc2hpdnB1amEiLCJhIjoiY2lqMHdha2MwMDA4NXU0bTR1MDNzYnVwcSJ9.mlzSj31Vxp5U8foA5N9QwA#5.000000000000003/16.917838214981245/76.51212090648386/0)

**Comment by planemad** [comment]
This is great, keep it coming :rocket:

**Comment by prajography** [comment]
Map depicting assets of Rs.10000000 of different ruling parties across India.

https://api.mapbox.com/styles/v1/prajography/cij367v65001j8vm11t1vecch.html?title=true&access_token=pk.eyJ1IjoicHJham9ncmFwaHkiLCJhIjoiY2lqMHZ5d29qMDA4M3U0bTRudGpuZWdtbSJ9.7yC_PwL7i2PcE6WHPRsyAw#4/23.966175871341036/77.75573730459865/0

**Comment by arshedhakeem** [comment]
[Criminal Crorepati MPs -  major parties](https://api.mapbox.com/styles/v1/arshedhakeem/cij31ja19003hbdm4zthjntwd.html?title=true&access_token=pk.eyJ1IjoiYXJzaGVkaGFrZWVtIiwiYSI6ImNpajB0dDdubTAwN3R1NG00ZnM0czY5dzQifQ.lIw8WcejfKVYW18MZORJ0A#3.8612754655918637/20.826984402357652/85.57190596244965/0) 
- MPs with criminal records and assets more than Rs. 1 Cr
  Parties covered in visualization are 
  
  Bharatiya Janata Party
  Indian National Congress
  Shivsena
  Telugu Desam Party
  Telangana Rashtra Samithi
  All India Majlis-E-Ittehadul Muslimeen
  YSR Congress Party
  Assam United Democratic Front
  Janata Dal (United)
  Rashtriya Janata Dal
  Jammu & Kashmir People's Democratic Party
  Jharkhand Mukti Morcha
  Communist Party of India (Marxist)
  National People's Party
  Biju Janata Dal
  Shiromani Akali Dal
  Pattali Makkal Katchi
  All India Anna Dravida Munnetra Kazhagam
  Samajwadi Party
  All India Trinamool Congress
  Nationalist Congress Party
  All India N.R. Congress

**Comment by kunchapu** [comment]
**Sajith Nair** 

Educational Status of our MP's

[Click here to view Map](https://api.mapbox.com/styles/v1/sajithnirvana/cij36a7r9001l8vm181lh5a36.html?title=true&access_token=pk.eyJ1Ijoic2FqaXRobmlydmFuYSIsImEiOiJjaWozMG1yZGowMDJsdWdrbnoybW1sbGlvIn0.eHXlYDdXK7fe9U9JUnPKKA#4.544910802787698/22.945232414528647/80.5158529672911/1)

**Comment by tantadang** [comment]
[Netas in 10&100 crore clubs](https://api.mapbox.com/styles/v1/anishkrishnan/cij3s6hiz000qapkl0qeg6inm.html?title=true&access_token=pk.eyJ1IjoiYW5pc2hrcmlzaG5hbiIsImEiOiJjaWhjYncyeDcwMWRydGNsejRubXB5MzRlIn0.A3kdrdduu50RctPTe2-Qow#4.04/22.191/79.371)

**Comment by SuchismitaNaik** [comment]
The map shows the education level of netas in points (where the size of the dots increase with the level of education of Netas) along with asset values of constituencies (where the intensity of the colours increase with the increase in the asset values i.e. darker regions shows more asset values )

[Education vs Asset value](https://api.mapbox.com/styles/v1/suchismitanaik/cikmfnw3700chaxkiirqr63t9.html?title=true&access_token=pk.eyJ1Ijoic3VjaGlzbWl0YW5haWsiLCJhIjoiY2lqMmZ5N2N5MDAwZnVna25hcjE2b2Q1eCJ9.IYx8Zoc0yNPcp7Snd7yW2A#7.5761219320903175/22.94649657249775/78.05293082873578/0)

**Comment by tinozza** [comment]
The map shows the Distribution of MP's by the party they belong to and a cartogram showing candidates with criminal records (number).
[criminal netas](https://api.mapbox.com/styles/v1/tinozza/cikl6vmbj00baciluds056vxu.html?title=true&access_token=pk.eyJ1IjoidGlub3p6YSIsImEiOiJjaWozcW9jOGQwMDBndWRsdm9qdGN6OWR0In0.vwgC8wqwOZoVQ6yeND8cXg#5.01/15.692613956688348/79.20849609375261/0)

**Comment by planemad** [comment]
Grading done.
