### ISSUE TITLE
Storytelling with maps | NID 2021

### ISSUE THREAD

**Issue by pkd2512** [mapschool/cartography#61]
**DATASETS FOR ASSIGNMENT**
Volcanoes – https://www.ngdc.noaa.gov/hazel/view/hazards/volcano/event-search
Earthquakes – https://earthquake.usgs.gov/earthquakes/search/

**Pick one of the datasets and come up with a visual story using maps.** 
The end result need not be interactive. Use only QGIS and Illustrator for map design.

Inspiration from previous years
https://github.com/mapschool/course/issues/44
https://github.com/mapschool/course/issues/38

**Comment by rasagy** [comment]
These might she been shared on classroom. Optional for folks to post here as well if they want to document it for others.

Closing the issue for now.
