### ISSUE TITLE
#3 Cartogram & Custom map style experiments

### ISSUE THREAD

**Issue by rasagy** [mapschool/cartography#67]
Hi everyone,

Let us use this issue to share our Mapbox style explorations. You can use [Mapbox Cartogram](https://www.mapbox.com/cartogram/) with a set of brand colors to make a custom style for a particular brand, and then explore if you want to customize the typography & details further in [Mapbox Studio](https://studio.mapbox.com/).

For inspiration, you can check the #28 where your seniors made map styles inspired by some classical art paintings.

**Comment by kirtivardhanrathore** [comment]
![Burger King](https://user-images.githubusercontent.com/93124181/158100491-05d60718-59dd-432d-a9c8-f4d72feb4c3f.jpg)
![Nirvana](https://user-images.githubusercontent.com/93124181/158100445-c0549597-7c6c-4d6e-9d5b-7e7eb29e4014.jpg)
![Batman 1](https://user-images.githubusercontent.com/93124181/158100463-1e293237-8a37-490a-bfc1-0b6e2daf5304.jpg)
![Batman 2](https://user-images.githubusercontent.com/93124181/158100466-edf58fff-c407-45bc-adfe-4a7cebbdc390.jpg)

**Comment by SudevKiyada** [comment]
![map2](https://user-images.githubusercontent.com/44196782/158100551-cef4a85c-4701-4741-946f-3f4bfe2dd186.png)
![map0](https://user-images.githubusercontent.com/44196782/158100561-bdfc368f-2766-441f-a2fd-80619cb1fd3a.png)
![map1](https://user-images.githubusercontent.com/44196782/158172420-768be723-abc3-49bb-b80e-5ad3323298fb.png)

**Comment by ginaphil** [comment]
![Group 21](https://user-images.githubusercontent.com/32394598/158101459-1e815217-9df4-4526-9f10-3e7427cd74db.png)
![Group 22](https://user-images.githubusercontent.com/32394598/158101460-64d64795-b26d-4b05-a2d8-2129477642fb.png)

**Comment by Abhimanyu-Saha** [comment]
![3](https://user-images.githubusercontent.com/80443134/158101973-47c3cd51-ae12-4aef-a31d-114e3e47c6af.jpg)
![Durga-Pattachitra-early-21st-century-unidentified-artist-Sarmaya-Arts-Foundation jpg-453x375 jpg-1647183306554](https://user-images.githubusercontent.com/80443134/158102002-354d4313-d915-449c-b04a-ae24b70cec13.jpg)
![2](https://user-images.githubusercontent.com/80443134/158102019-6ff95581-8165-4039-8910-28557f480416.jpg)
<img width="701" alt="Group 3" src="https://user-images.githubusercontent.com/80443134/158102255-2bdcde9f-7cf6-42b9-b3c1-16986ea15d52.png">

**Comment by Talphi** [comment]
![1 B Tokai](https://user-images.githubusercontent.com/93115371/158105090-5909547b-a2a3-4735-862e-339fdd5baf9d.png)

![REDBULL](https://user-images.githubusercontent.com/93115371/158107012-ef13700d-7e1b-45d7-ae2f-63fad871e256.png)
![REDBULL 2](https://user-images.githubusercontent.com/93115371/158108625-4cdb5659-5bcd-44e4-b3f7-8460fa375277.png)

**Comment by aashibhaiji** [comment]
![City Map-01](https://user-images.githubusercontent.com/93115145/158105878-5234deee-adc9-48cd-902c-05bd20ccf3ac.jpg)
![City Map-02](https://user-images.githubusercontent.com/93115145/158105889-ec1b168f-7c62-40a2-a15f-82c8a8d2e9ee.jpg)

**Comment by filterkaapier** [comment]
### **Explorations**

![Lenskart](https://user-images.githubusercontent.com/93120763/158113670-156a672d-bbee-48ab-9294-8c7d9c8a6e81.png)
![Myntra](https://user-images.githubusercontent.com/93120763/158113680-25863ec1-a211-4015-bec6-85e3b7b34282.png)
![BB](https://user-images.githubusercontent.com/93120763/158147842-f0dab3e6-0a91-4d24-b7c9-9e71de105b9f.png)
![Domino's](https://user-images.githubusercontent.com/93120763/158147885-da570af7-4ec9-4cc1-868f-527421fc623d.png)



---------
**A Map inspired by Murakami book covers**

![MURAKAMI](https://user-images.githubusercontent.com/93120763/158137409-84aabea0-2e35-43cf-93bc-46ad8ba97035.png)

**Comment by PGauri** [comment]
<h1>Exploring with IPL Teams' Logo</h1>

![kolkata](https://user-images.githubusercontent.com/93117159/158241923-151d06dc-f12e-43a1-aace-071de85e672a.png)




![gujarat](https://user-images.githubusercontent.com/93117159/158247859-fae8fbe2-25a8-4498-8179-d936ab4b997e.png)







![Mumbai](https://user-images.githubusercontent.com/93117159/158245053-3fb01cfc-6c70-4c80-b0a9-dcd2a41ce19d.png)

**Comment by someshsahoo** [comment]
### Birthplaces of Indian Food Brands. 


![AB's](https://user-images.githubusercontent.com/93121881/158170101-426f829d-5ede-4f7e-b8ec-25e781402abe.png)


![AMUL](https://user-images.githubusercontent.com/93121881/158170129-49fe2c3e-15d7-4c4b-8932-e726d4e09a4c.png)


![BARBEQUE_NATION](https://user-images.githubusercontent.com/93121881/158170151-5081b1fc-9433-4ade-ab85-61a49b5179cc.png)


![BLUE_TOKAI_COFFEE](https://user-images.githubusercontent.com/93121881/158170168-373b9705-4b02-4621-88bf-8ad3ec007a71.png)


![WOW_MOMO](https://user-images.githubusercontent.com/93121881/158170228-9523e013-32c4-4053-b17f-265b38db64ab.png)

**Comment by Tej333** [comment]
![MacBook Pro 14_ - 1](https://user-images.githubusercontent.com/36147802/158306465-dfe9b11d-6d9a-489d-b710-2e2e63b517a1.png)
![MacBook Pro 14_ - 2](https://user-images.githubusercontent.com/36147802/158306486-584bb345-3691-4511-9d87-5f5d3120e602.png)
![MacBook Pro 14_ - 3](https://user-images.githubusercontent.com/36147802/158306491-9477513c-4d72-4c25-b3d2-62ec90297193.png)

**Comment by rasagy** [comment]
Hope you had fun doing these quick styles! Closing this now.
