### ISSUE TITLE
#4 Map in an app

### ISSUE THREAD

**Issue by rasagy** [mapschool/cartography#68]
Hi everyone,

Now that you’ve played with custom map styles in the last exercise (#67), pick a context where you could use this map. 

This could be…
* A website of a single shop/office/place of interest (like a museum) and a map showing where the shop is, matching their brand
* A website/app for a multi-store brand that allows you to find the nearest store to a user’s location
* An extension of an existing app, but with a new feature that leverages a map (like @Talphi’s idea of Spotify feature for mapping local artists)
* A completely new brand & app for which you can make a custom map style (like @kirtivardhanrathore’s idea of making a map of exploring different architecture styles)

Your final submission can be just a single screen (in a mockup of a laptop/mobile), or an interactive prototype using a tool of your choice (Xd/Figma/Framer…). Look out for plugins to directly bring in your map style from Mapbox, like [Mapsicle](https://www.figma.com/community/plugin/736458162635847353/Mapsicle) or [Figmap](https://www.figma.com/community/plugin/937760472566581732/Figmap) for Figma.

**Comment by Abhimanyu-Saha** [comment]
Hey Rasagy,

I have some topics in mind about the Map  in-app

1. A map of the _UFO sightings_ across the world (Website & App)
2. A map of treks conducted by a _Thrillophilia_ (Website & App)
3. #Old Topic: Misti map of Kolkata (a  map of all the 100 years old sweets shop in Kolkata) (Website)

**Comment by PGauri** [comment]
Brainstorming on the topics:
1. An app that helps one find accessible/ wheelchair friendly places in a neighbourhood
2.  A journaling app in which the user notes experiences at locations. (Expanding the feature set of Daylio)
3.  An app for movie buffs that shows locations where bollywood movie scenes have been shot

**Comment by kirtivardhanrathore** [comment]
Brainstorming topics.

1. An app that tells which art movement inspired the houses near you and also the year in which they were constructed.

2. An app that tells you the location of nearby policemen/ traffic policemen and you can decide whether to ask for help or not to take that route.

3. An app that collects data from stock image websites (shutterstock, unsplash etc) and tells you if there are photo-worthy locations around you. 

4. An app that gives you non-conventional options other than traffic to decide your route. For example, the path with the most scenic view and throws a notification to look out of the window if a good view comes around, the path with the least pollution levels, the path less traveled (thanks to Robert Frost for this idea) etc. 

Moodboard for Art Deco
<img width="638" alt="Mood Board" src="https://user-images.githubusercontent.com/93124181/161586766-d53a170d-a1c6-4278-af1b-289cb1faeeb8.png">

App Screens
![Frame 15](https://user-images.githubusercontent.com/93124181/161586802-17cd0b86-3f27-4b6a-90ab-f00f7038df01.png)

**Comment by someshsahoo** [comment]
**Few initial ideas about Map in App** 

- Map that shows places around you from where one can watch stars/constellations clearly (best spots to watch the night sky). 
- Map that shows HandiCraft Shops setups around you.

**Comment by SudevKiyada** [comment]
Some ideas for map in app

1. A crowdsourced application that shows all the graffiti spots around the city. People can click a pic of graffiti and upload it on the app for other people to see or even visit those spots. One more layer can be added where the app allows people to add digital stuff (immersive stuff) with graffiti as a marker.

2. An app that hides malls and stores for foreign brands and instead focuses on local artisans and businesses to promote swadeshi products.

**Comment by Nivia-J** [comment]
Ideas - 

1. Map showing scenic picnic spots in and around the city. 
2. Map showing places for group activities eg - Paint Ball, Ice skating, etc. 
3. Map showing places for adventure sports - Bungee jumping, Paragliding, rock climbing etc.

**Comment by chickensoup28** [comment]
Map in app ideas

- A map for MyGate that helps visitors better navigate a campus or a society, It could also help delivery personnel find correct flats by their flat number and deliver products with ease,

**Comment by filterkaapier** [comment]
Ideas for Map in App: 

### INTACH's app - 

1. Redesigning the Heritage Walks, and 
2. Adding local intangible cultural heritage like Performing arts, rituals, craft clusters etc. 

-------------------------------

![INTACH](https://user-images.githubusercontent.com/93120763/158515771-07980b47-92c8-42b6-91fa-9584c947bf42.png)

**Comment by ginaphil** [comment]
Map in app ideas

1. An app for finding zostels all over India
2. an app to locate and  connect with kathakali artists and kathakali institutes in Kerala 
3. A map to meet friends of similar interest (eg. people who want to play football together , readers club etc.)
4. An app to get design and art inspirations from all over the world

**Comment by Tej333** [comment]
Map in app  : Avacado cafe 
![Avacadocafe](https://user-images.githubusercontent.com/36147802/161445594-d69f4a04-d571-4a52-9a0a-c8b49a1d2a37.png)

**Comment by Santoastiesm** [comment]
Airbnb
![air_bnb_map_in_app](https://user-images.githubusercontent.com/101229434/161473538-b618e59b-a3bc-43e4-9eff-e7a1e9b8769a.png)

**Comment by kirtivardhanrathore** [comment]
![Frame 15](https://user-images.githubusercontent.com/93124181/161531565-acff87f5-4118-426d-bfb6-619bc37ff615.png)

**Comment by rasagy** [comment]
Thanks for posting your progress and submitting the final designs/prototypes on Classroom. Closing this now.
