### ISSUE TITLE
#5 QGIS explorations

### ISSUE THREAD

**Issue by pkd2512** [mapschool/cartography#69]
As we go on learning how to work with spatial data in QGIS, drop in your explorations in this thread.

* Write brief description of what your map shows and the data sources used
* Post map screenshots from QGIS showing WIP and final results

### [Refer to classnotes here](https://bit.ly/qgis-carto)

**Comment by pkd2512** [comment]
Here's what I made –  World map showing countries, river and lakes with 30º graticules

<img width="1050" alt="image" src="https://user-images.githubusercontent.com/7580745/160562907-e7e8126d-9fc1-4ca2-9975-cfa5ce461103.png">

**Comment by someshsahoo** [comment]
### QGIS Explorations 1
---

**Used 3 different shape files and tried exploring different filters, layerings, fill and label options.** 

1. Map showing my home state - Odisha on  India Political Map.
<img width="1512" alt="Screenshot 2022-03-30 at 09 33 15" src="https://user-images.githubusercontent.com/93121881/160750307-f6e26f24-5a8d-451f-84b6-e7fa1d20dc7c.png">

2. Map showing my home district - Cuttack on Odisha Political Map.
<img width="1512" alt="Screenshot 2022-03-30 at 09 31 55" src="https://user-images.githubusercontent.com/93121881/160750404-e6c14f36-4fa6-442e-b500-48c606b9e1e1.png">

3.Map showing Cuttack on India Political Map. 
<img width="1512" alt="Screenshot 2022-03-30 at 09 41 09" src="https://user-images.githubusercontent.com/93121881/160750437-d855c1dc-2118-4277-83a8-7bba715eee38.png">


### QGIS Explorations 2
---

**Used csv files and Hub Logo to make airports of world & airport connections.**

Airports categorised by countries
![World Airports Country](https://user-images.githubusercontent.com/93121881/160978646-55df68af-835b-4911-a4e7-fde95192ceec.png)

Airports sorted by Altitude
![World Airports Altitude](https://user-images.githubusercontent.com/93121881/160978773-5b972310-c587-408f-8d85-d450ec6f935c.png)


Airports - India to India Internal Connections
![India Internal Airport Connection](https://user-images.githubusercontent.com/93121881/160978823-6848bbc5-c06f-4cc3-9b72-c1be790a22a9.png)

Airports - India to World External Connections
![India World Airport Connection](https://user-images.githubusercontent.com/93121881/160978876-3a2c9050-31cb-4ae8-9b90-c0ad37aeeec2.png)

---
_Will be updating more explorations soon._

**Comment by chickensoup28** [comment]
<h1>Explorations </h1>
Started trying out some iterations with admin boundaries, state borders, districts and waterbodies in India.

States I have lived in:
![1](https://user-images.githubusercontent.com/93116394/160752252-5d890c11-d778-4736-9d5a-bf96afe35b0c.png)
Districts I have visited :
![2](https://user-images.githubusercontent.com/93116394/160752275-4e4659bf-0a43-4395-b486-c761823e6882.png)
Districts overlaid on states (no labels): 
![3](https://user-images.githubusercontent.com/93116394/160752394-0b4423e3-0c31-40a8-b435-9090ddff7ff1.png)
Water bodies in India (no labels):
![5](https://user-images.githubusercontent.com/93116394/160752402-a272e385-5a5d-45ca-9d94-58cbf236c105.png)
Overlaid elements:
![6](https://user-images.githubusercontent.com/93116394/160752404-cb488bd3-9e0e-43c4-a8a7-24a697d64ecd.png)

<h2>Home district map explorations</h2>

![bbdd0182-fbc6-416e-a3da-59fbff1f977e 1](https://user-images.githubusercontent.com/93116394/162500156-680d5f02-b28d-45ba-8e50-2b1f56315ef7.png)

Trying out color variations
 
![ohho](https://user-images.githubusercontent.com/93116394/162499917-6c3c7e92-1e95-45f5-ab49-f58f16631c68.jpg)
![fhfh](https://user-images.githubusercontent.com/93116394/162500318-a1d70c94-fcef-4617-abaf-319a5b8ee9a6.jpg)
![highi](https://user-images.githubusercontent.com/93116394/162501234-4eb07a46-f8ed-4f8d-bc01-3fc2d43560a5.png)

Bokaro has a lot of contours which I wasn't able to represent in any of the previous maps I made so I decided to do a hillshade render, adjust the colors and post process it in Adobe software. This also helped locate the river along with major points in the map better.

<h5>Feedback:
They all look good. The idea is to capture the essence of the place which I think it does. Think of what else makes the place unique. Are there mines?  How to show the steel plant better
Any forests? Tourist attractions? Right now the terrain takes up lots of the visual attention. Maybe you can play it down a notch and add more highlights to some of the other featues. Maybe you don't need all the rivers to be labeled? Or some different style for water labels and landmarks? Maybe add a small locator map on the composition to show where Bokaro is in India? Think of it as a design composition and proceed accordingly. The coordinates you wrote would make sense on the locator map, not so much for whole Bokaro. Also the scale can be simplified to show maybe just 10km? Hope this helps.</h5>
---
Trying out new variations

![9f3d2b50-19f9-48bd-a14c-94d3bf59ed1d](https://user-images.githubusercontent.com/93116394/162504022-2ab1dc70-e7fc-4ee3-b05d-66e4a1aa61e2.png)

![04d45904-1fd3-4456-80a9-a8ef9a24e0c2](https://user-images.githubusercontent.com/93116394/162503235-a2f7e637-9bd4-46ac-bdc2-c802d147fb25.png)

Final Map 
![0e4a03b7-fa48-4fb9-8ae5-565c6718d00a](https://user-images.githubusercontent.com/93116394/162503309-442bdd35-8430-4669-ab08-14d001aac776.png)

**Comment by kirtivardhanrathore** [comment]
<img width="881" alt="Domestic FLights" src="https://user-images.githubusercontent.com/93124181/160771964-2f3e802a-5675-4d97-afe3-0dcf13cac71f.png">
<img width="1219" alt="International Flights" src="https://user-images.githubusercontent.com/93124181/160771989-40a6ae67-e78e-4520-af7f-6825077c21e5.png">
<img width="1187" alt="Map" src="https://user-images.githubusercontent.com/93124181/160771994-b9d4cdc5-bcc1-4e8b-9b1a-1e17bed6f10a.png">

**Comment by Abhimanyu-Saha** [comment]
![Screenshot 2022-03-31 013539](https://user-images.githubusercontent.com/80443134/160921680-79692123-6b9d-4783-b0dd-c626001829ed.png)
![Screenshot 2022-03-31 102526](https://user-images.githubusercontent.com/80443134/160979628-0679e04d-3426-4751-8a22-94d66ef3764c.png)

**Comment by SudevKiyada** [comment]
Cell tower data : https://drive.google.com/file/d/1SH-8ywogdD2_3456Ryd9wZSUFCderMtu/view?usp=sharing

1. Cell tower presence in India
![cell_towers_presence](https://user-images.githubusercontent.com/44196782/160979476-9a739a72-ddd6-4e04-865e-2d2d371a404c.png)

2. Cell tower presence in India segregated by telecom provider
![cell_towers_telecoms](https://user-images.githubusercontent.com/44196782/160979590-5e4b8fe5-850c-4698-a258-c33ebbeb417e.png)

Meteorites data : https://data.nasa.gov/Space-Science/Meteorite-Landings/gh4g-9sfh

3. All the meteorites that ever fell on Earth
![meteorites](https://user-images.githubusercontent.com/44196782/160979583-31545aa8-56c3-46a8-b1ba-d77f1ec3034e.png)

4. M.G. Roads of India
![MG Roads_Poster](https://user-images.githubusercontent.com/44196782/164467128-35ce716e-900c-47ac-bf21-5d7fa09635cf.jpg)

5. Sedimentary deposits in Gulf of Khambhat
![Gulf_of_Khambhat_Poster](https://user-images.githubusercontent.com/44196782/164467410-7563a969-dca2-44bb-a67c-933956dad87c.jpg)

6. Meteorites of Oman
![Oman_Poster](https://user-images.githubusercontent.com/44196782/164467477-d8b9864f-e350-45e6-a98d-f3edd021f656.jpg)

**Comment by Tej333** [comment]
Airports at various altitudes


<img width="1792" alt="Screenshot 2022-03-31 at 10 27 23" src="https://user-images.githubusercontent.com/36147802/160979692-632cbd70-34f1-4459-8b9c-d93547085cc0.png">

**Comment by Nivia-J** [comment]
### **Exploration 1** 
-----------------
Airport connectivity in India <br>
![image](https://user-images.githubusercontent.com/93118546/160980278-7e122051-3bad-4868-8929-9c99d5b959ec.png)

<br> <br>

### **Exploration 2** 
-----------------
Intensity contours of an earthquake <br>
![image](https://user-images.githubusercontent.com/93118546/160980367-9047205e-a11e-4d33-8891-d7ce8b4e597d.png)

<br> <br>

### **Exploration 3** 
-----------------
Most populated cities of the world <br>
![20 most populated cities_v2](https://user-images.githubusercontent.com/93118546/161755907-ba34a568-8993-48ce-8e44-88e4254beecc.png)

<br> <br>

### **Exploration 4** 
-----------------
My Hometown <br>
![My hometown](https://user-images.githubusercontent.com/93118546/161755959-f883033e-e0eb-4cb8-a05c-a3cfde3eb132.png)

### **Poster** (WIP)
-------------
![poster ai  Recovered](https://user-images.githubusercontent.com/93118546/162284202-b9cf2516-019b-4c00-97f5-1fc82ceb0cc5.png)

**Comment by ginaphil** [comment]
Airports and altitudes
![world airport](https://user-images.githubusercontent.com/32394598/160980579-b5f4c5b5-e5bc-4d9c-a66e-d978daaebed0.png)
Taiwan Earthquake
![taiwan](https://user-images.githubusercontent.com/32394598/160980629-63586bd6-3dd6-4aa1-9480-a0f7ea8964c6.png)

### Map poster explorations

![image](https://user-images.githubusercontent.com/32394598/162152344-7d4a1d1d-0a03-4451-a6d2-1efb9d9f8088.png)
![A4 - 28](https://user-images.githubusercontent.com/32394598/162157049-8c4d5f21-566f-4e5c-8cec-f3052308404d.jpg)
![A4 - 25](https://user-images.githubusercontent.com/32394598/162157793-8cdf8472-c1e5-4108-939e-54a30c2d3faa.png)

### Map Poster - Kerala Flood Susceptibily and Landslides of 2018
<img width="595" alt="A4 - 27" src="https://user-images.githubusercontent.com/32394598/162157967-9d7a7647-b1e6-46b6-bcef-723d755f79e7.png">

**Comment by Santoastiesm** [comment]
<img width="1138" alt="Airports_from_ind" src="https://user-images.githubusercontent.com/101229434/160981052-4f203e77-e579-4b2b-961a-9c0e14372c13.png">

population data
<img width="672" alt="Untitled5" src="https://user-images.githubusercontent.com/101229434/164382362-bfc15ffb-50c0-4927-af58-da76b25356d7.png">

<img width="672" alt="Untitled2" src="https://user-images.githubusercontent.com/101229434/164403725-f6073b7f-00d8-4c03-bee7-fef8b952b6fb.png">


Rivers of India
<img width="897" alt="Untitled" src="https://user-images.githubusercontent.com/101229434/164403746-ce841855-0c56-4fee-ac0b-bf595d9f8cfa.png">

**Comment by PGauri** [comment]
Mapping the sea forts and the hill forts of the Maratha Empire across the Sahyadri Mountain Range

A WIP:

![Artboard 4 copy 2](https://user-images.githubusercontent.com/93117159/162184878-97d64f85-89f7-4db1-829d-05b1d2f0fcb3.png)

**Comment by pkd2512** [comment]
> Mapping the sea forts and the hill forts of the Maratha Empire across the Sahyadri Mountain Range
> 
> A WIP:
> 
> ![Artboard 4 copy 2](https://user-images.githubusercontent.com/93117159/162184878-97d64f85-89f7-4db1-829d-05b1d2f0fcb3.png)

@PGauri 

Looks good overall. A couple of thoughts –
* The hills look a bit like cloud waves; did you try a version without the DEM blend or light from the east?
* The map could be used to provide more context, like names of the towns, regions etc. Also could use a locator showing where this place exactly is.
* I'm sure the layout is WIP. You can try placing the illos and text blurbs on the map itself, once you enlarge the map on an A3? That would help play up the finer details of the map and make it the focus of your composition.

Cheers!

**Comment by pkd2512** [comment]
@Nivia-J 

Interesting map, although it feels a bit overloaded right now with all. the roads. A couple of suggestions to highlight things –
* Do you need all roads? Does the road mention any roads in particular? Maybe driving directions between the locations mentioned in the book in order? See if there is a way to filter and refine the road data, maybe even by using the inbuilt hierarchy of highways and secondary roads, depending on whether you have that in your dataset.
* It would be nice to have the major points labelled on the map itself. Do you really need the glow on the locator dots, trying a COVID visual metaphor? See how you can strike a balance between that and making closely placed dots legible.
* The map has all 1-D elements (lines) which makes it difficult to differentiate between figure and ground. See if there is better way to show the states which don't get mixed up with the roads. Stroke width and colour don't seem enough.

Also, since the map talks about navigation, try a Mercator projection (EPSG:3395). Also mention your data sources

**Comment by pkd2512** [comment]
@ginaphil 

The maps look lovely. I like both the colour and grayscale versions. Here are some thoughts to make them better.
* The network inside Kerala, are they water bodies? If so, they probably need to be the same colour as the ocean/water theme colour. Can even filter them to show only the major ones. Remember we don't always need to show everything. (_information overload is real_) Also, one thing to try is the terrain of the region, because there is a clear slope from east to west, which would show why the plains are so susceptible to water accumulation.
* Maybe label some important rivers and lakes (the ones more prone to flooding) – Periyar, Idamlayar, Mullaperiyar? 
* In the B/W version, the India colour in black makes it feel like the mass of the composition, while I would like to see Kerala in focus. Think about _Gestalt_ and how you can best bring out the information hierarchy. Also, the K'taka and TN border feels like a river. 
* In terms of the map furniture, the scale and compass are fine (may not need to write scale explicitly). However, the coordinates are a bit confusing, because it's a generic location of Kerala right? In such cases, it usually helps to add a locator map (India or Globe, showing the region in focus), and the coordinates would make sense when placed with that.

 P.S. You can use an online tool like DataWrapper or Flourish to make quick locator globes.

**Comment by filterkaapier** [comment]
**Early explorations**

![00](https://user-images.githubusercontent.com/93120763/162749377-dfc93fad-6281-4bc8-8059-11b2840e82eb.png)


--------

### Chennai's Trash 
<img width="842" alt="Chennai-Trash" src="https://user-images.githubusercontent.com/93120763/175761200-980ba267-2abf-4d26-a340-ed98226fb01a.png">

**Comment by filterkaapier** [comment]
**### A Poster of Chennai's Trash Landscape**
![Chennai's Trash](https://user-images.githubusercontent.com/93120763/175760731-74701880-1685-47d9-a865-5f2e90280bd4.png)
