### ISSUE TITLE
Sensory Mapping

### ISSUE THREAD

**Issue by rasagy** [mapschool/cartography#72]
Hi everyone,

As discussed, let’s use this Github issue for sharing progress on Sensory mapping exercise.

In a comment, add your name, sense & specific aspect if any, how you’re collecting the data & add the collected data from today in the comment (in whatever form you collected — paper / digital). 
Next, start sketching ways to represent something insightful in this data, and share every design iteration you do on Github issue by editing your original comment.

**Comment by geetanjalikhanna98** [comment]
**Geetanjali & Gagarina**

### Sense: Touch & Feel
_**Aspect Studied:** Seating around the NID campus & Comfort_

**Potential Narrative:** Which department sits most comfortably? :p

Inspired by a recent episode in class, we began the assignment with a common challenge faced by faculty and students across the NID campus which was finding comfortable seating that did not end up hurting you at the end of the day. In fact, while carrying out the exercise of data collection we got complaints from several departments highlighting how they had the worst seating on campus and how they picked the most suitable option for themselves based on certain criteria.

**How are we collecting the data?**

- To collect the data, we gained a quick overview of the different types of seating available on the campus premises (both conventional and unconventional)
- Defined different criteria for how people evaluate the sensation of comfort associated with seating. 
- The only way forward was to sit on different chairs & seating, and see how comfortable they were :p
-  Each seating was then evaluated on the criteria defined. 

![IMG_EDCA7539374D-1](https://user-images.githubusercontent.com/36082594/215665976-df4b86c3-ba06-4936-ac4a-0680557acc0e.jpeg)

**Some Photos:**
![WhatsApp Image 2023-01-31 at 8 15 29 AM](https://user-images.githubusercontent.com/36082594/215666317-d5c30ece-a0c1-4d4e-964e-f1087c7c1a84.jpeg)
![WhatsApp Image 2023-01-31 at 8 15 31 AM](https://user-images.githubusercontent.com/36082594/215666321-22e1ac3e-5eb1-493f-b097-d68bb145df8a.jpeg)
![WhatsApp Image 2023-01-31 at 8 15 27 AM](https://user-images.githubusercontent.com/36082594/215666326-60f78580-7746-410d-ab42-2db1a5ba2360.jpeg)
![WhatsApp Image 2023-01-31 at 8 15 26 AM](https://user-images.githubusercontent.com/36082594/215666327-8b18c37b-aa9b-45e6-9d9e-3104fbc84e5b.jpeg)
![WhatsApp Image 2023-01-31 at 8 15 25 AM](https://user-images.githubusercontent.com/36082594/215666329-3d69e825-7e6c-49d5-8798-6d30e924bcd2.jpeg)
![WhatsApp Image 2023-01-31 at 8 15 23 AM](https://user-images.githubusercontent.com/36082594/215666333-29cc47c7-fb1e-49b9-9cab-069c6f715977.jpeg)
![WhatsApp Image 2023-01-31 at 8 15 22 AM (1)](https://user-images.githubusercontent.com/36082594/215666335-0fe148db-6c26-4e0b-b33d-974e4737a01b.jpeg)
![WhatsApp Image 2023-01-31 at 8 15 22 AM](https://user-images.githubusercontent.com/36082594/215666337-d7e34d79-d12e-4aa4-a678-c1570688a50f.jpeg)
![WhatsApp Image 2023-01-31 at 8 15 21 AM](https://user-images.githubusercontent.com/36082594/215666340-3aedbd1d-4d66-41e3-b240-c2b1eae1f2d7.jpeg)

**Link to Data Sheet:** [Seating Comfort Sheet](https://docs.google.com/spreadsheets/d/1n9ietp0MU4-eFqk4liC-ETLAPUsJusdUh8DWjXB_tJw/edit#gid=0)


**Ideations:**

![WhatsApp Image 2023-01-31 at 3 50 49 PM](https://user-images.githubusercontent.com/36082594/215733816-17715941-09f4-4ab2-b113-56617d473555.jpeg)

![WhatsApp Image 2023-01-31 at 4 00 18 PM](https://user-images.githubusercontent.com/36082594/215735889-df9a8d3d-1da6-462e-981a-ad6ceda7867d.jpeg)

![WhatsApp Image 2023-01-31 at 4 03 42 PM](https://user-images.githubusercontent.com/36082594/215736534-c692d241-cf25-48e9-8b98-7e0522fd740b.jpeg)

**Comment by mohnishlandge** [comment]
# Mapping 
## Update
![Screenshot 2023-02-02 101757](https://user-images.githubusercontent.com/60274031/216234275-5d530e06-b1c1-4606-9f03-3bd579ebb5ce.png)


![Screenshot 2023-01-31 150638](https://user-images.githubusercontent.com/60274031/215723211-c6d7d629-be96-4bfd-aa41-ce51b831cdfc.png)
![Screenshot 2023-01-31 150515](https://user-images.githubusercontent.com/60274031/215723225-06c15fd9-6545-4999-9683-2446832674da.png)
![Screenshot 2023-01-31 151722](https://user-images.githubusercontent.com/60274031/215725794-242ad680-7bc8-4d30-ae87-334df336d53a.png)

![Screenshot 2023-01-31 155616](https://user-images.githubusercontent.com/60274031/215734988-600b90f7-cbf2-44e2-b97f-787e4620ab3f.png)



![image](https://user-images.githubusercontent.com/60274031/215674317-b5d42350-c865-4efc-8388-682820ef4648.png)
![image](https://user-images.githubusercontent.com/60274031/215677950-429bc82b-725a-4382-959f-a6ed92f1ed23.png)
![image](https://user-images.githubusercontent.com/60274031/215680032-86ec67f7-b85b-469f-a2f3-93c35ec20a54.png)

# Case Images
Possible? Needed?

![image](https://user-images.githubusercontent.com/60274031/215674680-7dda854c-7747-4c7c-84ce-133826b30991.jpeg)
![image](https://user-images.githubusercontent.com/60274031/215674722-72527353-e198-43c2-bb6a-ca61c88b7aa5.jpeg)
![image](https://user-images.githubusercontent.com/60274031/215674739-14647623-9736-4de4-b579-8270e44e4b4a.jpeg)
![image](https://user-images.githubusercontent.com/60274031/215674760-260111ef-c635-412d-bf35-e799d85e99fb.jpeg)
![image](https://user-images.githubusercontent.com/60274031/215674785-75b68272-d92b-498b-ba60-6450bddbe495.jpeg)

**Comment by 8PocketElf** [comment]
## light and darkness 


![toaz info-case-study-3-nid-bangalore-astha-khare-091110010-pr_06fa01b479f7dc2b1faf75f06c9a7aee-4](https://user-images.githubusercontent.com/111482797/215681961-e351545c-554c-46af-88ac-f94c3b9f0fbf.jpg)
![toaz info-case-study-3-nid-bangalore-astha-khare-091110010-pr_06fa01b479f7dc2b1faf75f06c9a7aee-3](https://user-images.githubusercontent.com/111482797/215681996-b2841b81-5cf4-47fb-9e83-da28606c89b9.jpg)
![toaz info-case-study-3-nid-bangalore-astha-khare-091110010-pr_06fa01b479f7dc2b1faf75f06c9a7aee-2](https://user-images.githubusercontent.com/111482797/215682000-1e03e2a1-3bf8-476c-bcaa-d5080514e057.jpg)

![image](https://user-images.githubusercontent.com/111482797/215682626-e4935e40-f99a-456e-90c1-2054689e66ca.png)

![Untitled_Artwork 2](https://user-images.githubusercontent.com/111482797/215697063-a8a8f800-d8f5-410c-86ce-79cd757efe19.png)
![image](https://user-images.githubusercontent.com/111482797/215722459-ff07cddd-78f6-465f-916b-bf184c935004.png)
![image](https://user-images.githubusercontent.com/111482797/215722556-8591fee2-396a-4b9f-a4e0-3002b6bec222.png)

https://docs.google.com/spreadsheets/d/1Lm8GaFfNhB4NPC8aRtYXkHZA4BjPMbak2awXAfYbTyk/edit#gid=0

**Comment by speckx** [comment]
**Rucha & Meghana** 
Dumb Ways to Die

**Space layout audit**

![Slide 16_9 - 3](https://user-images.githubusercontent.com/111493088/215683371-e0f9b8e4-dbf3-47b3-ae5e-311a72e7d57e.png)


**Object Audit**
![Slide 16_9 - 1](https://user-images.githubusercontent.com/111493088/215683483-78b119ca-5151-418b-a4c1-2b932a15ac60.png)

![IMG_2E4D7C3922FA-1 1](https://user-images.githubusercontent.com/111493088/215683543-f58f712d-0d6c-449b-9c2f-16e3dbef8402.png)

![Slide 16_9 - 4](https://user-images.githubusercontent.com/111493088/215731401-36f97122-518a-4538-901c-45d54e8459d8.png)

![Frame 1](https://user-images.githubusercontent.com/111493088/215731488-4ca66b1f-4fcf-4049-b794-59e4104e7209.png)



![Frame 2](https://user-images.githubusercontent.com/111493088/215733080-9cca88fc-3377-45dd-9366-f152a03a94a4.png)

**Comment by karthikeya-gs07** [comment]
# team green
***Parvathy, Karthikeya and Mrunal***

### Sense: Sight

## Context
Through Sensory Mapping, we are aiming to find the _**Most Greenest Spots of NID**_ by mapping all kinds of Greenery found both indoors and outdoors within the NID campus. Through this activity, we also tend to understand how varied and diverse the foliage here is at NID and study the best place for nature lovers to spend their time.

## Data Collection
The main mode of Data Collection is _Manual Mode of Collection by Observation & Note Taking_ where we as members divided and conquered and selected different areas and floors to observe and note down foliage

**These were a few of the factors we noted across the campus sort of like our observation manual**

![IMG_0380](https://user-images.githubusercontent.com/39125026/215691687-fc987f48-b228-4898-a89c-a81e6df196af.JPG)


**Behind the Scenes**

![9e118564-f66b-4074-8591-26785159c3fe](https://user-images.githubusercontent.com/39125026/215689279-ebbc2b68-a0f8-418f-87b9-ba12b894a4a1.JPG)
![BDC8C0D5-9E85-4BDD-BC1E-8E4FCCB57929 2](https://user-images.githubusercontent.com/39125026/215691855-c150d4ad-6c11-4c69-9694-c028fe88a0e0.JPG)
![IMG_0371 2](https://user-images.githubusercontent.com/39125026/215691955-c93db67f-2c36-4db7-b57f-7383d6c97a80.JPG)

**Failed Attempts**
We tried using an Application to pinpoint the location of NID Bangalore and count the tress around the campus i.e the outdoor foliage but it was unsuccessful

![IMG_0381](https://user-images.githubusercontent.com/39125026/215694237-03af0c0e-b50b-4cec-b19e-74d66378f1a5.PNG)
![IMG_0271](https://user-images.githubusercontent.com/39125026/215694261-ff67687a-c678-4782-8103-da962309e250.PNG)


## Structuring the Data
 We ended up entering all of our data onto a Google Sheet and formatting it to be homogeneous across the different parameters and this was where we started getting concrete takeaways to use for our visualisation. 

[Access Sheet here](https://docs.google.com/spreadsheets/d/1sHopq_gsTM_BsZE9yceU7GeCyRL83kCAx_Js518fc6A/edit#gid=0)

<img width="1117" alt="Screenshot 2023-01-31 at 12 54 57 PM" src="https://user-images.githubusercontent.com/39125026/215694609-c98d641b-fe57-4e53-85c5-327db42a9c2a.png">

## Sketches & Iterations

#1
![Untitled_Artwork](https://user-images.githubusercontent.com/39125026/215695538-773e7266-ee23-4fc0-8637-887bc94efd08.png)

![Untitled_Artwork 2](https://user-images.githubusercontent.com/39125026/215721528-63c1bf5b-4228-4be2-b245-8ded355f4fd0.png)

![IMG_0384](https://user-images.githubusercontent.com/39125026/215721597-1997c874-d13d-4f7c-b430-c0730a24635c.JPG)

![Untitled_Artwork](https://user-images.githubusercontent.com/39125026/215722844-d66d6563-da5f-4018-a4f1-8948340eca30.jpeg)

![image](https://user-images.githubusercontent.com/39125026/215723257-7f1a8401-d44a-48eb-b368-22dcbda852e6.png)

![image](https://user-images.githubusercontent.com/39125026/215723830-8f8102fe-2236-4c74-bc08-0daa9702ebe5.png)

**Comment by ankita360** [comment]
# The most popular spots at NID after classes

![Mask group-2](https://user-images.githubusercontent.com/123930284/215723303-0a5fa26b-c061-4d68-8c12-ff66365be752.png)
![Mask group](https://user-images.githubusercontent.com/123930284/215723345-883652fe-e4bb-4ccf-a0a6-0e104af2ee8a.png)
![Mask group-1](https://user-images.githubusercontent.com/123930284/215723262-8aba1a05-5d29-4e4b-9e7b-b583ed2591f4.png)

![sensory-map-final](https://user-images.githubusercontent.com/123930284/216236634-e8b1e901-eccb-419c-8d3a-8861b3bc0d10.png)

**Comment by Rajeshm006** [comment]
### Experience NID's Texture

Data collected :
1. Object
2. Actual Feel
3. What I experience 

![1](https://user-images.githubusercontent.com/111482817/215728879-3870bdac-0776-47d6-8f12-1476b75701a4.png)

![2](https://user-images.githubusercontent.com/111482817/215728927-62358f08-9ffe-480e-a2a8-b710f67726c5.png)

![3](https://user-images.githubusercontent.com/111482817/215728942-6566c8a0-3ee9-4f97-8f48-4ccadb60c6b4.png)

![4](https://user-images.githubusercontent.com/111482817/215728949-61fb941f-4fe5-413d-9d2b-b4e516219674.png)

![5](https://user-images.githubusercontent.com/111482817/215728953-88d7a8a0-40f7-4aad-afd1-8be01b91f8b0.png)

**Comment by harshkauntey** [comment]
### Flooring finishes of NID
Harsh kauntey
 Sense : Sight

### Context
Exploring the different material flooring finishes at NID campus ..

### Data collection 


![WhatsApp Image 2023-01-31 at 3 14 39 PM (1)](https://user-images.githubusercontent.com/104082495/215728078-b688e5f5-9d1f-46c4-bfd8-f87c98cbd2d6.jpeg)

![WhatsApp Image 2023-01-31 at 3 14 39 PM](https://user-images.githubusercontent.com/104082495/215728126-2a428732-875e-4035-9769-4dc189be415b.jpeg)

![WhatsApp Image 2023-01-31 at 3 14 38 PM](https://user-images.githubusercontent.com/104082495/215728182-c0e6ecbd-af44-419a-addd-17319f5f9f04.jpeg)


### Material images in different areas

![WhatsApp Image 2023-01-31 at 3 18 04 PM](https://user-images.githubusercontent.com/104082495/215729592-879462f8-8bff-4207-ae3f-5fc68ad05b03.jpeg)
![WhatsApp Image 2023-01-31 at 3 20 03 PM (1)](https://user-images.githubusercontent.com/104082495/215729607-cf8e19cb-2347-4cf8-8054-321f68a69b5c.jpeg)
![WhatsApp Image 2023-01-31 at 3 20 03 PM](https://user-images.githubusercontent.com/104082495/215729612-bce2dd14-0c6b-499b-8125-20f54b3029a0.jpeg)
![WhatsApp Image 2023-01-31 at 3 20 02 PM](https://user-images.githubusercontent.com/104082495/215729615-60057842-aa62-4aa4-9b7c-8c7eaf938f00.jpeg)
![WhatsApp Image 2023-01-31 at 3 20 01 PM](https://user-images.githubusercontent.com/104082495/215729618-7748ccba-cea2-491e-b059-8378b05c6cc1.jpeg)
![WhatsApp Image 2023-01-31 at 3 18 33 PM (1)](https://user-images.githubusercontent.com/104082495/215729624-4ad9e8e0-931f-4232-9155-8aa8edf3852a.jpeg)
![WhatsApp Image 2023-01-31 at 3 18 32 PM (1)](https://user-images.githubusercontent.com/104082495/215729630-947dc340-5a0d-4887-8789-2c460ec36b65.jpeg)
![WhatsApp Image 2023-01-31 at 3 18 31 PM (1)](https://user-images.githubusercontent.com/104082495/215729637-f12601a5-cba9-41e1-8287-2e5606d25ac1.jpeg)
![WhatsApp Image 2023-01-31 at 3 18 31 PM](https://user-images.githubusercontent.com/104082495/215729642-b78278ac-a903-4ee5-932c-f66316891c30.jpeg)
![WhatsApp Image 2023-01-31 at 3 18 30 PM (1)](https://user-images.githubusercontent.com/104082495/215729650-1df3f1d5-7a90-4c35-b047-e73a75e2a623.jpeg)
![WhatsApp Image 2023-01-31 at 3 18 30 PM](https://user-images.githubusercontent.com/104082495/215729658-d9cd0f15-4059-4d52-876c-26cf947bd7b6.jpeg)
![WhatsApp Image 2023-01-31 at 3 18 05 PM](https://user-images.githubusercontent.com/104082495/215729665-acab628b-d347-4ada-9f64-ae299c7ab22d.jpeg)

**Comment by amandeep2496** [comment]
![IMG_20230131_154928](https://user-images.githubusercontent.com/90832949/215733566-b34e6415-fb7b-4d67-912c-09947976cdee.jpg)

![IMG_20230131_154931](https://user-images.githubusercontent.com/90832949/215733455-9e561e85-f517-4d0b-b687-69354fe18cf3.jpg)

**Comment by rasagy** [comment]
Closing this issue. If any of you ended up making any further progress on this, please do update the issue. Thanks!
