### ISSUE TITLE
QGIS Map poster

### ISSUE THREAD

**Issue by pkd2512** [mapschool/cartography#75]
Based on learnings from the QGIS workshop, pick a geo dataset and visualize the same using a GIS tool or a combination of them. The final outcome should be an A3 poster.

The poster (explanatory or exploratory) should have -

1. Title and an intro with a clear takeaway from the visualization
2. One or more maps with DataViz, can be coupled with some other charts and graphs if needed.
3. Notes and sources used

**Comment by ParvathyRaju98** [comment]
# Unveiling the Saudi Conflict
**A Data-driven tale of USA vs Al Qaida through the years**

Terrorism in Saudi Arabia has been a significant concern for the Saudi government and the international community. Over the years, the country has witnessed several terrorist attacks by Islamic extremist groups, including Al-Qaeda and ISIS. Their targets included foreign civilians—Westerners affiliated with its oil-based economy—as well as Saudi Arabian civilians and security forces These attacks have caused numerous casualties and inflicted significant damage on the country's economy and infrastructure. Despite the government's efforts to combat terrorism, the threat of terrorism remains a considerable challenge, and the country continues to face the risk of further attacks.

Through this assignment on Thematic Cartography, I aim to shed light on the ongoing condition of the USA vs Al Qaida conflicts on Saudi Arabian soil and create a narrative experience.

**Data Set** [https://data.world/hdx/9f1f6436-5159-4e04-bf88-e1b8743d5d48](url)
_____

**Data Set Details**

-  Year of Conflict
- Start year of conflict
- End year of Conflict
- Active years of conflict
- Type of Violence (Violence Category)
- Conflict Name
- Side A (Who attacked)
- Side B (Who was attacked)
- Conflict headline (Headline)
- Location
- Region
- Governance regimen
- Lat / Long
- Start Date
- End Date
- Side A deaths
- Side B deaths
- Civilian Deaths
- Unknown Deaths

_Data set records from the year 1991 to 2018 only_

_____

**Data Cleaning & Analysis**

![Screenshot 2023-03-13 at 10 38 48 PM](https://user-images.githubusercontent.com/111482857/224774769-ffa61c11-60d4-4dca-a640-5acbc2d39065.png)

Data Analysis was done to derive narratives and pinpoint key takeaways, here are a few major ones

<img width="812" alt="Screenshot 2023-03-13 at 10 42 29 PM" src="https://user-images.githubusercontent.com/111482857/224775541-d47cf05b-8fb6-4af4-a2c0-c821c14dfb9e.png">

<img width="643" alt="Screenshot 2023-03-13 at 10 43 03 PM" src="https://user-images.githubusercontent.com/111482857/224776127-c434e277-2710-4859-8702-48de0a7d0cc0.png">

<img width="875" alt="Screenshot 2023-03-13 at 10 43 18 PM" src="https://user-images.githubusercontent.com/111482857/224776270-7a01426c-048a-4b4d-b127-fe6bd34f6b85.png">

<img width="646" alt="Screenshot 2023-03-13 at 10 43 27 PM" src="https://user-images.githubusercontent.com/111482857/224776384-83374203-4465-4355-b608-0d401ab411bb.png">

<img width="656" alt="Screenshot 2023-03-13 at 10 43 43 PM" src="https://user-images.githubusercontent.com/111482857/224776502-8edf8e66-6f59-4d1f-b291-fb7ee2966644.png">

<img width="967" alt="Screenshot 2023-03-13 at 10 43 54 PM" src="https://user-images.githubusercontent.com/111482857/224776579-a12168a3-f33e-4a3e-b238-b8976dc834ff.png">

_____

**Storytelling Script**
The next step was to create the narrative by building storytelling blocks based on takeaways from the data

<img width="1198" alt="Screenshot 2023-03-13 at 10 47 48 PM" src="https://user-images.githubusercontent.com/111482857/224777356-d5c32466-30a8-42d3-806c-544241f6c0fb.png">

_____

**Rough Sketches**

A3 Poster Sketch

![IMG_1051](https://user-images.githubusercontent.com/111482857/224778019-b761145b-9ee6-45e4-bee8-99c536bd1586.jpg)

Narrative Article Sketch
![IMG_1052](https://user-images.githubusercontent.com/111482857/224778267-c0eea87a-7a4e-4a83-9aee-e6375a80f4a2.jpg)
![IMG_1053](https://user-images.githubusercontent.com/111482857/224778332-c003fafa-91ed-4b23-addc-71a045a4c1bb.jpg)
![IMG_1054](https://user-images.githubusercontent.com/111482857/224778349-6a8199aa-f454-4322-8af5-1759d2731180.jpg)
![IMG_1055](https://user-images.githubusercontent.com/111482857/224778364-b95b8e75-b704-46b7-ae84-31c321dda4c2.jpg)

### Version One
![A2 Poster Saudi Conflict](https://user-images.githubusercontent.com/111482857/226234349-7ebf28ae-644d-4a45-8866-695d923acba7.jpg)

**Review Session Corrections**

- Minimise the look of the legend for the hero map, it looks like another chart in itself
- Sizing of the data encoded dots (2-20) make it more evident
- Make the legend have friendly numbers, not all the numbers
- Put indicators for 0 death regions too
- Subdue the grey tone of the Saudi Arabia map
- Add City Names
- Add numbers and callouts for all places where mortality is there not just for Riyadh
- Add water body labels
- Wording & language used can be made better Eg: USA vs Al Qaeda makes it sound like a wrestling match
- Bump chart can be made more aesthetic
- Rearrange the layout of the poster to bring bump chart onto the lower half
- Try incorporating the legend and description together to make it look like one
- Add time data, from which year to which you have plotted the data
- Add Data Source
- Try experimenting by swapping the data encoded: Dot denotes no of deaths cause it resonates to pool of blood and spokes show number of conflicts

### Version Two
![Printer Copy](https://user-images.githubusercontent.com/111482857/226235790-9a9f817b-9846-4472-af29-76ba4438ac01.png)

**Comment by Rucha-ux** [comment]
### Death Pockets for Afghani Migrants ### (Thematic Cartography Poster)

-----------------------------------------------------------------------------------------------------------------------------

Data Source : https://missingmigrants.iom.int/downloads
Data Context : Every year, hundreds of people die or go missing on migration routes worldwide. For every one of these people, there is a family awaiting news of their loved one and affected by their loss in a multitude of ways. There are likely tens of thousands of families who have loved ones who disappeared along the Central and Western Mediterranean routes towards Europe alone. 

Afghanistan is a leading country from which people migrate to other countries in search of better livelihood, safety, standards of living and security of family. The Taliban surged back to power two decades after U.S.-led forces toppled their regime in what led to the United States’ longest war.

Purpose of Poster : The poster calls for safe, humane and legal routes for migration. Better data can help inform policies to end migrant deaths and address the needs of families left behind and highlight the politics behind these tragedies.

* Note : My topic has shifted slightly from forced displacement to missing migrants. Furhter study led me to narrow down 
--------------------------------------------------------------------------------------------------------------------------

## Ideation ##

![image](https://user-images.githubusercontent.com/75575294/225262940-9e37c82f-baf5-477c-9060-c0f39ec4f36b.png)

![image](https://user-images.githubusercontent.com/75575294/225263021-5b7d7667-9d1c-4407-a1fd-790d853f79d8.png)

![image](https://user-images.githubusercontent.com/75575294/225263089-81555a70-7890-461d-9f46-1b77db174a5c.png)

![image](https://user-images.githubusercontent.com/75575294/225263130-36384dd1-11f8-4107-8dd6-35b6259a0da3.png)

--------------------------------------------------------------------------------------------------------------------------

## Data Cleaning and Formatting ##

https://docs.google.com/spreadsheets/d/1mHQ1Ek8uEkDZfHfC5yHXHtVQAzQVMNocmj-WhE_WIak/edit?usp=sharing

--------------------------------------------------------------------------------------------------------------------------

## QGIS Explorations ##

<img width="996" alt="image" src="https://user-images.githubusercontent.com/75575294/225263640-fe5a84a6-470d-4f17-adf7-fc639ffd2e02.png">

**Comment by ankita360** [comment]
<img width="2828" alt="A4 - 3(1)" src="https://user-images.githubusercontent.com/123930284/226084037-29ba9558-656d-446c-93c2-50085791363b.png">

**Comment by karthikeya-gs07** [comment]
# What happened on the US East Coast
A thematic map that showcases all the marine casualties (accidents) that happened in the Mississippi River and the east coast of the USA between 2000 - 2015. The data is sourced from the US Coast Guard's official website. 

**Data Source:** [Link](https://www.dco.uscg.mil/Our-Organization/Assistant-Commandant-for-Prevention-Policy-CG-5P/Inspections-Compliance-CG-5PC-/Office-of-Investigations-Casualty-Analysis/Marine-Casualty-and-Pollution-Data-for-Researchers/)

**Cleaned Data and Analysis:** [Link](https://docs.google.com/spreadsheets/d/15mffNqdA7rFOckf1vHHoJC40I_QyV0fP/edit?usp=sharing&ouid=109748890754691912564&rtpof=true&sd=true)

**Data Selection:** The Vessel Casualty / Incidents dataset was analysed for visualisation.
___

### Intent
To help viewers easily visualise the category of the vessel and the location at which the incident happened. To also have a better understanding of the types of vessels and their activities during maritime. An attempt was also made to educate and trigger an investigation on the casualty type and the location at which the incident occurred. 
___

### Final Post

![East Coast - Large Markers](https://user-images.githubusercontent.com/39125026/226498436-7cbf5efc-6a93-4670-978f-f74b74146aee.png)
___

### Interactive Prototype for iPad

Link: https://xd.adobe.com/view/4d2b5909-5139-449a-9477-c56bc6fa1d67-1878/?fullscreen

![East Coast - Interactive Mockup](https://github.com/mapschool/course/assets/39125026/5bf7f7fa-1221-4b30-87ba-a8feb6437fc3)

![iPad Pro 11in – 6](https://user-images.githubusercontent.com/39125026/226498860-d0570a64-7a65-44cb-8020-f03838367f4f.png)

![iPad Pro 11in – 27](https://user-images.githubusercontent.com/39125026/226498877-2262ba8f-d727-4d57-ba12-395694a2a7f0.png)
___
