### ISSUE TITLE
Map in an app

### ISSUE THREAD

**Issue by rasagy** [mapschool/cartography#80]
Hi everyone,

Let’s use this issue to work on our map-in-an-app exercise. Our aim is to create a prototype for an app where a map plays a key role.

**You can pick from the following approaches:**
1. Redesign the map experience that already exists in an existing app
2. Add a new feature/workflow that includes a map in an existing app
3. Create a new map-based app

**Document your design process:**
1. Idea, target user group, similar apps
2. Brainstorm potential problems this will solve/features it’ll offer (vs it won’t offer)
3. User flow, IA, wireframes etc for the concept
4. Aesthetic/branding inspiration (moodboard/references)
5. Map style using Mapbox studio
6. Hi fid screens/prototype

Aim for **three aspects** when incorporating this map in your app design:
1. Custom basemap designed in [Mapbox Studio](https://studio.mapbox.com/)
2. Overlays that focus on highlighting some info (can be added on Figma/any design tool)
3. Interactions with the map

### References
- My Pinterest board with some [inspiration for map-in-an-app](https://in.pinterest.com/rasagy/for-the-love-of-maps/maps-in-apps/)
- Great collection of [Map UI Patterns](https://www.mapuipatterns.com/)
- Mapbox’s [Guide to Map Design](https://go.mapbox.com/rs/117-NXK-490/images/the-guide-to-map-design.pdf)

**Comment by ipsitaccc** [comment]
Ideas for Map in an App

Idea 1
A very personalized itinerary for travelers in the form of a map where they can plan their day out and see information about crowd, weather, traffic conditions, time needed, accessibility etc.

Idea 2
A map where one can 'unearth' layers to see what existed in the same place 5, 10, 15, 20 years ago. (can experiment with variable map styles maybe)

![Slide 16_9 - 5](https://github.com/mapschool/course/assets/126864097/f762b658-6314-40d6-bf26-ad2320b02627)
![Slide 16_9 - 6](https://github.com/mapschool/course/assets/126864097/de0aa9c7-22e8-4859-8708-db35b608b6c9)
![Slide 16_9 - 8](https://github.com/mapschool/course/assets/126864097/cddc4b05-589d-45ec-b1b3-da7333c7377d)

![Slide 16_9 - 7](https://github.com/mapschool/course/assets/126864097/260fe2ad-aafb-4e62-bd06-aa3bd715d8b9)
![Slide 16_9 - 4](https://github.com/mapschool/course/assets/126864097/13564208-2684-4f85-8226-40449809d42e)




![Slide 16_9 - 1](https://github.com/mapschool/course/assets/126864097/0b2a571b-394b-41eb-93f8-06091b23b06b)
![Slide 16_9 - 2](https://github.com/mapschool/course/assets/126864097/1e0aba8e-80f3-416b-b665-ed4d5037170a)
![Slide 16_9 - 3](https://github.com/mapschool/course/assets/126864097/94f7e638-3b48-4f4e-bd4f-cba9c3a422e3)


![Untitled_Artwork](https://github.com/mapschool/course/assets/126864097/30affed2-96a4-486b-959f-47d1463d59db)
![Untitled_Artwork 1](https://github.com/mapschool/course/assets/126864097/56dc440c-49ae-44bc-9aa8-22b1443af711)



![Slide 16_9 - 14](https://github.com/mapschool/course/assets/126864097/ea96f476-046f-43a6-a674-d8e0fd202905)


### Final Submission

![1](https://github.com/mapschool/course/assets/126864097/e3e32e17-10e2-4fed-a295-2ace5492a00c)
![2](https://github.com/mapschool/course/assets/126864097/341e036b-9e50-433d-a231-d308d6059796)
![3](https://github.com/mapschool/course/assets/126864097/fc3e036e-2e2e-4169-a803-d6aa2901adab)
![4](https://github.com/mapschool/course/assets/126864097/c26e18ef-4669-4e45-98f7-7bc725b61d34)
![5](https://github.com/mapschool/course/assets/126864097/f62d410e-3906-4a55-99ec-5265a6a27249)
![6](https://github.com/mapschool/course/assets/126864097/3e02030d-4dd5-4d67-8144-97d90e3f8a7d)
![7](https://github.com/mapschool/course/assets/126864097/dea8e633-29bb-40e6-a8ff-a174b339d1df)
![8](https://github.com/mapschool/course/assets/126864097/13a00cb3-0534-4193-adb0-f73a32b18fea)
![9](https://github.com/mapschool/course/assets/126864097/237ed2fb-3a4c-4b7d-9230-924b7b188a08)
![11](https://github.com/mapschool/course/assets/126864097/c88698cc-77b8-426f-9d92-6c5091a0efdf)
![12](https://github.com/mapschool/course/assets/126864097/d33d369e-b0bd-4143-af75-31d952e24e68)
![13](https://github.com/mapschool/course/assets/126864097/23103ed9-da2a-4647-93eb-c689c07e6a17)
![14](https://github.com/mapschool/course/assets/126864097/5ddf8f11-84b7-48a5-890b-196ec67dd4e5)
![15](https://github.com/mapschool/course/assets/126864097/4d6da7c9-8998-4468-8fed-834df5eba08d)

**Comment by SamruddhiBulbule** [comment]
### **Submission:**
https://www.behance.net/gallery/192931809/Gpay-Expense-Tracking



### **Previously on...:**

Topics:
1. Metro route schematic map: Shows information about activities around the route and station
2. Who can do my task in city?- in small town where are the places & shops where I can get my work done
3. ### Map for gpay-expense tracking
4. Map Music: Can be a feature of app like spotify or new app. Embedded contextual music on map 


![Slide 16_9 - 1](https://github.com/mapschool/course/assets/126863744/7aa3e9b4-131a-4c0e-8513-689ea141c8c6)

![Frame 11](https://github.com/mapschool/course/assets/126863744/26102599-e279-4366-af85-28848b175eaa)

**Comment by anmllol** [comment]
Ideas for Map in App

**Idea 1**

A co-living app that helps users find compatible flatmates or roommates by matching them based on shared interests, hobbies, and professional backgrounds. The app includes a map feature displaying suitable locations along with nearby facilities.


**Target user group**

**Age group** - Young Professional (18-35 years old)

**Users**
  1. University students
  2. Recent graduates
  3. Bachelors
  4. Entry-level employees
  5. Freelancers
  6. Digital nomads 

 **Similar apps**

![similar apps](https://github.com/mapschool/course/assets/126863153/a1d883b1-d2d7-414b-a4b4-bf4070e52def)

1. Housing - Suggests nearby facilities via map however map is not the key feature of the application
2. Coliving.com (international application) - Use of map only for the rates of coliving spaces based on the location. 
3. happn Dating app - Map for locating places based on the users match and their interest.
More emphasis on map based match and other activity.
4. Meetup: Social Events & Groups - Exploring city through map and finding events nearby

 **User Problems**

1. **Compatible flatmates** - Difficulty finding potential roommates with similar interests and lifestyles through traditional methods.
2. **Suitable location** - Intimidating and time-consuming process of researching neighborhoods and available co-living options.
3. **Limited Amenities** - Uncertainty about access to necessary amenities and transportation links.
4. **Move-in difficulty** - Setting home at new location is a hassle. Finding suitable shops for basic needs is difficult.

**Experience**

1. **Interest hotspots**: Overlay the map with vibrant icons representing various hobbies and activities (e.g., music venues for music lovers, gyms for fitness enthusiasts).
2. **Proximity filters**: Allow users to easily adjust a radius around their desired location, focusing on areas rich in their chosen interests. For discovering nearby services for new movers. for eg., grocery shops, cleaning service.
3. **Dynamic co-living markers**: As users zoom and pan, see co-living spaces appear on the map, pulsating with different colors based on the user's interest match with the residents.
4. **Matchmaker feature**: A "Find My Tribe" button on the map that let the app suggest co-living spaces with residents based on the highest compatibility score based on shared interests and lifestyle.
5. **Virtual tours and walkabouts**: Schedule immersive virtual tours of the co-living space directly from the map marker, or propose local walks within the area to explore shared interests.

![image](https://github.com/mapschool/course/assets/126863153/00337a4e-bcde-420a-b85b-5cd60d64facb)

![image](https://github.com/mapschool/course/assets/126863153/3effad2a-1f34-4710-b599-c1a824e96928)

![image](https://github.com/mapschool/course/assets/126863153/942d741f-c691-4d63-ad24-e7b9d29530aa)

![image](https://github.com/mapschool/course/assets/126863153/5f31f74d-3cee-4288-bdd6-d944bf9534e6)

![image](https://github.com/mapschool/course/assets/126863153/08aff585-6cd0-4e26-baec-2190db2f98a1)

![image](https://github.com/mapschool/course/assets/126863153/8af18d25-dd57-4b92-89ad-c436562e1762)

![entire city](https://github.com/mapschool/course/assets/126863153/eda9eb65-87c9-4979-b3e2-a48e896352f5)

![Monochrome-1705643426093](https://github.com/mapschool/course/assets/126863153/1ad00aaf-83eb-41eb-9ff9-7e419cada102)

![m](https://github.com/mapschool/course/assets/126863153/1ab189f0-9204-40ab-a482-e36534992c9c)

![image](https://github.com/mapschool/course/assets/126863153/9be167be-d48e-4a22-898d-c45724372c14)

![draft](https://github.com/mapschool/course/assets/126863153/137f08e4-806f-405d-af89-d2b081c96d4e)

**Comment by UtkarshSing98** [comment]
IDEA 1 
A Map based interface for Google News to view news based on your location

IDEA 2 
Creating a Map for BookMyShow that helps users select the right hall and movie for them

IDEA 3 
A Map for Cubbon Park to find the right people with similar interest 





FINAL IDEA : Map for Users of Book My Show




### Target User Group: 

A Group of friends ( 18 -35 ) living in different areas in a metropolitan city (e.g., Delhi, Mumbai, Bangalore).
Occupation: Students and working professionals from diverse fields.
Technological Proficiency: Moderate to high proficiency with mobile applications and online services






### Problems

1. **Difficulty in Coordinating Timing**
Problem: It is challenging to coordinate with all friends and find a common time when everyone is free

2. **Challenges in Movie Selection** 
Problem: Selecting a movie that is agreeable to everyone can be a complex decision-making process

3. **Difficulty in Choosing a Cinema**
Problem: Selecting a cinema that is comfortable and convenient for everyone in terms of Location, Amenities, Nearby food places, Audio/Video Quality, Seats, and Parking, poses a challenge

4. **Budget Coordination**
Problem: Coordinating and aligning budgets for tickets can be challenging




### Current Booking Process

<img width="595" alt="A4 - 3 (1)" src="https://github.com/mapschool/course/assets/126862749/48a418bd-ee4d-42b9-9789-7888d8b0cc03">












### User Flow


![1705654032644 (1)](https://github.com/mapschool/course/assets/126862749/d54e6753-65e5-4b88-8a50-1c5542edcd98)



![IMG_20240119_140249](https://github.com/mapschool/course/assets/126862749/8276877e-fea4-4766-933a-59354b67ca79)

**Final Protoype:**
https://drive.google.com/file/d/1bGcyvwJyuXKiwZDMhRgF6ksbVwxfgW6Z/view?usp=sharing

**Currently working on the Payment screens and overall documentation**

**Comment by gmeenal98** [comment]
Idea 1 — Internal navigation of public spaces (eg. hospitals, festivals, markets, etc.)
Idea 2 — Public Transport Tracking (bus, metro); real time tracking like we have for cabs
**Idea 3 — How much have you traveled in your city; All the routes you have taken, places you have explored, etc.**
Idea 4 — Map your online expenses


**Features**
- Track your travel (roads, locations, etc.) with time stamps and travel history
- Customise your nodes by specifying certain locations such as home, workplace, friend's place, etc.
- Automatic map generation using location 
**(user does not need to add anything/ perform any task on the application if they don't want to)**
- Add friends to certain nodes/trips
- Gamification (unlock places, earn awards)
- Suggestions based on their usual travel
- Travel patterns


**Tasks**
- View your map
- Use filters (location, time range, etc.)
- Categorise your nodes
- Add pictures, notes, friends to nodes
- View travel patterns and suggested places
- Unlock places and earn awards (eg. new city, museum enthusiast, etc.)


**Similar Apps**
- Google maps, Google Fit
- Places Been
- Track My Journey
- PolarSteps
**Most of these applications require the user to actively add location points, etc for the journey to be recorded. Some only record destinations and not movement pattern.**


![Slide 16_9 - 13](https://github.com/mapschool/course/assets/127397480/04dc4e83-37b3-430e-98c3-15d91a6d8973)

**Comment by arunikasajith** [comment]
Concepts for map in app task:

**Idea 1:** Map to find pet-care / pet-friendly spaces
**Idea 2:** Map to find tender coconut vendors in Kerala
**Idea 3:** A map to track animals/birds within a national park
**Idea 4:** Map to locate houseboat tourism services and track the houseboat

![pet_space_app_arunika](https://github.com/mapschool/course/assets/126863213/8e2cc504-3384-4659-a469-482e78c87c72)
![pet_space_app_arunika_2](https://github.com/mapschool/course/assets/126863213/05628550-b025-4719-9f0d-9f8190099405)

**Comment by Meg-exe** [comment]
Topic ideas:
1. Markets of Mumbai
A Map showcasing all the markets in Mumbai and navigation through the various markets.

2. Ganesh pandal Trackers
A Map showcasing all the Ganesh pandals in Mumbai, its immersion spots and other relevant data like places to shop from for the occasion.


**Selected topic:** Markets of Mumbai - Making navigation easy through the markets of Mumbai.
![mom1](https://github.com/mapschool/course/assets/126862966/841fa648-1821-484a-bc14-ce2689750d1e)
![mom2](https://github.com/mapschool/course/assets/126862966/e8366a60-99f6-4430-bf64-48e0a8e8a787)
![mom3](https://github.com/mapschool/course/assets/126862966/a627c775-cb2b-4e21-b4b3-db2de360bc98)
![mom4](https://github.com/mapschool/course/assets/126862966/542747e8-0a7e-487a-b3a2-326679ace099)
![mom5](https://github.com/mapschool/course/assets/126862966/849db818-7f9b-492c-b552-762df763777c)
![mom6](https://github.com/mapschool/course/assets/126862966/c8cbda71-8d06-4aaf-b8c1-3c45c02ea6cd)
![mom7](https://github.com/mapschool/course/assets/126862966/d9702514-3d13-481f-9fb6-eb563cc2dbaa)
![mom8](https://github.com/mapschool/course/assets/126862966/c9314109-7765-4d17-8a70-a89a9c58e8f5)

**Comment by anjalikothari** [comment]
**IDEA 1 : 
A map in the existing NRC (Nike run club) app.**

IDEA 2: 
A map for an instore shopping experience (malls, melas) etc.

<img width="1920" alt="Slide 16_9 - 6" src="https://github.com/mapschool/course/assets/126863089/388b84de-14f4-4a10-9701-821c4ddfd5d5">

<img width="1920" alt="Slide 16_9 - 6" src="https://github.com/mapschool/course/assets/126863089/f7f61a69-ce46-4c15-b359-2f8fccb0a482">

documentation
![documentationmap](https://github.com/mapschool/course/assets/126863089/05b41057-5248-4421-aebb-42f2ee30744a)

**Comment by Eesha-2002** [comment]
### Topics

Idea 1 - An app helping piligrims in the Temple City of Puri to visit other hidden temples around the main temple and plan there stay in the city.

Idea 2 - Extension to the news application Inshorts, where people can also pick a place/state/country to read news from

**Idea 3 - An app to unearth monuments that have gotten lost over the years in the city of Bhopal**

Idea 4- An app helping you figure out places to shop for wedding wrt to their budgets, in different cities of India.


### Target User Group

**Cultural Tourists -** 
Cultural tourists visiting the city for the first time can get guidance to go about the city and learn about its rich culture and heritage. They can plan their visit with respect to their duration of stay, covering important destinations to get an essence of the city.

**College Students -**
As the city boasts a robust education infrastructure, it sees a huge influx of college students flocking the city every year. The app can be a guide to their city exploration and be a learning platform at the same time.


### Similar Apps / Competition

**Incredible India-**
The website gives information about heritage sites spread across India and is run by Ministry of Tourism. They have separate state government sites as well that help plan trips across their respective state.

**Google Maps -**
Provides location of places to visit and helps navigating to reach the destination.

**Sygic Travel -**
Similar to google maps but in mobile.

**Trip Hobo -**
Web-based application to plan a trip to a destination.
![ss apps](https://github.com/mapschool/course/assets/126862702/0b7291cf-3ef0-4fad-930c-7fca8f18ebeb)



### Problem Areas

1. No major mobile based application other than Google maps. Sygic Travel needs paid subscription to access ones itinerary.
2. Google maps cannot be used solely to plan a trip, needs juggling between various websites and applications.
3. All the websites cover only major tourist attraction and miss out on the less known monuments of a place.
4. No application solely dedicated to complete history and heritage of these places.
5. Most of them are just information portals about the places.
6. All the trips curated are based for 4-6 days travel, hopping between cities

### Experience that can be given
1. Narrates the history of a place as you go around the city.
2. Help plan heritage trails with respect to duration of the stay
3. Takes around lesser known monuments, thus shedding light on them.
4. Reduce hassle of juggling between various websites


### Probable Features of the App
PLAN | NAVIGATE | KNOW
1. Plan itinerary at a local level
2. View your plan on a map to gauge distances
3. Navigate to the spots and experience even lesser known spots on the go
5. Get information about the spots right on the application

Other features -
- Share experience on the blog and sociall media directly from the app
- Keep track of local heritage event taking place at various spots across the city and plan a visit.

### User Flows
![userflow](https://github.com/mapschool/course/assets/126862702/86be0d85-075e-4024-aa50-2e72a7df5466)


### Mood Board
![moodboard](https://github.com/mapschool/course/assets/126862702/2e74e6cd-34ae-4129-962d-edf238ed34c9)

### Mapbox exploration

Day Views
![Bhopal-Day-copy-1705546602834](https://github.com/mapschool/course/assets/126862702/b4bde186-5882-4aab-bdd3-87763635e146)
![Untitled-1705546168488](https://github.com/mapschool/course/assets/126862702/5127f024-ec5d-4e04-b2bd-16b0cbf68812)

Night view
![Screenshot (9)](https://github.com/mapschool/course/assets/126862702/2f70e749-f8fc-4bb1-8948-23cd7be2ad35)
![Screenshot (11)](https://github.com/mapschool/course/assets/126862702/36e45e4c-d78d-473e-9af4-5996d5c295a1)

**Comment by andriamarinus** [comment]
idea 1
An urban graffiti/ mural/ street art exploration application where users can locate graffiti from different artist of the city. The location of these street art is crowd-sourced. The app can be gamified by making it pokimon go-esque, where users can visit these spots, collect the artist's virtual stickers and gain points. The map style can change wrt to the style of art you are viewing.

![Slide 16_9 - 2](https://github.com/mapschool/course/assets/126863696/c8d8bcbc-afb4-4e35-9689-48892a9e22c1)
![Slide 16_9 - 4](https://github.com/mapschool/course/assets/126863696/efeb0365-637f-44ac-8fa0-58052d3d3211)
![Slide 16_9 - 10](https://github.com/mapschool/course/assets/126863696/7534e0a8-f2f7-4775-abf7-2c0b5060987a)
![Slide 16_9 - 91](https://github.com/mapschool/course/assets/126863696/86dfcd90-6a3a-49e8-904e-cd6d6a490c36)
![Slide 16_y9 - 11](https://github.com/mapschool/course/assets/126863696/9fe28a0f-d6ad-4540-b19d-233a61816d22)




idea 2
An application where you can view photos of a location from different time periods. It can incorporate AR technology to overlay historical photos onto the current view through the user's device camera. This allows users to see a side-by-side comparison of the past and present in real-time. These photos can be crowd-sourced.

**Comment by NomeshwariReddy** [comment]
1. Exhibitions/mela application
In big melas and exhibitions, people tend to get stuck of where is what and there is also tendency that they get lost or their children get lost in the crowd. the major problems is to understand where they are, knowing their surroundings. other problems yet to be mapped.

2. Creating Experiential Map using Music.
I am not pretty sure about this or not yet thought of the user group yet, but travelling or driving always associated with music.... so what can we do? to make this more experiential? could be like music based on location, playlists of people in that area etc., etc., Like that particular context people have local musics or popularly listening music and they can listen to it, i have to think about it.

3. Tourist Maps, customising their whole experience based on their timeline and providing ideas of how to go about it,, ex: a person came to banglore for 3 days and 2 days he have free time and he wants to spend time in bengaluru, but he dont know how to plan the distances etc., so he will install the app and enter his available dates and times , all his preferences, and the map will create a plan of it,,,,,

4. Adding a feature on dating applications locating the date places and right swipping to find right date places

<img width="1920" alt="B1" src="https://github.com/mapschool/course/assets/126862650/41febbd5-9109-4a77-859d-f5d24a2ee17e">
<img width="1920" alt="B2" src="https://github.com/mapschool/course/assets/126862650/1133c814-e3be-48ea-846f-91caf6d87f3e">
<img width="1920" alt="B3" src="https://github.com/mapschool/course/assets/126862650/c9677f4c-1f9d-4047-a636-2ffeb1086b4c">
<img width="1920" alt="B4" src="https://github.com/mapschool/course/assets/126862650/55b481e1-9774-4364-8e4b-3250cb3b1d22">

Link for the final prototype: 

https://www.figma.com/proto/gwLQjwYQ1BAnqNX6CYqrru/Cartography?page-id=0%3A1&type=design&node-id=324-12880&viewport=219%2C-258%2C0.04&t=3PVbMOsyRwqXcqBw-1&scaling=scale-down&starting-point-node-id=324%3A12880&mode=design

**Comment by Chinmayk79** [comment]
![Chinmay_Cartography_1](https://github.com/mapschool/course/assets/122165522/51bf3180-2be2-41c4-a3d0-fa04693176ad)

![Chinmay_Cartography_2](https://github.com/mapschool/course/assets/122165522/1be94075-bb18-4d59-81b8-c2e7b29eed71)
1. Community Story Wall: Create an app that transforms physical walls into digital storytelling canvases. Users can contribute short stories, poems, or messages to specific walls (can be a landmark) in their city, creating an ever-evolving community story walls.                             
2. Scenic Sketchbook: Build an app that encourages users to engage in urban sketching. The app could suggest picturesque locations, provide digital sketching tools, and allow users to share their creations with others who visit the same spots.


![Chinmay_SkectScape](https://github.com/mapschool/course/assets/122165522/2581f318-550f-4587-bfe0-89d0277d2e00)

Project Documentation (WIP) - (https://www.figma.com/file/DIqP2FfyHU3ZFgKaHhDa5B/SketchScape-App?type=design&node-id=1308%3A2491&mode=design&t=DxmWeYBTPKmfNb5T-1)

App prototype (WIP) - (https://www.figma.com/proto/DIqP2FfyHU3ZFgKaHhDa5B/SketchScape-App?page-id=1202%3A5222&type=design&node-id=1202-6537&viewport=6706%2C2050%2C0.39&t=rQ7s0CrvF8A3zBLC-1&scaling=scale-down&starting-point-node-id=1202%3A6533&show-proto-sidebar=1&mode=design)

**Comment by Surabhiiy** [comment]
**Idea 1**
Integration of a map into an app designed as my service design project. 
The app's goal is to showcase all the details about street food vendors available in a user's selected area. The integration of a map in the app will assist users in locating and reaching a particular street food vendor stall. 

![Presentation](https://github.com/mapschool/course/assets/126863486/d8cc7041-818f-4ef3-b7f8-07babbc65cd9)
![Presentation 2](https://github.com/mapschool/course/assets/126863486/86d073a0-aa24-45a7-ab79-68be50747d0b)
![Presentation 3](https://github.com/mapschool/course/assets/126863486/cb6eff39-b4d9-4566-a30c-edecf1181b11)
![Presentation 4](https://github.com/mapschool/course/assets/126863486/72fc2318-f4c6-4531-8f37-5a24039a79fc)


Prototype Link- https://www.figma.com/proto/vj0cQQmNhmUwKjhJnefAj3/Map-in-App?page-id=0%3A1&type=design&node-id=61-930&viewport=-3289%2C95%2C0.5&t=WMY88tZhw7eTquWG-1&scaling=scale-down&starting-point-node-id=61%3A930&mode=design














_**Idea 2**
Adding a map in an app that provides simplified data about air quality and pollution for the nearby area. The app sends personalized notifications and health recommendations based on the air quality in the user's area. 
By adding a map, users can visually see the distribution of pollution levels across different locations, aiding in a better understanding of the air quality in their vicinity and surrounding areas. The map enables users to set alerts based on specific geographic areas. Also, by incorporating air quality data into map-based route planning, users can choose paths with better air quality, especially valuable for outdoor activities.

**Idea 3**
Redesigning the experience of a hyperlocal delivery app by Integrating AR maps to assist delivery person in navigating their routes more effectively. This AR map integration aims to enhance the delivery experience by providing real-time, dynamic visual guidance to delivery person, ensuring efficient and accurate navigation to the delivery destination._

**Comment by arifalimw** [comment]
**Ideas for App:**

1. **Add a new feature/workflow that includes a map in an existing app**
.
In Zomato include a feature of curated restaurant hops based on themes, cuisines, or dietary preferences in a modified zomato map for restaurants. You can become food influencers and earn rewards by trying their recommendations. Get exclusive deals and insider tips. 
"Food Quests"- Compete with friends in themed challenges, exploring new restaurants and earn rewards as you move or cover  journeys
"Foodie Squad"-  Share recommendations, discover hidden gems together, and unlock group discounts

2. **Create a new map-based app**

An app for the elderly where users can easily input tasks like "Buy groceries," "Go to the bank," and "Meet friends at restaurant" with simple voice or text commands and the map optimizes and prioritise the closest grocery store, bank branch, etc., based on real-time traffic and walking distance. Filtering of routes based on preferred walking distance, public transportation availability, private transport or wheelchair accessibility can also be an option.
They can also leave comments like they need help with something as a floating comment on map where others can come and suggest what to be done or where to go...

![Map Feature (1)](https://github.com/mapschool/course/assets/126864913/35f81d56-4b10-4add-8e3a-6b46017b3232)

Prototype: [Link](https://www.figma.com/proto/VbJPJS5GL5XKC3XNEuoYYg/Zomato-MAP-Project?type=design&node-id=103-1826&t=gIT12eUuBNydehgP-1&scaling=contain&page-id=0%3A1&starting-point-node-id=103%3A1827&mode=design)

**Comment by tinnicreatesXOXO** [comment]
Sanjana Maiti
1) Adding map feature to news app like- beatroot(by Faye D'souza) for clarity in where exactly the instances are happening.

2) App for Alzihmer's to help patients trace back their routes.

3) Travel pin app to spot locations to visit for travellers to make it easier to plan iternery with real time AR letting them see how the places are and decide if they actually want to visit.

Final: 

**News app with map**

Users: 
Age group specific news so that it is easier for younger audience to grasp.
Kids
Teenagers
Young Adults
Adults

Similar Apps/ Websites:
1) Liveuamap- up-to-date on breaking events around the globe. 
2) Worldly map - Ipad based good news around the world.
3) Ushahidi - Real time crisis and disaster response.
4) Citymapper - This app is primarily a transit navigation app, but it also includes a news feed that highlights local events and happenings.

Problem Areas :
1) India's locale specific news
2) Having news aggregated from different trusted sources
3) Having age appropriate news
4) Having location based search with multiple layered high quality maps.

Features:
1)Map layers: Overlay different map layers on top of news stories, such as traffic, weather, or event locations.
2) Location enabled accurate news
3) Pin pointing news stories to reach the map
4)Augmented reality (AR): Use AR to overlay news stories and information onto the real world through the phone's camera.
5) Multilingual support
6)Timeline view: Show the chronology of events on a map, allowing users to see how a story unfolded over time.
7) Age group accurate news.
8) Have saved news locations.

Final Project with process
https://www.behance.net/gallery/192921155/CartoCat-map-based-news-app

**Comment by rasagy** [comment]
Closing this, was great to see a bunch of great ideas come through this time!
