### ISSUE TITLE
Mapmaking explorations

### ISSUE THREAD

**Issue by pkd2512** [mapschool/cartography#82]
A brief introduction to using QGIS for making custom maps with geographical datasets.
Download QGIS LTR version [here](https://www.qgis.org/en/site/)
A [showcase](https://www.flickr.com/groups/qgis/pool/) of some maps made using the tool.

For avid readers, you can [read the documentation](https://docs.qgis.org/3.4/en/docs/user_manual/) which is a handy reference to understand a specific tool or process whenever you get stuck.

We shall use this thread to document classwork and WIPs.

**Comment by tinnicreatesXOXO** [comment]
Sanjana Maiti
![1st map](https://github.com/mapschool/course/assets/126864929/fe345073-45b9-427b-bb0a-1c9a39783368)

<img width="1379" alt="Screenshot 2024-01-29 at 4 24 48 PM" src="https://github.com/mapschool/course/assets/126864929/d37fda0b-2fcf-4701-a4e8-036a23e0b758">

![wQoLO-bangalore (1)](https://github.com/mapschool/course/assets/126864929/447139f7-029e-43a3-a825-98cc632f22a2)

Centroid based on yearly GDP
![centroid](https://github.com/mapschool/course/assets/126864929/2e1cf1df-eb34-422e-8dfc-b0bc32789f42) 


Worldwide airports
![AIRPORTS WW](https://github.com/mapschool/course/assets/126864929/d6edbc06-04f5-4885-a0ed-9fb9447c9086)
rivers
![rivers](https://github.com/mapschool/course/assets/126864929/b2f2d59a-1816-4c0a-b3bf-26ebe06d2046)

Indian airports
![india nad aiports](https://github.com/mapschool/course/assets/126864929/afc4890c-8519-40e6-a9ac-442cc0a09d5b)

India's pop. density
![world pop](https://github.com/mapschool/course/assets/126864929/f0bb7e0a-323a-47c6-8240-79a49dada790)

 Darjeeling Terrain
![darj](https://github.com/mapschool/course/assets/126864929/33b729da-0fcb-46e8-b525-5c49cf7e578c)

Map poster
<img width="1190" alt="Frame 1" src="https://github.com/mapschool/course/assets/126864929/b8df9a7f-3e81-4efc-ad63-8f677465e20d">

**Comment by gmeenal98** [comment]
<img width="725" alt="Screenshot 2024-01-29 at 4 09 55 PM" src="https://github.com/mapschool/course/assets/127397480/d4d2d381-a4e1-4a08-8694-216b37daff54">

**Comment by UtkarshSing98** [comment]
![l8J7b--insert-title-here- (1)](https://github.com/mapschool/course/assets/126862749/fd972535-f887-4ac5-b983-8a17734538c0)

![Print Layout_choroplyth](https://github.com/mapschool/course/assets/126862749/3d082216-8081-47aa-a361-5953982e7f84)

![river 3-1](https://github.com/mapschool/course/assets/126862749/28ac1567-6203-4008-84d2-27ed2e13b13d)





![Print Layout 2](https://github.com/mapschool/course/assets/126862749/78fd40f4-2175-4ba2-bd58-975b984b6d95)

![airport 2](https://github.com/mapschool/course/assets/126862749/852e175e-10dd-4fb5-aa96-7a8160efe94b)

![Airports altitude india](https://github.com/mapschool/course/assets/126862749/d45bf474-4422-4907-92cd-83cbde210503)

![My maps](https://github.com/mapschool/course/assets/126862749/669e2533-58eb-4d5e-a164-291a172e4358)


https://github.com/mapschool/course/assets/126862749/ec5f9d49-dece-49f2-bfad-0f07a2e1a2e4

![a3 (8)](https://github.com/mapschool/course/assets/126862749/9a4f974b-78b7-46e6-9cc6-0f0e93199dc4)

**Comment by Chinmayk79** [comment]
![1oOIu-chinmayk_map](https://github.com/mapschool/course/assets/122165522/c722a378-8fa5-4090-968e-6dacb37ce84c)
![Rivers_Chinmayk](https://github.com/mapschool/course/assets/122165522/d8a2b3cb-955b-405f-b3fa-8ce76a09f2be)

Country GDP
![GDP_Country](https://github.com/mapschool/course/assets/122165522/f1dc24d0-5828-444a-9b88-3112c5cb5f6a)

World Airports, ports and stations
![Airports, ports and stations](https://github.com/mapschool/course/assets/122165522/30b8ddfa-20a0-4c00-a965-a2213da68e45)
Indian Airports
![Indian Airports](https://github.com/mapschool/course/assets/122165522/7b5cf018-331c-41b9-adf6-9b03d54074b4)

India Population data_2020
![India population data](https://github.com/mapschool/course/assets/122165522/9463ba6b-b158-44a9-a4be-8df21dc3af15)

**Comment by SamruddhiBulbule** [comment]
![Uploading vz8Me--insert-title-here-.png…]()

**Comment by arunikasajith** [comment]
![bengaluru_points_arunika](https://github.com/mapschool/course/assets/126863213/ea5f17a8-839e-4cde-9c1c-ec349dc49515)

QGIS exploration - rivers and lakes
![image](https://github.com/mapschool/course/assets/126863213/8ad4f101-c9bd-4c4c-8a14-bcc71fe1fbb4)

QGIS exploration - income group classification
![image](https://github.com/mapschool/course/assets/126863213/7a20cf74-edba-44fc-8463-9f086de4e074)

Mini assignment
![wildlife_trafficking_map](https://github.com/mapschool/course/assets/126863213/2532f85e-4cda-4655-93a1-58d2abead1f2)

**Comment by andriamarinus** [comment]
![8EYB4-peenyamap_andria (2)](https://github.com/mapschool/course/assets/126863696/d819a0ff-30e3-4119-95a2-1b7bc4949641)
![rivers se asia](https://github.com/mapschool/course/assets/126863696/6f326bbb-46e6-46dd-8b5b-3e48766451f3)



![income group se asia](https://github.com/mapschool/course/assets/126863696/95c352cd-2a4c-4c18-8e4b-2cc3748ca737)
![pop est](https://github.com/mapschool/course/assets/126863696/237cad07-7309-4ff8-910d-c796d0fa5515)
![image](https://github.com/mapschool/course/assets/126863696/01a2d6f1-a41e-4d78-8ac4-36715db15dfc)
![image](https://github.com/mapschool/course/assets/126863696/1f57523e-6765-46a7-a3ca-bf95f25373e9)
![image](https://github.com/mapschool/course/assets/126863696/19c4effe-cad7-48ba-9a87-7ac2b4f6c965)
![image](https://github.com/mapschool/course/assets/126863696/e713de46-fa56-4190-9ef7-35906b48fa3c)
![image](https://github.com/mapschool/course/assets/126863696/11e49a3f-3e98-4737-8f41-ce774adcf4ad)
![image](https://github.com/mapschool/course/assets/126863696/e9b6233d-68a4-4e54-805a-a6f6b8147695)

**Comment by Meg-exe** [comment]
Datawrapper Exploration-
![T4peL-bengaluru](https://github.com/mapschool/course/assets/126862966/b891cc74-5b78-425b-97d4-0d5ee81e9a72)

Google Maps Exploration-
![image](https://github.com/mapschool/course/assets/126862966/389e87d0-fe18-46ae-afaf-8506be701a87)

Datawrapper + OSM + Overpass-turbo Exploration-

![T4peL-geojson-area-marker](https://github.com/mapschool/course/assets/126862966/4fc622f9-a960-4760-8941-21ad9ab6e4d8)

QGIS Explorations-
![rivermap](https://github.com/mapschool/course/assets/126862966/bc893fd8-f438-4cdf-a414-08feb2e02a6c)

![income_grp_map](https://github.com/mapschool/course/assets/126862966/cb668718-00ba-42a1-9879-aa57c71958c9)

![Layout 2](https://github.com/mapschool/course/assets/126862966/1ac7dd75-ab60-45b4-880e-d59a85f36db9)

![Layout 1](https://github.com/mapschool/course/assets/126862966/c5a9834a-58d8-44d3-95a7-299458f8fb27)

![Screenshot 2024-01-31 150934](https://github.com/mapschool/course/assets/126862966/3208530c-0bcc-4988-ba7f-b73f62d7ba02)

![Screenshot 2024-01-31 154329](https://github.com/mapschool/course/assets/126862966/cd089a7e-2773-4fea-8819-c3783ea24341)

India's population density
![popu](https://github.com/mapschool/course/assets/126862966/fe5bebbc-6700-4678-badb-ae1b2ec5e7b0)

Terrain view in threejs
![three](https://github.com/mapschool/course/assets/126862966/1d7dddb0-0a1b-433b-982c-7551cf54d35f)

Mini Assignment Poster
![A4 - 6](https://github.com/mapschool/course/assets/126862966/6306a116-f08b-4b76-bca0-17ce01f98787)

**Comment by anjalikothari** [comment]
![n78bS-myfirstmap_anjali](https://github.com/mapschool/course/assets/126863089/c0a3abbe-4659-420a-bccf-ff14675c8e23)
![river world](https://github.com/mapschool/course/assets/126863089/1f03138f-fcfd-4cfc-89ea-92d01293db94)
![world population](https://github.com/mapschool/course/assets/126863089/c1435682-bd8f-4152-9af4-35c4b77c6611)
![world gdp](https://github.com/mapschool/course/assets/126863089/07840abf-613c-4a40-a366-813926fc02fc)
![world airports](https://github.com/mapschool/course/assets/126863089/ad0cf61a-d6f7-4a6f-a79f-344d5c76c185)
![India airports](https://github.com/mapschool/course/assets/126863089/4c6c7546-67f2-441a-b914-03660eb16b1b)
![platinum city](https://github.com/mapschool/course/assets/126863089/831a0e58-d8d0-4c89-b857-0038d12ffb53)
![pc1](https://github.com/mapschool/course/assets/126863089/1eee2cd9-c839-4fe7-b4b4-f6baee45bb0c)
![image](https://github.com/mapschool/course/assets/126863089/be491ee5-5c55-42f2-a5d7-690623582588)
![image](https://github.com/mapschool/course/assets/126863089/f58ba67d-f25e-4347-81dd-5c45a4c488af)
![image](https://github.com/mapschool/course/assets/126863089/2e70997f-40ea-4be5-9fe2-4995922188d2)

India population density
![India pop density](https://github.com/mapschool/course/assets/126863089/9180882e-8ae3-4c39-92be-f3452a865971)
![hill](https://github.com/mapschool/course/assets/126863089/4be872c6-d9c2-4809-91da-63abaaa800cd)

**Comment by Surabhiiy** [comment]
![ALrBa-first-map](https://github.com/mapschool/course/assets/126863486/044d888b-44ba-4cb6-b52f-e5237df2fc20)
Rivers Representation
![rivers1](https://github.com/mapschool/course/assets/126863486/ec2f25b7-a7a0-41dc-9317-b622b97cc0b4)

World Airports
![Airports World](https://github.com/mapschool/course/assets/126863486/69cd9077-2155-43cd-a5f4-dcda499909a5)
Airports of India
![Airports India](https://github.com/mapschool/course/assets/126863486/750a8f96-3787-4e1f-a659-ecfe6d3fede4)
GDP Map -Cholopleth
![chl](https://github.com/mapschool/course/assets/126863486/f8aa2e2e-7546-474f-9360-14c1bc4cc7cd)
![South_Asia_non_political,_with_rivers](https://github.com/mapschool/course/assets/126863486/3c49994a-22c9-43df-8944-11bcd782f32d)
![Shaktipeeth data viz 3](https://github.com/mapschool/course/assets/126863486/4886e8e4-15b5-44da-b316-9834509c4a0e)

**Comment by SamruddhiBulbule** [comment]
![vz8Me--insert-title-here-](https://github.com/mapschool/course/assets/126863744/7b199921-e764-48b9-8080-4a47068e091e)
### **Income Map**


![Income Map_page-0001](https://github.com/mapschool/course/assets/126863744/67ddfa20-bb62-456a-90f7-4b21a52cf5fb)


### **Poster**

<img width="842" alt="A3 _ 297x420 mm" src="https://github.com/mapschool/course/assets/126863744/4ebcd7f9-940e-4634-9990-7b8e73c6bd73">

**Comment by ipsitaccc** [comment]
![CCGS8-bengaluru_ipsita](https://github.com/mapschool/course/assets/126864097/1498f113-3c37-4689-bd89-4fac2f9435f2)
![CCGS8-bengaluru_ipsita (1)](https://github.com/mapschool/course/assets/126864097/7272f64c-fc67-4f86-9f91-da0ab9031f70)


### Rivers of India on QGIS

![Rivers of India](https://github.com/mapschool/course/assets/126864097/89414a5a-258d-40e3-9f00-15ee4cf10155)

### Economy Maps Chloropleth

![Economy Groups](https://github.com/mapschool/course/assets/126864097/cdbed874-b88d-4d0c-adcb-44fa856e2601)

### Population Map using Centroids 
(but it is centroids of every land parcel and not just country)

![Centroid Map for Population](https://github.com/mapschool/course/assets/126864097/7d4263cc-b80b-42c6-8209-5ccb02d55de3)

![Centroid 2](https://github.com/mapschool/course/assets/126864097/e69dee4b-ce68-427a-a64d-8b187b0c0545)

Draft 1 (WIP)
To edit: reduce the number of categories, add category layer maps, work on colour scale

![Map 1-01](https://github.com/mapschool/course/assets/126864097/54b9e3d4-920f-4e9e-be3b-174022400c8b)

####FINAL THEMATIC SUBMISSION

![1](https://github.com/mapschool/course/assets/126864097/518d0ce8-f4c7-4d26-aa57-0fb3525ad64c)
![2](https://github.com/mapschool/course/assets/126864097/8f51dd21-281d-4a3e-828a-999efda95010)

**Comment by arifalimw** [comment]
![zps6i-pc-area-map](https://github.com/mapschool/course/assets/126864913/84558098-76eb-48b3-b6e4-c183ee72f41f)

**Comment by Eesha-2002** [comment]
![9kbxz-my-little-bangalore-map (1)](https://github.com/mapschool/course/assets/126862702/97dadee3-016d-4b74-9bd1-e4f00ffa1e40)
![eqKiK-places-i-have-lived-in-](https://github.com/mapschool/course/assets/126862702/218755f3-86b1-4e32-baab-385c88c381fa)
![diOtd-platinum-city](https://github.com/mapschool/course/assets/126862702/1d125942-fe8b-4ac4-ac9b-ea3ea5f4d522)



### Temples of Bhubaneshwar

Map 1 - Zoomed out version to show spread of the temples in the city
![BbsrTemple2](https://github.com/mapschool/course/assets/126862702/e2afce1e-b02b-48cd-b54e-674569590b8d)

**Comment by pkd2512** [comment]
Rivers from natural earth dataset, shown using gradients and varying widths encoded with river widths
<img width="1475" alt="image" src="https://github.com/mapschool/course/assets/7580745/fdac10ad-7ab2-47b3-a2d2-1267f8383e54">

**Comment by anjalikothari** [comment]
![image](https://github.com/mapschool/course/assets/126863089/1188c7e9-ecd0-4fff-83ad-48a9a130dbe8)

**Comment by NomeshwariReddy** [comment]
<img width="1263" alt="Screenshot 2024-01-31 at 10 55 09 AM" src="https://github.com/mapschool/course/assets/126862650/b1cfb77b-9cf7-4303-9c2b-50dc30c13f03">
<img width="1263" alt="Screenshot 2024-01-31 at 10 55 43 AM" src="https://github.com/mapschool/course/assets/126862650/2b58a62e-8c75-4b1b-be5a-66597ea4ce96">
<img width="1263" alt="Screenshot 2024-01-31 at 10 51 46 AM" src="https://github.com/mapschool/course/assets/126862650/820a4f17-d6d7-4b37-af55-12573b96e51d">
<img width="728" alt="Screenshot 2024-02-01 at 3 09 22 PM" src="https://github.com/mapschool/course/assets/126862650/1833f327-70ba-4cd4-a712-d48a7f41f2a3">
<img width="1247" alt="Screenshot 2024-02-01 at 3 43 42 PM" src="https://github.com/mapschool/course/assets/126862650/2fe85217-3704-4a15-b816-989a16496fe8">
<img width="1247" alt="Screenshot 2024-02-01 at 3 43 33 PM" src="https://github.com/mapschool/course/assets/126862650/537da58b-7aa0-4e2d-8c4b-ced0e2159ddd">
<img width="1247" alt="Screenshot 2024-02-01 at 3 43 23 PM" src="https://github.com/mapschool/course/assets/126862650/42acaf37-7316-4ab8-af76-5aee8f013443">


<img width="1247" alt="Screenshot 2024-02-01 at 3 36 04 PM" src="https://github.com/mapschool/course/assets/126862650/36697534-71aa-4e05-9a40-34eb2feb01d1">

<img width="1247" alt="Screenshot 2024-02-01 at 3 46 42 PM" src="https://github.com/mapschool/course/assets/126862650/bfd43944-a0a1-49ac-bdbf-5f90c9ab0749">
<img width="1247" alt="Screenshot 2024-02-01 at 3 47 00 PM" src="https://github.com/mapschool/course/assets/126862650/0b967e9c-73f9-4ace-af94-ef4c275982a3">
<img width="1224" alt="Screenshot 2024-02-03 at 1 29 20 PM" src="https://github.com/mapschool/course/assets/126862650/d61722fe-3b95-4d21-a4e1-2f088a23dfbb">

MINI PROJECT ITERATION-1

<img width="1260" alt="Screenshot 2024-02-03 at 1 33 39 PM" src="https://github.com/mapschool/course/assets/126862650/06d4a345-34eb-419f-b3e4-0fbf1aa35525">


<img width="842" alt="rail rivers" src="https://github.com/mapschool/course/assets/126862650/bb803a9e-cc97-46da-90f5-72842d2b4b51">

**Comment by arifalimw** [comment]
![Untitled (1)](https://github.com/mapschool/course/assets/126864913/32d04f04-5cbb-4729-8771-7f2642dde128)

**Exploring Terrains in 3D**
<img width="516" alt="terrain" src="https://github.com/mapschool/course/assets/126864913/7f1253eb-38db-4072-8347-8a5f668dac42">

![01 02 2024_16 05 35_REC (1)](https://github.com/mapschool/course/assets/126864913/2d38d73c-971e-4cc3-bcf6-c2639acd696c)

**Mini Assignment**
Iteration 1

<img width="1191" alt="Frame 4 (2)" src="https://github.com/mapschool/course/assets/126864913/0aed8965-f236-4541-83fe-fe4c7e153c79">

**Iteration 2**

![Frame 5 (3)](https://github.com/mapschool/course/assets/126864913/b6b25bfa-cfd6-4e63-900a-cb2100d1815d)

**Comment by anmllol** [comment]
**Day 3**
![map](https://github.com/mapschool/course/assets/126863153/786898a8-f121-48c1-be84-7658db94a296)

![polygon map](https://github.com/mapschool/course/assets/126863153/d7314cc4-f871-44b0-9da4-3716c54359a0)

![Mini Assignment Map](https://github.com/mapschool/course/assets/126863153/333c861d-6c66-47f7-86d5-228b4f4707c3)

**Comment by gmeenal98** [comment]
![A4 - 5](https://github.com/mapschool/course/assets/127397480/2a588b07-4fb7-4242-a0b7-706fc1d301f6)
![A4 -2 ](https://github.com/mapschool/course/assets/127397480/d37a15f6-93aa-4026-9393-bf34b059f94a)
<img width="624" alt="Screenshot 2024-01-31 at 12 39 11 PM" src="https://github.com/mapschool/course/assets/127397480/5d04cfdf-39a3-4c37-b4ac-414573c0abf2">
<img width="1357" alt="Screenshot 2024-01-30 at 3 41 56 PM" src="https://github.com/mapschool/course/assets/127397480/02d2dd86-395e-440e-842b-39333eb90c68">
![Uploading Screenshot 2024-02-19 at 2.44.14 PM.png…]()
![Uploading Screenshot 2024-02-19 at 2.47.48 PM.png…]()
